// Real relational SQLite, serialized per company into durable storage with CAS.
// @ts-ignore sql.js asm build has the same API as its wasm build.
import initSqlJs from 'sql.js/dist/sql-asm.js';
import type {Database} from 'sql.js';
import {tables,businessSample,type TableName} from '../lib/business.ts';
import type {Repository} from './api.ts';
const engine=initSqlJs();
const ddl=`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,name TEXT NOT NULL,price_cents INTEGER CHECK(price_cents>=0),cost_cents INTEGER CHECK(cost_cents>=0),source_code TEXT,unit TEXT,category TEXT,specification TEXT);
CREATE TABLE IF NOT EXISTS suppliers(id TEXT PRIMARY KEY,name TEXT NOT NULL,lead_days INTEGER NOT NULL CHECK(lead_days>=0),on_time_percent REAL NOT NULL CHECK(on_time_percent BETWEEN 0 AND 100));
CREATE TABLE IF NOT EXISTS purchase_orders(id TEXT PRIMARY KEY,supplier_id TEXT NOT NULL REFERENCES suppliers(id),product_id TEXT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity>=0),unit_cost_cents INTEGER NOT NULL CHECK(unit_cost_cents>=0),due_date TEXT NOT NULL,status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS inventory(product_id TEXT PRIMARY KEY REFERENCES products(id),stock INTEGER NOT NULL CHECK(stock>=0),safety_stock INTEGER NOT NULL CHECK(safety_stock>=0),as_of TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sales_orders(id TEXT PRIMARY KEY,product_id TEXT NOT NULL REFERENCES products(id),date TEXT NOT NULL,quantity REAL NOT NULL,unit_price_cents INTEGER NOT NULL CHECK(unit_price_cents>=0),unit_cost_cents INTEGER CHECK(unit_cost_cents>=0),amount_cents INTEGER,is_promotion TEXT);
CREATE TABLE IF NOT EXISTS campaigns(id TEXT PRIMARY KEY,product_id TEXT NOT NULL REFERENCES products(id),name TEXT NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL,discount_percent REAL NOT NULL CHECK(discount_percent BETWEEN 0 AND 100),budget_cents INTEGER NOT NULL CHECK(budget_cents>=0));
CREATE TABLE IF NOT EXISTS deliveries(id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES sales_orders(id),promised_date TEXT NOT NULL,delivered_date TEXT NOT NULL,status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS returns(id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES sales_orders(id),quantity INTEGER NOT NULL CHECK(quantity>=0),reason TEXT NOT NULL,status TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS sales_product_date ON sales_orders(product_id,date);`;
export function query(db:Database,sql:string,args:any[]=[]){const stmt=db.prepare(sql);try{stmt.bind(args);const rows:any[]=[];while(stmt.step())rows.push(stmt.getAsObject());return rows}finally{stmt.free()}}
function insert(db:Database,data:any){for(const [table,definition] of Object.entries(tables)){const rows=data[table]??[];if(!Array.isArray(rows)||rows.length>5000)throw Error('每张表最多导入 5000 行');for(const row of rows){const values=definition.columns.map(c=>{const value=row[c];const numeric=['price_cents','cost_cents','lead_days','on_time_percent','quantity','unit_cost_cents','stock','safety_stock','unit_price_cents','discount_percent','budget_cents','amount_cents'].includes(c);if(value==null&&((table==='products'&&['price_cents','cost_cents','source_code','unit','category','specification'].includes(c))||(table==='sales_orders'&&['unit_cost_cents','amount_cents','is_promotion'].includes(c))))return null;if(table==='sales_orders'&&['quantity','amount_cents'].includes(c)&&typeof value==='number'&&Number.isFinite(value)&&Math.abs(value)<=1e10){if(c==='amount_cents'&&!Number.isInteger(value))throw Error('金额必须为整数分');return value}if(!numeric&&typeof value==='string'&&value.length<=2000&&(value.trim().length>0||c==='delivered_date'))return value;if(numeric&&typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=1e10){if(!['on_time_percent','discount_percent'].includes(c)&&!Number.isInteger(value))throw Error('数量和金额必须为整数');return value}throw Error(table+' 的 '+c+' 格式不正确')});for(const c of definition.columns){if(['date','due_date','as_of','start_date','end_date','promised_date'].includes(c)||c==='delivered_date'&&row[c]!==''){if(!/^\d{4}-\d{2}-\d{2}$/.test(row[c])||new Date(row[c]).toISOString().slice(0,10)!==row[c])throw Error('日期格式不正确')}}if(table==='campaigns'&&row.end_date<row.start_date)throw Error('活动结束日期早于开始日期');const primary=table==='inventory'?'product_id':'id';db.run(`INSERT INTO ${table} (${definition.columns.join(',')}) VALUES (${definition.columns.map(()=>'?').join(',')}) ON CONFLICT(${primary}) DO UPDATE SET ${definition.columns.filter(c=>c!==primary).map(c=>c+'=excluded.'+c).join(',')}`,values)}}}
export async function openBusiness(repo:Repository,tenant:string){if(!/^[a-zA-Z0-9_-]{1,64}$/.test(tenant))throw Error('企业编号无效');const saved=await repo.get('business/'+tenant),SQL=await engine,db:Database=new SQL.Database(saved?Buffer.from(saved.value.sqlite,'base64'):undefined);db.run(ddl);for(const [table,cols] of Object.entries({products:{source_code:'TEXT',unit:'TEXT',category:'TEXT',specification:'TEXT'},sales_orders:{amount_cents:'INTEGER',is_promotion:'TEXT'}})){const existing=query(db,'PRAGMA table_info('+table+')').map(r=>r.name);for(const [name,type] of Object.entries(cols)){if(!existing.includes(name))db.run('ALTER TABLE '+table+' ADD COLUMN '+name+' '+type)}}if(!saved&&tenant==='demo'){insert(db,businessSample());await repo.put('business/demo',{sqlite:Buffer.from(db.export()).toString('base64'),source:'synthetic',revision:1,updatedAt:new Date().toISOString()},null)}return {db,source:saved?.value.source??(tenant==='demo'?'synthetic':'empty'),revision:saved?.value.revision??(tenant==='demo'?1:0)}}
export async function importBusiness(repo:Repository,tenant:string,data:any,revision:number){if(tenant==='demo')throw Error('公共演示数据不可修改');if(!data||typeof data!=='object'||Array.isArray(data)||Object.keys(data).some(k=>!Object.hasOwn(tables,k)))throw Error('请使用数据库导入模板中的表名');const saved=await repo.get('business/'+tenant);if((saved?.value.revision??0)!==revision)throw Error('数据已更新，请刷新后重试');const {db}=await openBusiness(repo,tenant);try{db.run('BEGIN');insert(db,data);db.run('COMMIT');const bytes=db.export();if(bytes.byteLength>16*1024*1024)throw Error('当前试用版每家企业数据库上限为 16MB');if(!await repo.put('business/'+tenant,{sqlite:Buffer.from(bytes).toString('base64'),source:'provided',revision:revision+1,updatedAt:new Date().toISOString()},saved?.version??null))throw Error('数据更新冲突，请刷新后重试');return {ok:true,revision:revision+1}}finally{db.close()}}
export async function databaseView(repo:Repository,tenant:string,table:TableName){if(!Object.hasOwn(tables,table))throw Error('表不存在');const {db,source,revision}=await openBusiness(repo,tenant);try{return {source,revision,table,columns:tables[table].columns,rows:query(db,`SELECT * FROM ${table} LIMIT 500`),total:query(db,`SELECT COUNT(*) n FROM ${table}`)[0].n,counts:Object.fromEntries(Object.keys(tables).map(t=>[t,query(db,`SELECT COUNT(*) n FROM ${t}`)[0].n]))}}finally{db.close()}}

