const money=(v:number)=>(v/10000).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:4})+'元';
const quantity=(v:number)=>Number(v.toFixed(3));
export function productEvidence(c:any,products:any[],selected:boolean){
 const rows=selected?products:[];
 return {text:rows.length?rows.map(p=>{const sales=c.sales.filter((r:any[])=>r[2]===p.id),positive=sales.filter((r:any[])=>r[4]>0),prices=positive.map((r:any[])=>r[6]),latest=positive.at(-1),weighted=positive.length?Math.round(positive.reduce((n:number,r:any[])=>n+r[7],0)/positive.reduce((n:number,r:any[])=>n+r[4],0)):null;return `${p.name}（${p.id}）：本期售出${p.sold}${p.unit}、退货${p.returned}${p.unit}；销售净额${money(p.revenue_scaled)}。${latest?`最近一次销售单价${money(latest[6])}/${p.unit}，时间${latest[5].replace('T',' ')}（拟）；期间售价${money(Math.min(...prices))}至${money(Math.max(...prices))}/${p.unit}，加权成交均价${money(weighted!)}/${p.unit}。`:'本期没有正向销售价格。'}\n本期买入${p.bought}${p.unit}、损耗${p.lost??0}${p.unit}、期末库存${p.stock}${p.unit}（拟）；演示采购成本${money(p.cost_scaled)}/${p.unit}、毛利${money(p.gross_profit_scaled)}（拟）。原始销售可按附件2行号回查。`;}).join('\n\n'):`本期${c.sales.length}条销售明细、${c.products.length}种商品，销售净额${money(c.income.revenue_scaled)}。`,data:{products:rows.map(p=>({id:p.id,name:p.name,unit:p.unit,stock:p.stock,bought:p.bought,sold:p.sold,returned:p.returned,lost:p.lost,cost_scaled:p.cost_scaled,revenue_scaled:p.revenue_scaled,gross_profit_scaled:p.gross_profit_scaled,sourceRows:c.sales.filter((r:any[])=>r[2]===p.id).slice(0,8).map((r:any[])=>r[0])})),count:c.products.length}};
}
export function procurementEvidence(c:any,ids:string[]){
 const orders=c.purchases.filter((p:any)=>!ids.length||p.lines.some((l:any)=>ids.includes(l.product_id))).map((p:any)=>{const lines=p.lines.filter((l:any)=>!ids.length||ids.includes(l.product_id));return {id:p.id,date:p.date,supplier:p.partner,orderAmount_scaled:p.amount_scaled,selectedAmount_scaled:lines.reduce((n:number,l:any)=>n+l.amount_scaled,0),lines,quantity:quantity(lines.reduce((n:number,l:any)=>n+l.quantity,0))}}),total=orders.reduce((n:number,p:any)=>n+p.selectedAmount_scaled,0);
 return {text:orders.length?`${ids.length?'所选商品':'全部商品'}本期采购金额${money(total)}（拟），共${orders.length}张相关采购单。${ids.length?'金额只统计所选商品明细；整张采购单总额另列，付款属于整单，不能擅自归到该商品。':''}\n`+orders.slice(0,8).map((p:any)=>`${p.date} · ${p.supplier} · ${p.id}：所选明细${money(p.selectedAmount_scaled)}（拟），整单${money(p.orderAmount_scaled)}（拟）。`).join('\n'):'所选期间没有匹配采购单；以前采购仍可能影响期末库存。',data:{orders,total_scaled:total,orderCount:orders.length,suppliers:c.suppliers.filter((p:any)=>!ids.length||c.products.some((x:any)=>ids.includes(x.id)&&x.supplier_id===p.id))}};
}
export function rankingEvidence(products:any[],options:any){
 const names:any={quantity:'正向销量',revenue:'销售净额',gross:'销售毛利（拟）',margin:'销售毛利率（拟）'},metric=options.metric??'revenue';
 const amount=(p:any)=>metric==='quantity'?p.sold:metric==='gross'?p.gross_profit_scaled:metric==='margin'?(p.revenue_scaled>0?p.gross_profit_scaled/p.revenue_scaled:null):p.revenue_scaled;
 const eligible=products.filter(p=>p.stocked&&amount(p)!==null&&(!options.lossOnly||p.gross_profit_scaled<0)).sort((a,b)=>(amount(a)-amount(b))*(options.ascending?1:-1));
 const rows=eligible.slice(0,options.limit??10).map(p=>({id:p.id,name:p.name,unit:p.unit,sold:p.sold,revenue_scaled:p.revenue_scaled,gross_profit_scaled:p.gross_profit_scaled,margin:p.revenue_scaled>0?p.gross_profit_scaled/p.revenue_scaled:null}));
 return {text:rows.length?`按${names[metric]}${options.ascending?'从低到高':'从高到低'}，列出${rows.length}种商品：\n`+rows.map((p,i)=>`${i+1}．${p.name}（${p.id}）：售出${p.sold}${p.unit}，销售净额${money(p.revenue_scaled)}，毛利${money(p.gross_profit_scaled)}（拟）${p.margin!==null?'，毛利率'+(p.margin*100).toFixed(2)+'%（拟）':''}。`).join('\n'):'所选期间没有符合条件的商品。',data:{metric,ascending:!!options.ascending,limit:options.limit??10,matchedCount:eligible.length,rows}};
}
export function allocateBudget(forecasts:any[],budget:number|null,products:any[]){
 const prices=new Map(products.map(p=>[p.id,p])),requested=forecasts.reduce((n,f)=>n+f.budget_scaled,0);let remaining=budget;
 const ranked=[...forecasts].sort((a,b)=>{const pa:any=prices.get(a.productId),pb:any=prices.get(b.productId),margin=(p:any)=>p.revenue_scaled>0?p.gross_profit_scaled/p.revenue_scaled:0;return margin(pb)-margin(pa)||b.gap-a.gap});
 for(const f of ranked){const desired=f.suggested,packCost=Math.round(f.packSize*f.cost_scaled);if(remaining!==null){const affordable=packCost>0?Math.floor(remaining/packCost)*f.packSize:0;f.suggested=quantity(Math.min(desired,affordable));f.budget_scaled=Math.round(f.suggested*f.cost_scaled);remaining-=f.budget_scaled}f.unconstrainedSuggested=desired;f.budgetLimited=f.suggested<desired;f.allocationReason='按期间毛利率优先、缺口次序分配，不构成全局最优证明；须人工核实交期与次日可售库存。';if(f.dailyPlan?.length&&f.budgetLimited){let available=f.suggested;f.dailyPlan=f.dailyPlan.map((d:any)=>{const suggested=quantity(Math.min(d.suggested,available));available=quantity(available-suggested);return {...d,suggested,budget_scaled:Math.round(suggested*f.cost_scaled)}})}f.unfulfilled=quantity(f.dailyPlan?.length?f.dailyPlan.reduce((n:number,d:any)=>n+Math.max(0,d.lossAdjusted+d.safety-d.suggested),0):Math.max(0,f.gap-f.suggested))}
 return {rows:ranked,totalRequested_scaled:requested,totalAllocated_scaled:ranked.reduce((n,f)=>n+f.budget_scaled,0),budget_scaled:budget,remainingBudget_scaled:remaining,limitedCount:ranked.filter(f=>f.budgetLimited).length,totalProducts:forecasts.length,rule:'以包装为单位，先满足期间毛利率较高的商品，余额不足时减少或不采购；预算约束由程序校验。'};
}
