const day=(s:string)=>new Date(s+'T00:00:00Z'),add=(s:string,n:number)=>new Date(+day(s)+n*86400000).toISOString().slice(0,10),ceil=(n:number)=>Math.ceil(n*1000-1e-8)/1000;
export function forecastProduct(c:any,p:any,params:any,policy:any){
 const native=c.source.case_id==='国内商超-202609-人民币-v3',sampleWeek=(i:number)=>day(add(c.from,i).replace(/^2026-09/,native?c.source.original_period:'2026-09')).getUTCDay();
 const n=Math.round((+day(c.to)-+day(c.from))/86400000)+1,series=Array(n).fill(0),refs:number[]=[],documents=new Set<string>();
 for(const r of c.sales)if(r[2]===p.id){const i=Math.round((+day(r[5].slice(0,10))-+day(c.from))/86400000);series[i]+=Math.max(0,r[4]);refs.push(r[0]);documents.add(r[1])}
 const average=series.reduce((a,b)=>a+b,0)/n;let method='期间日均',mae:any=null,weekdays:number[]=[];
 if(n>=21){const train=series.slice(0,-7),baseline=train.reduce((a,b)=>a+b,0)/train.length;weekdays=Array.from({length:7},(_,w)=>{const values=train.filter((_,i)=>sampleWeek(i)===w);return values.reduce((a,b)=>a+b,0)/values.length});const actual=series.slice(-7),basic=actual.reduce((a,v)=>a+Math.abs(v-baseline),0)/7,weekly=actual.reduce((a,v,i)=>a+Math.abs(v-weekdays[sampleWeek(n-7+i)]),0)/7;mae={days:7,average:basic,weekday:weekly};if(weekly<basic){method='星期分组均值';weekdays=Array.from({length:7},(_,w)=>{const values=series.filter((_,i)=>sampleWeek(i)===w);return values.reduce((a,b)=>a+b,0)/values.length})}}
 const packSize=native?p.pack_size:policy.packSize,lossPercent=native?p.loss_percent:0,lossFactor=1/(1-lossPercent/100),availableStock=native?0:p.stock,safety=ceil(average*(p.safety_days??2));
 const expected=Array.from({length:params.days},(_,i)=>(method==='星期分组均值'?weekdays[day(add(c.to,i+1)).getUTCDay()]:average)*(1+params.uplift/100)),forecast=ceil(expected.reduce((a,b)=>a+b,0)),required=ceil(forecast*lossFactor),gap=ceil(Math.max(0,required+safety-availableStock));
 const dailyPlan=native?expected.map((amount,i)=>{const demand=ceil(amount),need=ceil(demand*lossFactor+safety),suggested=Math.ceil(need*(1+policy.bufferPercent/100)/packSize)*packSize;return {date:add(c.to,i+1),demand,lossAdjusted:ceil(demand*lossFactor),safety,suggested,budget_scaled:Math.round(suggested*p.cost_scaled)}}):[];
 const suggested=native?dailyPlan.reduce((n,r)=>n+r.suggested,0):Math.ceil(gap*(1+policy.bufferPercent/100)/packSize)*packSize;
 return {productId:p.id,name:p.name,supplierId:p.supplier_id,unit:p.unit,asOf:c.to,from:c.from,to:c.to,horizonFrom:add(c.to,1),horizonTo:add(c.to,params.days),days:params.days,uplift:params.uplift,stock:p.stock,availableStock,availabilityRule:native?'生鲜缺少批次效期与次日验收，按次日可售0千克保守测算（拟）；账面库存单列。':'按账面库存测算',sold:p.sold,returned:p.returned,sampleDays:n,average,method,mae,forecast,required,safety,remaining:availableStock-required,gap,suggested,packSize,bufferPercent:policy.bufferPercent,lossPercent,cost_scaled:p.cost_scaled,budget_scaled:Math.round(suggested*p.cost_scaled),dailyPlan,sourceRows:refs.slice(0,8),sourceRowCount:refs.length,invoiceRefs:[...documents].slice(0,8),wholesaleReference_scaled:p.wholesale_reference_scaled??null,wholesaleSourceRows:p.wholesale_refs?.slice(0,5)??[],lossSourceRow:c.lossReference?.rows?.find((r:any[])=>String(r[1])===p.id)?.[0]??null,quantityBasis:'原始正向销量；数量单位'+p.unit+'，退货与拟定损耗参与账面库存结存',assumptions:[...params.assumptions,'以查询截止日为演示决策时点；预测明天为该时点次日。星期模型按原始2022年日期学习，按目标2026年日历预测（拟）。',...(native?['近期损耗率来自附件4，非本月逐笔实测；分日到货，不能一次囤积整个活动期间的生鲜。','包装0.5千克、安全余量按0.2个日均销量为情景（拟）；没有实际供应商到货承诺。']:[])],warning:!p.sold?'期间无正向销量，不能把零预测当作实际无需求。':n<21?'样本少于21天，无法做末7天留出检验。':'留出检验仅衡量历史误差，不保证未来销量。'};
}
