import {salesAnalysis,type SalesFilter} from './sales-analysis.ts';
import {ledgerExists} from './ledger.ts';
import {ledgerAnswer} from './ledger-query.ts';
import {query,openBusiness} from './business-db.ts';import {agentTables} from '../lib/business.ts';import type {Repository} from './api.ts';
export function routeQuestion(text:string){const ids=new Set<string>();if(/整体|全部|经营风险|协同诊断/.test(text))['procurement','demand','forecast','inventory','replenish','strategy','fulfillment'].forEach(x=>ids.add(x));else{if(/供应|采购|交期|报价|进货|到货/.test(text))ids.add('procurement');if(/库存|缺货|积压/.test(text))ids.add('inventory');if(/补货|备货|补多少|够不够|够吗/.test(text)){ids.add('inventory');ids.add('replenish')}if(/销售|销量|预测|收入|利润|毛利/.test(text))ids.add('forecast');if(/营销|活动|促销|折扣|推广/.test(text))ids.add('strategy');if(/需求|客群/.test(text))ids.add('demand');if(/物流|发货|履约|售后|退货|交付/.test(text))ids.add('fulfillment')}return [...ids]}
export async function prepareFacts(repo:Repository,tenant:string,agents:any[],question:string,filter:SalesFilter={}){if(await ledgerExists(repo,tenant)){const scoped=question+(filter.from?'；查询日期'+filter.from+'至'+(filter.to??filter.from):'')+(filter.productCode?'；商品编码'+filter.productCode:'');const result=await ledgerAnswer(repo,tenant,scoped);const facts:any={};for(const a of agents){const allowed=new Set(a.tools.map((t:string)=>t==='orders'?'sales_orders':t));const required=['inventory','replenish'].includes(a.id)?'inventory':'sales_orders';if(!allowed.has(required)&&!['orchestrator','review','procurement','strategy','demand','fulfillment'].includes(a.id)){facts[a.id]={text:'没有所需业务数据的读取权限，无法分析。',evidence:[]};continue;}const evidence=result.evidence.map(e=>({...e,rows:e.rows.map((r:any)=>Object.fromEntries(Object.entries(r).map(([k,v])=>k.endsWith('_cents')?[k.replace(/_cents$/,'_amount'),typeof v==='number'?(v/100).toFixed(2):v]:[k,v])))}));facts[a.id]={text:result.text,evidence};}return {facts,revision:result.evidence[0]?.databaseRevision??0,source:result.evidence[0]?.source??'synthetic',scope:result.scope,assumptions:{}};}const {db,revision,source}=await openBusiness(repo,tenant);try{const facts:any={},allProducts=query(db,'SELECT id,name,source_code,unit FROM products'),matches=allProducts.filter(p=>question.includes(p.name)||question.includes(p.id)||(p.source_code&&question.includes(p.source_code))),selected=matches.find(p=>p.unit&&question.includes(p.unit))??matches[0];if(matches.length>1&&!matches.some(p=>p.unit&&question.includes(p.unit)))throw Error('匹配到多个商品或计量单位，请提供完整商品编码和单位');const dayMatch=[...question.matchAll(/(\d{1,2})\s*天/g)].at(-1),upMatch=[...question.matchAll(/(?:增长|增幅|提升)\s*(\d{1,3})\s*%/g)].at(-1),days=dayMatch?Math.min(60,Math.max(1,Number(dayMatch[1]))):7,uplift=upMatch?Math.min(300,Number(upMatch[1])):40;
 for(const a of agents){const evidence:any[]=[],allowed=new Set((a.tools as string[]).map(t=>t==='orders'?'sales_orders':t));const read=(sql:string,needed:string[],args:any[]=[])=>{if(needed.some(t=>!allowed.has(t))){evidence.push({sql:'未执行：缺少数据权限',tables:needed,rowCount:0});return []}if(selected&&sql.includes('product_id')){sql='SELECT * FROM ('+sql+') scoped WHERE product_id=?';args=[...args,selected.id]}const rows=query(db,sql,args);evidence.push({sql,args,tables:needed,rowCount:rows.length,rows:rows.slice(0,30)});return rows};let text='';
 if(a.id==='orchestrator')text=`已识别经营咨询，分配 ${agents.filter(x=>!['orchestrator','review'].includes(x.id)).map(x=>x.name).join('、')}，最后交给回顾与输出。${selected?'分析商品：'+selected.name:'未指定商品，按企业整体数据分析。'}`;
 if(a.id==='procurement'){const rows=read('SELECT p.id,p.product_id,s.name supplier,s.lead_days,s.on_time_percent,p.quantity,p.due_date,p.unit_cost_cents FROM purchase_orders p JOIN suppliers s ON s.id=p.supplier_id WHERE p.status=?',['purchase_orders','suppliers'],['pending']);text=rows.length?`待到货采购 ${rows.length} 单，共 ${rows.reduce((n,r)=>n+Number(r.quantity),0)} 件。到货日期为记录值，执行前需向供应商核实。`:'没有可读取的待到货采购记录，无法判断供应能力。'}
 if(a.id==='forecast'){const analysis=salesAnalysis(db,allowed,question,filter,selected?.id);text=analysis.text;evidence.push(...analysis.evidence);}
 if(a.id==='inventory'){const rows=read('SELECT product_id,stock,safety_stock,as_of FROM inventory',['inventory']);text=rows.length?`${rows.map(r=>`${r.product_id}：库存 ${r.stock} 件，安全库存 ${r.safety_stock} 件，截止 ${r.as_of}`).join('；')}。共 ${rows.filter(r=>Number(r.stock)<Number(r.safety_stock)).length} 个低于安全库存。`:'库存记录为空，需先补充库存和截止日期。'}
 if(a.id==='replenish'){const rows=read('SELECT i.product_id,i.stock,i.safety_stock,i.as_of,AVG(s.daily) average FROM inventory i JOIN (SELECT product_id,date,SUM(quantity) daily FROM sales_orders GROUP BY product_id,date) s ON s.product_id=i.product_id GROUP BY i.product_id',['inventory','sales_orders']);const selectedRows=selected?rows.filter(r=>r.product_id===selected.id):rows;const calculated=selectedRows.map(r=>{const forecast=Math.ceil(Number(r.average)*days*(1+uplift/100)),gap=Math.max(0,Number(r.safety_stock)-Number(r.stock)+forecast);return {product:r.product_id,forecast,gap,suggested:Math.ceil(gap*(1+a.bufferPercent/100)/a.packSize)*a.packSize}});evidence.push({tables:[],sql:'程序计算：ceil(日均销量 × 天数 × (1+增幅))；按包装批量上取整补货',rowCount:calculated.length,rows:calculated});text=calculated.length?`情景假设：${days} 天、需求增长 ${uplift}%。${calculated.map(r=>`${r.product} 预计销售 ${r.forecast} 件，建议补货 ${r.suggested} 件`).join('；')}。历史销量未剔除促销影响，仅作情景估计。`:'缺少相同商品的销售与库存记录，暂不能计算补货。'}
 if(a.id==='demand'||a.id==='strategy'){const rows=read('SELECT c.name,c.product_id,c.discount_percent,c.budget_cents,c.start_date,c.end_date,p.price_cents,p.cost_cents FROM campaigns c JOIN products p ON p.id=c.product_id',['campaigns','products']);text=rows.length?rows.map(r=>r.price_cents==null||r.cost_cents==null?`${r.name}：缺少商品售价或进货成本，无法计算活动毛利`:`${r.name}：折扣 ${r.discount_percent}%，按标价折扣后单件毛利 ¥${((Number(r.price_cents)*(1-Number(r.discount_percent)/100)-Number(r.cost_cents))/100).toFixed(2)}，活动预算 ¥${(Number(r.budget_cents)/100).toFixed(2)}`).join('；')+'。尚无活动归因数据，不能计算真实增量 ROI；推广前须核对库存与供货。':'没有可关联商品成本的营销记录，不能判断折扣后的毛利。'}
 if(a.id==='fulfillment'){const deliveries=read('SELECT id,order_id,promised_date,delivered_date,status FROM deliveries WHERE status=?',['deliveries'],['delayed']),returns=read('SELECT id,order_id,quantity,reason,status FROM returns WHERE status=?',['returns'],['pending']);text=`可读取记录中有 ${deliveries.length} 条延迟交付、${returns.length} 条待处理售后。请逐单核实原因和处理时限；记录为空不代表没有风险。`}
 if(a.id==='review')text='汇总各环节证据、数据缺口与行动建议；不自动执行采购、调价或投放。';
 facts[a.id]={text,evidence};}
 return {facts,revision,source,scope:selected?.name??'企业整体',assumptions:{days,uplift}};
 }finally{db.close()}}
