import {test} from 'node:test';import assert from 'node:assert/strict';
import {caseFacts} from './case-agent.ts';import {parameters,queryOptions} from './case-language.ts';import {newCaseRun,stepCaseRun,questionScope,candidates} from './case-workflow.ts';import {procurementEvidence,rankingEvidence} from './case-evidence.ts';import type {Repository} from './api.ts';
const scope={from:'2026-09-01',to:'2026-09-30'},sku='102900011031100';
function memory():Repository{const rows=new Map();return {async get(k){return structuredClone(rows.get(k)??null)},async list(p){return [...rows.keys()].filter(k=>k.startsWith(p))},async put(k,v,ver){if((rows.get(k)?.version??null)!==ver)return false;rows.set(k,{value:structuredClone(v),version:String(Number(ver??0)+1)});return true}}}
async function run(q:string){const repo=memory(),r=await newCaseRun(repo,q,scope);for(let i=0;i<3&&r.status==='running';i++)await stepCaseRun(repo,'test-secret',r);return r}
test('Chinese days, growth signs, adjusted targets, budgets and dates preserve user constraints',()=>{assert.equal(parameters('二十一天').days,21);assert.equal(parameters('十二天').days,12);assert.equal(parameters('增长三成').uplift,30);assert.equal(parameters('下降20%').uplift,-20);assert.equal(parameters('增长-20%').uplift,-20);assert.equal(parameters('增幅由30%调整为10%').uplift,10);assert.equal(parameters('预算五百元').budget_scaled,5000000);assert.throws(()=>parameters('1.5天'));assert.deepEqual(questionScope('九月五日至十五日销售',scope),{from:'2026-09-05',to:'2026-09-15'});assert.deepEqual(questionScope('昨天销售多少',scope),{from:'2026-09-29',to:'2026-09-29'});assert.deepEqual(questionScope('上周卖了多少',scope),{from:'2026-09-21',to:'2026-09-27'})});
test('domestic rows preserve source evidence, native currency, fractional quantities and balanced stock losses',()=>{const c=caseFacts();assert.equal(c.products.length,79);assert.equal(c.sales.length,24040);assert.equal(c.source.original_period,'2022-09');assert.equal(c.source.original_currency,'CNY');assert.equal(c.source.conversion_rate,1);assert.equal(c.income.revenue_scaled,1121405012);assert.equal(c.income.cost_scaled,694985084);assert.equal(c.income.net_profit_scaled,55361401);assert(c.sales.every((r:any[])=>c.salesMeta[String(r[0])].original_date.startsWith('2022-09-')&&r[5].startsWith('2026-09-')));assert.equal(c.sales.filter((r:any[])=>r[4]<0).length,22);assert(c.flow.every(f=>Math.abs(f.quantity_before+f.quantity_change-f.quantity_after)<1e-8&&f.quantity_after>=0));assert(c.checks.every(t=>t.difference===0));assert(c.wholesale.rows.length>0);assert(c.products.every(p=>p.wholesale_refs.length>0));assert.equal(c.aftersales.length,22)});
test('selected procurement sums only matching lines and metric-aware ranking follows the requested direction/count',()=>{const c=caseFacts(),r=procurementEvidence(c,[sku]),expected=c.purchases.flatMap((p:any)=>p.lines).filter((l:any)=>l.product_id===sku).reduce((n:number,l:any)=>n+l.amount_scaled,0);assert.equal(r.data.total_scaled,expected);assert(r.data.orders.every((p:any)=>p.lines.every((l:any)=>l.product_id===sku)));assert(r.data.orders.some((p:any)=>p.orderAmount_scaled>p.selectedAmount_scaled));const rank=rankingEvidence(c.products,queryOptions('销量最高的五种菜'));assert.equal(rank.data.rows.length,5);assert.equal(rank.data.rows[0].id,[...c.products].sort((a,b)=>b.sold-a.sold)[0].id);const low=rankingEvidence(c.products,queryOptions('毛利最低的三种菜'));assert.equal(low.data.rows.length,3);assert.equal(low.data.rows[0].gross_profit_scaled,Math.min(...c.products.map(p=>p.gross_profit_scaled)))});
test('budget is enforced across products and daily arrivals; prices and greetings respond without invented facts',async()=>{const r=await run('全店备货七天，预算五百元');assert.equal(r.status,'completed');assert(r.allocation.totalAllocated_scaled<=5000000);assert(r.allocation.limitedCount>0);assert.equal(r.allocation.totalProducts,79);for(const f of r.allocation.rows){assert.equal(f.stock,caseFacts().products.find(p=>p.id===f.productId)!.stock);assert.equal(f.suggested,f.dailyPlan.reduce((n:number,d:any)=>n+d.suggested,0));assert.equal(f.budget_scaled,f.dailyPlan.reduce((n:number,d:any)=>n+d.budget_scaled,0))}const price=await run('小米椒多少钱一千克');assert.match(price.answer,/最近一次销售单价/);assert.equal(price.plan.productIds[0],sku);const hi=await run('你好');assert.match(hi.answer,/智链销经营助手/);assert.equal(hi.trace.length,1);assert.equal(hi.usage,undefined);assert(candidates(caseFacts(),'生菜备货').length>1)});

