import {test} from 'node:test';import assert from 'node:assert/strict';
import type {Repository} from './api.ts';import {createAPI,passwordHash} from './api.ts';
import {newRun,executeStep} from './engine.ts';import {saveModel,callModel,modelSettings} from './model.ts';import {releaseInfo,publishAgents} from './releases.ts';
function memory():Repository{const rows=new Map<string,any>();return {async get(k){return rows.has(k)?structuredClone(rows.get(k)):null},async put(k,v,version){const old=rows.get(k);if((old?.version??null)!==version)return false;rows.set(k,{value:structuredClone(v),version:String(Number(old?.version??0)+1)});return true},async list(p){return [...rows.keys()].filter(k=>k.startsWith(p))}}}
const secret='test-not-a-real-secret-'.repeat(3);
async function run(repo:Repository,question:string,old?:any,mock?:typeof fetch){const chat=old??{tenant:'demo',messages:[]};chat.messages.push({role:'user',content:question});chat.run=await newRun(repo,chat,question);for(let i=0;i<14&&chat.run.status==='running';i++){const n=chat.run.steps.findIndex((s:any)=>s.status==='pending');assert(n>=0);await executeStep(repo,secret,chat,n,mock)}return chat}
test('greeting and narrow questions never fan out; contextual new conditions override old',async()=>{const repo=memory();let c=await run(repo,'你好');assert.equal(c.run.steps.length,1);c=await run(repo,'轻醒无糖茶库存有多少？',c);assert.deepEqual(c.run.steps.map((s:any)=>s.id),['orchestrator','inventory','review']);assert.equal(c.run.steps[1].evidence[0].rows.length,1);assert(c.messages.at(-1).content.includes('库存'));c=await run(repo,'轻醒无糖茶备货 7 天增长 40%');const first=c.run.steps.find((s:any)=>s.id==='replenish').output;c=await run(repo,'那只做 3 天呢？',c);assert(c.run.steps.find((s:any)=>s.id==='replenish').output.includes('3 天'));assert.notEqual(c.run.steps.find((s:any)=>s.id==='replenish').output,first);const unknown=await run(repo,'帮我处理那个事情');assert.equal(unknown.run.steps.length,1);assert.equal(unknown.run.routeMode,'clarify')});
test('real model dispatch contract, evidence and history reach model; malformed plans fail explicitly',async()=>{const repo=memory();await saveModel(repo,secret,{provider:'Groq',model:'test/model',apiKey:'fake-groq-key',enabled:true,guestEnabled:true,guestDailyLimit:20,revision:0,dailyLimit:30});let n=0;const mock:typeof fetch=async(url,opts)=>{assert.equal(String(url),'https://api.groq.com/openai/v1/chat/completions');const b=JSON.parse(opts!.body as string);assert.equal(b.model,'test/model');const input=JSON.parse(b.messages[1].content);n++;let content='';if(n===1){assert.equal(input.question,'无糖茶库存？');content=JSON.stringify({mode:'delegate',answer:'',reason:'只查库存',tasks:[{agent:'inventory',question:'轻醒无糖茶库存多少',reason:'库存查询'}]})}else if(n===2){assert.equal(input.evidence[0].rows.length,1);content=JSON.stringify({answer:'库存已查询 [inventory-1]',requests:[]})}else{assert(input.results[0].evidence.length);content='模拟库存结果 [inventory-1]'}return Response.json({choices:[{message:{content},finish_reason:'stop'}],usage:{total_tokens:50}})};const c=await run(repo,'无糖茶库存？',{tenant:'demo',messages:[],preview:true},mock);assert.equal(c.run.status,'completed');assert.equal(n,3);assert.equal(c.run.steps.length,3);assert(c.messages.at(-1).content.includes('模拟'));const bad:typeof fetch=async()=>Response.json({choices:[{message:{content:'{"mode":"delegate","answer":"","reason":"x","tasks":[{"agent":"secret-sql","question":"x","reason":"x"}]}'},finish_reason:'stop'}]});const failed=await run(repo,'查库存',{tenant:'demo',messages:[],preview:true},bad);assert.equal(failed.run.status,'failed');assert.equal(failed.run.steps.length,1);assert(failed.messages.at(-1).content.includes('未授权'))});
test('provider switch never reuses a key; free quota enforced; guest disabled by default',async()=>{const repo=memory();await saveModel(repo,secret,{model:'test',apiKey:'fake-openai-key',enabled:true,revision:0,dailyLimit:1});await saveModel(repo,secret,{provider:'Groq',model:'test/model',enabled:false,revision:1,dailyLimit:1});assert.equal((await modelSettings(repo)).hasKey,false);await assert.rejects(saveModel(repo,secret,{provider:'Groq',model:'test/model',enabled:true,revision:2,dailyLimit:1}),/API Key/);assert.equal((await newRun(repo,{tenant:'demo'},'hi')).modelEnabled,false)});
test('draft isolation, admin preview, publish and rollback; history retains previous run',async()=>{const repo=memory(),app=createAPI(repo,{ADMIN_PASSWORD_HASH:passwordHash('test-login'),SESSION_SECRET:secret});let cookie='';async function req(path:string,b?:any,auth=false,key=''){const r=await app(new Request('http://localhost/api/'+path,{method:b?'POST':'GET',headers:{'Content-Type':'application/json',cookie:auth?cookie:'','x-chat-key':key},...(b?{body:JSON.stringify(b)}:{})}),'release-test');return {status:r.status,data:await r.json() as any,cookie:r.headers.get('set-cookie')?.split(';')[0]??''}}
cookie=(await req('login',{password:'test-login'})).cookie;assert.equal((await req('v2/chat/start',{preview:true})).status,401);const agents=(await req('agents',undefined,true)).data.agents,a=agents.find((x:any)=>x.id==='inventory');assert.equal((await req('agents',{...a,name:'新版库存节点'},true)).status,200);let info=await releaseInfo(repo);assert(info.changed);assert.equal(info.current.agents.find((x:any)=>x.id==='inventory').name,a.name);await assert.rejects(publishAgents(repo,info.revision,info.draftHash),/试运行/);
const p=(await req('v2/chat/start',{preview:true},true)).data;await req('v2/chat/send',{id:p.chat.id,message:'库存有多少'},true,p.accessKey);let c:any;for(let i=0;i<3;i++)c=(await req('v2/chat/step',{id:p.chat.id},true,p.accessKey)).data.chat;assert.equal(c.run.status,'completed');assert.equal(c.run.steps[1].name,'新版库存节点');assert.equal((await req('v2/chat/read?id='+p.chat.id,undefined,false,p.accessKey)).status,404);info=await releaseInfo(repo);assert(info.test);await publishAgents(repo,info.revision,info.draftHash);const live=await run(repo,'库存');assert.equal(live.run.steps[1].name,'新版库存节点');info=await releaseInfo(repo);await publishAgents(repo,info.revision,'',1);assert.equal((await run(repo,'库存')).run.steps[1].name,a.name);
await req('v2/chat/send',{id:p.chat.id,message:'你好'},true,p.accessKey);c=(await req('v2/chat/step',{id:p.chat.id},true,p.accessKey)).data.chat;assert.equal(c.history.length,1);assert.equal(c.history[0].steps[1].name,'新版库存节点');assert(!JSON.stringify(c).includes('prompt'));});

test('approval requires enterprise submission and administrator decision; no automatic execution',async()=>{const repo=memory(),app=createAPI(repo,{ADMIN_PASSWORD_HASH:passwordHash('test-login'),SESSION_SECRET:secret});async function q(path:string,b?:any,cookie=''){const r=await app(new Request('http://localhost/api/'+path,{method:b?'POST':'GET',headers:{'Content-Type':'application/json',cookie},...(b?{body:JSON.stringify(b)}:{})}),'approval-test');return {status:r.status,data:await r.json() as any,cookie:r.headers.get('set-cookie')?.split(';')[0]??''}}const admin=(await q('login',{password:'test-login'})).cookie;const a=(await q('v2/companies',{name:'A'},admin)).data,b=(await q('v2/companies',{name:'B'},admin)).data;const ca=(await q('v2/company-login',{id:a.id,accessCode:a.accessCode})).cookie,cb=(await q('v2/company-login',{id:b.id,accessCode:b.accessCode})).cookie;assert.equal((await q('v2/actions',{title:'test',content:'test'})).status,403);const action=(await q('v2/actions',{title:'采购建议',content:'请人工核实后处理'},ca)).data.action;assert.equal((await q('v2/actions',undefined,cb)).data.actions.length,0);assert.equal((await q('v2/actions',{id:action.id,revision:1,status:'approved',note:'同意'},ca)).status,403);assert.equal((await q('v2/actions',{id:action.id,revision:1,status:'approved',note:'核实后由负责人执行'},admin)).status,200);assert.equal((await q('v2/actions',{id:action.id,revision:1,status:'rejected',note:'重复'},admin)).status,409);assert.equal((await q('v2/actions',undefined,ca)).data.actions[0].status,'approved');});

test('Zhipu request contract and incomplete-key rejection',async()=>{const repo=memory();await assert.rejects(saveModel(repo,secret,{provider:'Zhipu',model:'glm-4.7-flash',apiKey:'redacted...key',enabled:true,revision:0,dailyLimit:5}),/省略号/);await saveModel(repo,secret,{provider:'Zhipu',model:'glm-4.7-flash',apiKey:'test-id.test-secret',enabled:true,revision:0,dailyLimit:5});const mock:typeof fetch=async(url,opts)=>{assert.equal(String(url),'https://open.bigmodel.cn/api/paas/v4/chat/completions');assert.equal((opts!.headers as any).Authorization,'Bearer test-id.test-secret');const b=JSON.parse(opts!.body as string);assert.equal(b.max_tokens,2400);assert.equal(b.max_completion_tokens,undefined);assert.equal(b.model,'glm-4.7-flash');return Response.json({choices:[{message:{content:'连接成功'},finish_reason:'stop'}]})};assert.equal((await callModel(repo,secret,'test','hello',mock)).text,'连接成功');assert.equal((await modelSettings(repo)).provider,'Zhipu');});

// A live ledger uses the model for interpretation, never for financial arithmetic.
test('model interprets ledger questions while authoritative figures survive fabricated numbers and outages',async()=>{const repo=memory();await saveModel(repo,secret,{provider:'Ark',model:'test-model',apiKey:'fake-ark-key',enabled:true,guestEnabled:true,guestDailyLimit:30,revision:0,dailyLimit:30});let n=0;const mock:typeof fetch=async()=>{n++;return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(n===1?{query:'2026年9月全店现金和利润为什么不同'}:{comment:'利润已经达到999999元，马上采购！'})}]}]});};let c=await run(repo,'九月的钱和盈利怎么差这么多？',undefined,mock);assert.equal(c.run.status,'completed');assert.equal(n,2);assert(c.messages.at(-1).content.includes('经营净利润-5802.80元'));assert(!c.messages.at(-1).content.includes('999999'));assert.equal(c.ledgerQuery.intent,'finance');const broken:typeof fetch=async()=>{throw Error('simulated outage')};c=await run(repo,'2026年9月矿泉水买卖数量',c,broken);assert.equal(c.run.status,'completed');assert(c.messages.at(-1).content.includes('买入120瓶'));assert(c.messages.at(-1).content.includes('卖出35瓶'));assert(c.run.steps.some((s:any)=>s.mode==='离线查询回退'));});
