import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ledgerView,ledgerWrite} from './ledger.ts';
import type {Repository} from './api.ts';
test('procurement approval and partial receipts do not count plans as existing stock',async()=>{const r=memory();await ledgerWrite(r,'plan',{revision:0,product:{id:'T',name:'茶',unit:'瓶',price_cents:600}},'product');await ledgerWrite(r,'plan',{revision:1,key:'funding01',date:'2026-09-01',type:'capital',amount_cents:10000,cash_cents:10000});const plan=await ledgerWrite(r,'plan',{revision:2,key:'plan-key1',partner:'模拟供应商',due_date:'2026-09-05',lines:[{product_id:'T',quantity:10,unit_price_cents:200}]},'plan');let v=await ledgerView(r,'plan');assert.equal(v.products[0].stock,0);assert.equal(v.balance.payable,0);assert.equal(v.plans[0].status,'draft');const receipt={revision:3,plan_id:plan.id,key:'receive01',date:'2026-09-05',lines:[{product_id:'T',quantity:4,unit_price_cents:200}],cash_cents:0};await assert.rejects(ledgerWrite(r,'plan',receipt,'receive'),/尚未批准/);await ledgerWrite(r,'plan',{revision:3,id:plan.id,status:'approved'},'approve');await ledgerWrite(r,'plan',{...receipt,revision:4},'receive');assert((await ledgerWrite(r,'plan',{...receipt,revision:4},'receive')).duplicate);v=await ledgerView(r,'plan');assert.equal(v.products[0].stock,4);assert.equal(v.balance.payable,-800);assert.equal(v.plans[0].status,'partial');assert.equal(v.plans[0].lines[0].received,4);await assert.rejects(ledgerWrite(r,'plan',{...receipt,revision:5,key:'receive02',lines:[{product_id:'T',quantity:7,unit_price_cents:200}]},'receive'),/剩余数量/);await ledgerWrite(r,'plan',{...receipt,revision:5,key:'receive03',lines:[{product_id:'T',quantity:6,unit_price_cents:200}]},'receive');v=await ledgerView(r,'plan');assert.equal(v.products[0].stock,10);assert.equal(v.plans[0].status,'received');assert.equal(v.plans[0].lines[0].received,10);assert(v.checks.every(c=>c.ok));});
function memory():Repository{const rows=new Map<string,any>();return {async get(k){return rows.has(k)?structuredClone(rows.get(k)):null},async put(k,v,version){const old=rows.get(k);if((old?.version??null)!==version)return false;rows.set(k,{value:structuredClone(v),version:String(Number(old?.version??0)+1)});return true},async list(p){return [...rows.keys()].filter(k=>k.startsWith(p));}};}
test('61-day demonstration: every statement reconciles, named goods and evidence persist',async()=>{const r=memory(),v=await ledgerView(r,'demo');assert.equal(v.products.length,12);assert(v.documents.length>60);assert(v.products.every(p=>p.name&&!p.name.includes('商品编码')));assert(v.checks.every(c=>c.ok),JSON.stringify(v.checks));const ids=v.documents.map(d=>d.id);assert.deepEqual((await ledgerView(r,'demo')).documents.map(d=>d.id),ids);for(const [from,to] of [['2026-08-01','2026-08-31'],['2026-09-01','2026-09-30'],['2026-09-20','2026-09-22'],['2026-07-01','2026-07-31']]){const f=await ledgerView(r,'demo',from,to);assert(f.checks.every(c=>c.ok),JSON.stringify(f.checks));assert.equal(f.income.revenue_cents,f.products.reduce((n,p)=>n+p.revenue_cents,0));assert.equal(f.income.gross_profit_cents,f.products.reduce((n,p)=>n+p.profit_cents,0));}await assert.rejects(ledgerWrite(r,'demo',{revision:1},'seed'),/只读/);});
test('purchase, weighted cost, credit sale, partial return, settlement, expense and closing statements',async()=>{const repo=memory();let revision=0;const add=async(input:any)=>{const result=await ledgerWrite(repo,'shop',{revision,...input});revision=result.revision;return result.id;};await ledgerWrite(repo,'shop',{revision,product:{id:'A',name:'茶',unit:'瓶',price_cents:600}},'product');revision++;
 await add({key:'capital-1',date:'2026-09-01',type:'capital',amount_cents:100000,cash_cents:100000});
 const buy=await add({key:'purchase-1',date:'2026-09-01',type:'purchase',lines:[{product_id:'A',quantity:10,unit_price_cents:200}],cash_cents:1000});
 await add({key:'purchase-2',date:'2026-09-02',type:'purchase',lines:[{product_id:'A',quantity:10,unit_price_cents:400}],cash_cents:4000});
 const sell=await add({key:'sale-key1',date:'2026-09-03',type:'sale',lines:[{product_id:'A',quantity:5,unit_price_cents:600}],cash_cents:1200});
 let v=await ledgerView(repo,'shop');assert.equal(v.products[0].stock,15);assert.equal(v.products[0].stock_value_cents,4500);assert.equal(v.income.gross_profit_cents,1500);assert.equal(v.balance.receivable,1800);
 await add({key:'return-01',date:'2026-09-04',type:'sale_return',reference:sell,lines:[{product_id:'A',quantity:2,unit_price_cents:600}],cash_cents:600});
 await add({key:'collect01',date:'2026-09-05',type:'customer_payment',reference:sell,amount_cents:1200,cash_cents:1200});
 await add({key:'pay-vend1',date:'2026-09-05',type:'supplier_payment',reference:buy,amount_cents:1000,cash_cents:1000});
 await add({key:'expense01',date:'2026-09-06',type:'expense',amount_cents:200,cash_cents:200});v=await ledgerView(repo,'shop');assert.equal(v.products[0].stock,17);assert.equal(v.products[0].stock_value_cents,5100);assert.equal(v.products[0].bought,20);assert.equal(v.products[0].sold,5);assert.equal(v.products[0].returned,2);assert.equal(v.income.revenue_cents,1800);assert.equal(v.income.cost_cents,900);assert.equal(v.income.net_profit_cents,700);assert.equal(v.balance.receivable,0);assert.equal(v.balance.payable,0);assert(v.checks.every(c=>c.ok));
 const before=JSON.stringify(v);for(const b of [{key:'over-sell',type:'sale',lines:[{product_id:'A',quantity:18,unit_price_cents:600}],cash_cents:10800},{key:'over-back',type:'sale_return',reference:sell,lines:[{product_id:'A',quantity:4,unit_price_cents:600}],cash_cents:2400},{key:'wrong-ref',type:'customer_payment',reference:buy,amount_cents:100,cash_cents:100},{key:'over-pay1',type:'customer_payment',reference:sell,amount_cents:100,cash_cents:100},{key:'negative1',type:'expense',amount_cents:-1,cash_cents:-1},{key:'past-date',type:'expense',amount_cents:10,cash_cents:10,date:'2026-08-01'}]){await assert.rejects(ledgerWrite(repo,'shop',{revision,date:'2026-09-06',...b}));assert.equal(JSON.stringify(await ledgerView(repo,'shop')),before);}
});
test('idempotency, optimistic concurrency and full-return rounding restore inventory exactly',async()=>{const repo=memory();await ledgerWrite(repo,'round',{revision:0,product:{id:'A',name:'饼干',unit:'袋',price_cents:200}},'product');await ledgerWrite(repo,'round',{revision:1,key:'funding01',date:'2026-09-01',type:'capital',amount_cents:10000,cash_cents:10000});const purchase={revision:2,key:'buy-key01',date:'2026-09-01',type:'purchase',lines:[{product_id:'A',quantity:3,unit_price_cents:101}],cash_cents:303};const first=await ledgerWrite(repo,'round',purchase);assert((await ledgerWrite(repo,'round',purchase)).duplicate);await assert.rejects(ledgerWrite(repo,'round',{...purchase,cash_cents:200}),/提交编号/);await assert.rejects(ledgerWrite(repo,'round',{...purchase,key:'buy-key02'}),/更新/);
 const sale=await ledgerWrite(repo,'round',{revision:3,key:'sale-key1',date:'2026-09-02',type:'sale',lines:[{product_id:'A',quantity:3,unit_price_cents:200}],cash_cents:600});for(let i=0;i<3;i++)await ledgerWrite(repo,'round',{revision:4+i,key:'return-'+i,date:'2026-09-03',type:'sale_return',reference:sale.id,lines:[{product_id:'A',quantity:1,unit_price_cents:200}],cash_cents:200});const v=await ledgerView(repo,'round');assert.equal(v.products[0].stock,3);assert.equal(v.products[0].stock_value_cents,303);assert.equal(v.income.revenue_cents,0);assert.equal(v.income.cost_cents,0);assert(v.checks.every(c=>c.ok));assert.equal((await ledgerView(repo,'other')).documents.length,0);assert(first.id);});
