import {ledgerView} from './ledger.ts';
import type {Repository} from './api.ts';
export const ledgerTables:Record<string,string>={products:'商品',purchases:'采购入库明细',sales:'销售明细',returns:'销售退回明细',inventory:'库存余额',documents:'业务单据',journal:'会计凭证',flow:'全流程流水',plans:'采购计划',suppliers:'供货商',marketing:'营销活动',fulfillment:'履约记录',aftersales:'售后记录'};
export function inspectLedger(v:any,table='products',offset=0,limit=500){
 const items=v.documents.flatMap((d:any)=>d.lines.map((l:any)=>({id:l.id,document_id:d.id,date:d.date,type:d.type,product_id:l.product_id,name:l.name,unit:l.unit,quantity:l.quantity,unit_price_cents:l.unit_price_cents,amount_cents:l.amount_cents,cost_cents:l.cost_cents,partner:d.partner,reference:d.reference,source:d.provenance?.kind??v.source,original_number:d.provenance?.original_number??'',source_file:d.provenance?.source_file??'',source_row:d.provenance?.source_row??null})));
 const rows:Record<string,any[]>={products:v.products,purchases:items.filter((l:any)=>l.type==='purchase'),sales:items.filter((l:any)=>l.type==='sale'),returns:items.filter((l:any)=>l.type==='sale_return'),inventory:v.products.map((p:any)=>({product_id:p.id,name:p.name,unit:p.unit,stock:p.stock,stock_value_cents:p.stock_value_cents,safety_stock:p.safety_stock,as_of:v.to||v.cutoff})),documents:v.documents.map(({lines,journal,...d}:any)=>d),journal:v.documents.flatMap((d:any)=>d.journal.map((j:any)=>({...j,date:d.date,original_number:d.provenance?.original_number??''}))),flow:v.flow,plans:v.plans,suppliers:[...v.suppliers,...v.operations.filter((r:any)=>r.kind==='suppliers')],marketing:v.operations.filter((r:any)=>r.kind==='marketing'),fulfillment:v.operations.filter((r:any)=>r.kind==='fulfillment'),aftersales:v.operations.filter((r:any)=>r.kind==='aftersales')};
 const name=({purchase_orders:'purchases',sales_orders:'sales'} as Record<string,string>)[table]??table;if(!ledgerTables[name])throw Error('请选择经营账套中的数据表');const all=rows[name]??[];
 return {tenant:v.tenant,source:v.source,currency:v.currency??'CNY',revision:v.revision,from:v.from,to:v.to,counts:Object.fromEntries(Object.entries(rows).map(([k,r])=>[k,r.length])),table:name,total:all.length,columns:all.length?Object.keys(all[0]):[],rows:all.slice(offset,offset+limit),income:v.income,checks:v.checks,storage:'ledger/'+v.tenant,scope:'已过账经营单据'};
}
export async function ledgerDatabase(repo:Repository,tenant:string,table:string,from='',to='9999-12-31',offset=0){return inspectLedger(await ledgerView(repo,tenant,from,to),table,offset);}
