// One posted document produces stock movements and balanced journal entries atomically.
// @ts-ignore
import initSqlJs from 'sql.js/dist/sql-asm.js';
import type {Database} from 'sql.js';
import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';
import type {Repository} from './api.ts';
import {query} from './business-db.ts';
const engine=initSqlJs();
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'日期无效');
const cents=z.number().int().min(0).max(100000000);
const provenanceSchema=z.object({kind:z.enum(['manual','import']).default('manual'),original_number:z.string().trim().max(100).default(''),source_file:z.string().trim().max(200).default(''),source_sha256:z.string().regex(/^[a-f0-9]{64}$/).optional(),source_row:z.number().int().min(1).optional()});
const inputSchema=z.object({provenance:provenanceSchema.optional(),key:z.string().min(8).max(100),revision:z.number().int().min(0),date,type:z.enum(['purchase','sale','sale_return','expense','customer_payment','supplier_payment','capital']),partner:z.string().trim().max(100).default(''),note:z.string().trim().max(500).default(''),cash_cents:cents.default(0),amount_cents:cents.optional(),reference:z.string().max(100).optional(),lines:z.array(z.object({product_id:z.string().max(80),quantity:z.number().int().min(1).max(100000),unit_price_cents:cents})).max(50).default([])});
const productSchema=z.object({id:z.string().trim().regex(/^[A-Za-z0-9_-]{1,50}$/),name:z.string().trim().min(1).max(80),unit:z.string().trim().min(1).max(10),specification:z.string().trim().max(80).default(''),category:z.string().trim().max(30).default('未分类'),price_cents:cents,safety_stock:z.number().int().min(0).max(100000).default(10),pack_size:z.number().int().min(1).max(10000).default(1),lead_days:z.number().int().min(0).max(60).default(3)});
const ddl=`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS ledger_products(id TEXT PRIMARY KEY,name TEXT NOT NULL,unit TEXT NOT NULL,specification TEXT NOT NULL,category TEXT NOT NULL,price_cents INTEGER NOT NULL,safety_stock INTEGER NOT NULL,pack_size INTEGER NOT NULL,lead_days INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS documents(id TEXT PRIMARY KEY,request_key TEXT UNIQUE NOT NULL,input_hash TEXT NOT NULL,date TEXT NOT NULL,type TEXT NOT NULL,partner TEXT NOT NULL,note TEXT NOT NULL,amount_cents INTEGER NOT NULL,cash_cents INTEGER NOT NULL,reference TEXT REFERENCES documents(id));
CREATE TABLE IF NOT EXISTS document_lines(id TEXT PRIMARY KEY,document_id TEXT REFERENCES documents(id),product_id TEXT REFERENCES ledger_products(id),quantity INTEGER NOT NULL,unit_price_cents INTEGER NOT NULL,amount_cents INTEGER NOT NULL,cost_cents INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS movements(id TEXT PRIMARY KEY,document_id TEXT REFERENCES documents(id),product_id TEXT REFERENCES ledger_products(id),quantity INTEGER NOT NULL,value_cents INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS journal(id TEXT PRIMARY KEY,document_id TEXT REFERENCES documents(id),account TEXT NOT NULL,debit_cents INTEGER NOT NULL CHECK(debit_cents>=0),credit_cents INTEGER NOT NULL CHECK(credit_cents>=0));
CREATE TABLE IF NOT EXISTS purchase_plans(id TEXT PRIMARY KEY,request_key TEXT UNIQUE NOT NULL,partner TEXT NOT NULL,due_date TEXT NOT NULL,note TEXT NOT NULL,status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS purchase_plan_lines(plan_id TEXT REFERENCES purchase_plans(id),product_id TEXT REFERENCES ledger_products(id),quantity INTEGER NOT NULL,unit_price_cents INTEGER NOT NULL,PRIMARY KEY(plan_id,product_id));
CREATE TABLE IF NOT EXISTS plan_receipts(plan_id TEXT REFERENCES purchase_plans(id),document_id TEXT REFERENCES documents(id),product_id TEXT REFERENCES ledger_products(id),quantity INTEGER NOT NULL,PRIMARY KEY(document_id,product_id));
CREATE TABLE IF NOT EXISTS document_sources(document_id TEXT PRIMARY KEY REFERENCES documents(id),kind TEXT NOT NULL,original_number TEXT NOT NULL,source_file TEXT NOT NULL,source_sha256 TEXT,source_row INTEGER);
CREATE TABLE IF NOT EXISTS operational_records(id TEXT PRIMARY KEY,kind TEXT NOT NULL,date TEXT NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL,document_id TEXT REFERENCES documents(id),original_number TEXT NOT NULL,source_file TEXT NOT NULL,note TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS document_dates ON documents(date);
CREATE INDEX IF NOT EXISTS stock_product ON movements(product_id);
CREATE INDEX IF NOT EXISTS journal_account ON journal(account);`;
export const accountNames:Record<string,string>={cash:'货币资金',receivable:'应收账款',inventory:'库存商品',fixed_assets:'固定资产原值',depreciation:'累计折旧',payable:'应付账款',capital:'投入资本',revenue:'销售收入',cogs:'销售成本',expense:'经营费用'};
function insert(db:Database,table:string,row:Record<string,any>){const cols=Object.keys(row);db.run(`INSERT INTO ${table} (${cols.join(',')}) VALUES (${cols.map(()=>'?').join(',')})`,Object.values(row));}
function stock(db:Database,id:string,asOf='9999-12-31'){return query(db,'SELECT COALESCE(SUM(m.quantity),0) quantity,COALESCE(SUM(m.value_cents),0) value_cents FROM movements m JOIN documents d ON d.id=m.document_id WHERE m.product_id=? AND d.date<=?',[id,asOf])[0];}
function journal(db:Database,id:string,account:string,debit=0,credit=0){if(debit||credit)insert(db,'journal',{id:randomUUID(),document_id:id,account,debit_cents:debit,credit_cents:credit});}
function balance(db:Database,account:string){return Number(query(db,'SELECT COALESCE(SUM(debit_cents-credit_cents),0) n FROM journal WHERE account=?',[account])[0].n);}
function post(db:Database,b:z.infer<typeof inputSchema>){
 const content={...b};delete (content as any).revision;const fingerprint=createHash('sha256').update(JSON.stringify(content)).digest('hex');
 const duplicate=query(db,'SELECT id,input_hash FROM documents WHERE request_key=?',[b.key])[0];if(duplicate){if(duplicate.input_hash!==fingerprint)throw Error('同一提交编号不能用于不同业务');return duplicate.id;}
 const last=query(db,'SELECT MAX(date) date FROM documents')[0].date;if(last&&b.date<last)throw Error('单据日期不能早于最近过账日期；追溯更正需要专门的调整流程');
 if(['purchase','sale','sale_return'].includes(b.type)&&!b.lines.length)throw Error('请选择至少一个商品');
 if(new Set(b.lines.map(l=>l.product_id)).size!==b.lines.length)throw Error('同一单据商品不能重复');
 if(!['purchase','sale','sale_return'].includes(b.type)&&b.lines.length)throw Error('此类单据不接受商品明细');
 const reference=b.reference?query(db,'SELECT * FROM documents WHERE id=?',[b.reference])[0]:null;
 if(['sale_return','customer_payment','supplier_payment'].includes(b.type)&&!reference)throw Error('请选择原始单据');
 if(b.type==='sale_return'&&reference.type!=='sale'||b.type==='customer_payment'&&reference.type!=='sale'||b.type==='supplier_payment'&&reference.type!=='purchase')throw Error('关联单据类型不正确');
 const prepared=b.lines.map(l=>{const p=query(db,'SELECT * FROM ledger_products WHERE id=?',[l.product_id])[0];if(!p)throw Error('商品不存在');const s=stock(db,p.id);let cost=0,amount=l.quantity*l.unit_price_cents;
  if(b.type==='sale'){if(l.quantity>s.quantity)throw Error(p.name+'库存不足，可售 '+s.quantity+p.unit);cost=l.quantity===s.quantity?s.value_cents:Math.round(s.value_cents*l.quantity/s.quantity);}
  if(b.type==='purchase')cost=amount;
  if(b.type==='sale_return'){const original=query(db,'SELECT * FROM document_lines WHERE document_id=? AND product_id=?',[b.reference,p.id])[0];if(!original)throw Error('退货商品不在原销售单中');const returned=query(db,"SELECT COALESCE(SUM(l.quantity),0) quantity,COALESCE(SUM(l.cost_cents),0) cost,COALESCE(SUM(l.amount_cents),0) amount FROM document_lines l JOIN documents d ON d.id=l.document_id WHERE d.type='sale_return' AND d.reference=? AND l.product_id=?",[b.reference,p.id])[0];if(returned.quantity+l.quantity>original.quantity)throw Error('退货数量超过原单剩余可退数量');if(l.unit_price_cents!==original.unit_price_cents)throw Error('退货单价必须与原销售单一致');cost=returned.quantity+l.quantity===original.quantity?original.cost_cents-returned.cost:Math.round(original.cost_cents*l.quantity/original.quantity);amount=returned.quantity+l.quantity===original.quantity?original.amount_cents-returned.amount:l.quantity*original.unit_price_cents;}
  if(!Number.isSafeInteger(amount)||amount>10000000000)throw Error('单据金额超出范围');return {...l,cost_cents:cost,amount_cents:amount};});
 const amount=prepared.length?prepared.reduce((n,l)=>n+l.amount_cents,0):b.amount_cents??0,cost=prepared.reduce((n,l)=>n+l.cost_cents,0);
 if(amount<=0)throw Error('单据金额必须大于零');if(b.cash_cents>amount)throw Error('现金金额不能大于单据金额');
 if(['customer_payment','supplier_payment'].includes(b.type)){const adjustments=query(db,"SELECT COALESCE(SUM(CASE WHEN type='sale_return' THEN amount_cents-cash_cents ELSE amount_cents END),0) n FROM documents WHERE reference=?",[b.reference])[0].n;const outstanding=reference.amount_cents-reference.cash_cents-adjustments;if(amount>outstanding)throw Error('结算金额超过原单未结余额');if(b.cash_cents!==amount)throw Error('结算单现金金额应等于结算金额');}
 if(b.type==='sale_return'){const settled=query(db,"SELECT COALESCE(SUM(CASE WHEN type='customer_payment' THEN amount_cents WHEN type='sale_return' THEN -cash_cents ELSE 0 END),0) n FROM documents WHERE reference=?",[b.reference])[0].n;const availableCash=reference.cash_cents+settled;const priorReturns=query(db,"SELECT COALESCE(SUM(amount_cents-cash_cents),0) n FROM documents WHERE reference=? AND type='sale_return'",[b.reference])[0].n;const receivable=reference.amount_cents-reference.cash_cents-query(db,"SELECT COALESCE(SUM(amount_cents),0) n FROM documents WHERE reference=? AND type='customer_payment'",[b.reference])[0].n-priorReturns;if(b.cash_cents>availableCash||amount-b.cash_cents>receivable)throw Error('退货退款与冲减应收的分配不正确');}
 if(['expense','capital'].includes(b.type)&&b.cash_cents!==amount)throw Error('此类单据按实际现金金额记录');
 const cashOut=['purchase','sale_return','expense','supplier_payment'].includes(b.type)?b.cash_cents:0;if(cashOut>balance(db,'cash'))throw Error('可用资金不足');
 const id=randomUUID();insert(db,'documents',{id,request_key:b.key,input_hash:fingerprint,date:b.date,type:b.type,partner:b.partner,note:b.note,amount_cents:amount,cash_cents:b.cash_cents,reference:b.reference??null});
 insert(db,'document_sources',{document_id:id,kind:b.provenance?.kind??'manual',original_number:b.provenance?.original_number??'',source_file:b.provenance?.source_file??'',source_sha256:b.provenance?.source_sha256??null,source_row:b.provenance?.source_row??null});
 for(const l of prepared){insert(db,'document_lines',{id:randomUUID(),document_id:id,...l});const sign=b.type==='sale'?-1:1;insert(db,'movements',{id:randomUUID(),document_id:id,product_id:l.product_id,quantity:sign*l.quantity,value_cents:sign*l.cost_cents});}
 if(b.type==='purchase'){journal(db,id,'inventory',amount);journal(db,id,'cash',0,b.cash_cents);journal(db,id,'payable',0,amount-b.cash_cents);}
 if(b.type==='sale'){journal(db,id,'cash',b.cash_cents);journal(db,id,'receivable',amount-b.cash_cents);journal(db,id,'revenue',0,amount);journal(db,id,'cogs',cost);journal(db,id,'inventory',0,cost);}
 if(b.type==='sale_return'){journal(db,id,'revenue',amount);journal(db,id,'cash',0,b.cash_cents);journal(db,id,'receivable',0,amount-b.cash_cents);journal(db,id,'inventory',cost);journal(db,id,'cogs',0,cost);}
 if(b.type==='expense'){journal(db,id,'expense',amount);journal(db,id,'cash',0,amount);}
 if(b.type==='capital'){journal(db,id,'cash',amount);journal(db,id,'capital',0,amount);}
 if(b.type==='customer_payment'){journal(db,id,'cash',amount);journal(db,id,'receivable',0,amount);}
 if(b.type==='supplier_payment'){journal(db,id,'payable',amount);journal(db,id,'cash',0,amount);}
 const j=query(db,'SELECT SUM(debit_cents) debit,SUM(credit_cents) credit FROM journal WHERE document_id=?',[id])[0];if(j.debit!==j.credit)throw Error('凭证借贷不平衡');return id;
}
const goods=[['T001','轻醒无糖茶','瓶','500ml','饮品',600,280,24],['W001','矿泉水','瓶','550ml','饮品',200,85,24],['C001','冰咖啡','瓶','270ml','饮品',800,420,12],['M001','纯牛奶','盒','250ml','乳品',350,225,24],['Y001','原味酸奶','杯','200g','乳品',600,380,12],['B001','全麦面包','袋','400g','烘焙',1200,750,6],['N001','红烧牛肉面','桶','110g','食品',500,310,12],['R001','东北大米','袋','5kg','粮油',3800,2700,5],['O001','葵花籽油','桶','1.8L','粮油',3200,2350,6],['S001','海盐薯片','袋','70g','零食',650,390,12],['P001','抽纸','包','100抽','日用',450,260,10],['D001','洗衣液','瓶','1kg','日用',1800,1180,6]] as const;
function seed(db:Database){
 for(const g of goods)insert(db,'ledger_products',productSchema.parse({id:g[0],name:g[1],unit:g[2],specification:g[3],category:g[4],price_cents:g[5],safety_stock:30,pack_size:g[7],lead_days:3}));
 post(db,inputSchema.parse({key:'seed-capital-1',revision:0,date:'2026-08-01',type:'capital',partner:'模拟门店股东',note:'演示初始投入',amount_cents:5000000,cash_cents:5000000}));
 post(db,inputSchema.parse({key:'seed-purchase-1',revision:0,date:'2026-08-01',type:'purchase',partner:'青禾商贸（模拟）',note:'首批入库',lines:goods.map(g=>({product_id:g[0],quantity:g[0]==='T001'?60:150,unit_price_cents:g[6]})),cash_cents:goods.reduce((n,g)=>n+g[6]*(g[0]==='T001'?60:150),0)}));
 let refundReference='';
 for(let month=8;month<=9;month++)for(let day=1;day<=(month===8?31:30);day++){
  const d=`2026-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
  if(day===1&&month===9)post(db,inputSchema.parse({key:'seed-purchase-2',revision:0,date:d,type:'purchase',partner:'青禾商贸（模拟）',note:'补货入库，部分赊购',lines:goods.map(g=>({product_id:g[0],quantity:g[0]==='T001'?20:120,unit_price_cents:g[6]+10})),cash_cents:300000}));
  const lines=goods.filter((_,i)=>(i+day)%3===0).map((g,i)=>({product_id:g[0],quantity:2+(day+i)%4,unit_price_cents:g[5]}));const amount=lines.reduce((n,l)=>n+l.quantity*l.unit_price_cents,0);
  const id=post(db,inputSchema.parse({key:`seed-sale-${month}-${day}`,revision:0,date:d,type:'sale',partner:day%7===0?'企业客户（模拟）':'门店零售（模拟）',lines,cash_cents:day%7===0?Math.floor(amount/2):amount,note:day%7===0?'部分赊销':'现款销售'}));
  if(month===9&&day===20)refundReference=id;
  if(month===9&&day===22){const line=query(db,'SELECT * FROM document_lines WHERE document_id=? LIMIT 1',[refundReference])[0];post(db,inputSchema.parse({key:'seed-return-1',revision:0,date:d,type:'sale_return',reference:refundReference,partner:'门店零售（模拟）',note:'包装破损退货',lines:[{product_id:line.product_id,quantity:1,unit_price_cents:line.unit_price_cents}],cash_cents:line.unit_price_cents}));}
  if(day===28)for(const [name,money] of [['房租',240000],['工资',480000],['水电',28000]] as const)post(db,inputSchema.parse({key:`seed-expense-${month}-${name}`,revision:0,date:d,type:'expense',partner:name,note:name,amount_cents:money,cash_cents:money}));
 }
}
async function open(repo:Repository,tenant:string){if(!/^[a-zA-Z0-9_-]{1,64}$/.test(tenant))throw Error('企业编号无效');let saved=await repo.get('ledger/'+tenant);const SQL=await engine;let db:Database=new SQL.Database(saved?Buffer.from(saved.value.sqlite,'base64'):undefined);db.run(ddl);if(tenant==='demo'&&(!saved||saved.value.seedVersion!==2)){db.close();db=new SQL.Database();db.run(ddl);seed(db);db.run("UPDATE document_sources SET kind='synthetic'");await repo.put('ledger/demo',{sqlite:Buffer.from(db.export()).toString('base64'),revision:(saved?.value.revision??0)+1,seedVersion:2,source:'synthetic',updatedAt:new Date().toISOString()},saved?.version??null);db.close();saved=await repo.get('ledger/demo');db=new SQL.Database(Buffer.from(saved!.value.sqlite,'base64'));db.run(ddl);}return {db,saved,revision:saved?.value.revision??0,source:saved?.value.source??(tenant==='demo'?'synthetic':'empty')};}
export async function ledgerExists(repo:Repository,tenant:string){return tenant==='demo'||!!await repo.get('ledger/'+tenant);}
export async function ledgerWrite(repo:Repository,tenant:string,input:any,operation='document'){
 if(tenant==='demo')throw Error('公共演示账套只读，请创建自己的企业账套');const {db,saved,revision,source}=await open(repo,tenant);
 try{if(operation==='document'){const b=inputSchema.parse(input),old=query(db,'SELECT id,input_hash FROM documents WHERE request_key=?',[b.key])[0];if(old){post(db,b);return {id:old.id,revision,duplicate:true};}}
  if(operation==='receive'){const p=query(db,'SELECT * FROM purchase_plans WHERE id=?',[input.plan_id])[0];if(p){const b=inputSchema.parse({...input,type:'purchase',partner:p.partner,note:'采购计划 '+p.id+' 收货：'+(input.note??'')}),old=query(db,'SELECT id FROM documents WHERE request_key=?',[b.key])[0];if(old){post(db,b);if(!query(db,'SELECT * FROM plan_receipts WHERE document_id=? AND plan_id=?',[old.id,p.id]).length)throw Error('提交编号已用于其他业务');return {id:old.id,revision,duplicate:true};}}}
  if(input.revision!==revision)throw Error('账套已更新，请刷新后重新提交');db.run('BEGIN');let id='';
  if(operation==='seed'){if(query(db,'SELECT COUNT(*) n FROM documents')[0].n||query(db,'SELECT COUNT(*) n FROM ledger_products')[0].n)throw Error('只能向空账套创建演示数据');seed(db);db.run("UPDATE document_sources SET kind='synthetic'");}
  else if(operation==='record'){const b=z.object({kind:z.enum(['suppliers','marketing','fulfillment','aftersales']),date,name:z.string().trim().min(1).max(100),status:z.string().trim().min(1).max(50),document_id:z.string().nullable().default(null),original_number:z.string().trim().min(1).max(100),source_file:z.string().trim().min(1).max(200),note:z.string().max(1000).default('')}).parse(input);if(['fulfillment','aftersales'].includes(b.kind)){const d=query(db,'SELECT type,date FROM documents WHERE id=?',[b.document_id])[0];if(!d||d.type!=='sale')throw Error('履约和售后必须关联本账套销售原单');if(b.date<d.date)throw Error('业务日期不能早于销售原单');}id=randomUUID();insert(db,'operational_records',{id,...b});}
  else if(operation==='product')insert(db,'ledger_products',productSchema.parse(input.product));
  else if(operation==='plan'){
   const b=z.object({key:z.string().min(8).max(100),partner:z.string().trim().min(1).max(100),due_date:date,note:z.string().max(500).default(''),lines:z.array(z.object({product_id:z.string(),quantity:z.number().int().min(1).max(100000),unit_price_cents:cents})).min(1).max(50)}).parse(input);if(new Set(b.lines.map(l=>l.product_id)).size!==b.lines.length)throw Error('商品不能重复');
   id=randomUUID();insert(db,'purchase_plans',{id,request_key:b.key,partner:b.partner,due_date:b.due_date,note:b.note,status:'draft'});for(const l of b.lines){if(!query(db,'SELECT id FROM ledger_products WHERE id=?',[l.product_id]).length)throw Error('商品不存在');insert(db,'purchase_plan_lines',{plan_id:id,...l});}
  }
  else if(operation==='approve'){
   const b=z.object({id:z.string(),status:z.enum(['approved','rejected'])}).parse(input),p=query(db,'SELECT * FROM purchase_plans WHERE id=?',[b.id])[0];if(!p||p.status!=='draft')throw Error('只有待审批的采购计划可以审核');db.run('UPDATE purchase_plans SET status=? WHERE id=?',[b.status,b.id]);id=b.id;
  }
  else if(operation==='receive'){
   const p=query(db,'SELECT * FROM purchase_plans WHERE id=?',[input.plan_id])[0];if(!p||!['approved','partial'].includes(p.status))throw Error('采购计划尚未批准或已经全部收货');
   const b=inputSchema.parse({...input,type:'purchase',partner:p.partner,note:'采购计划 '+p.id+' 收货：'+(input.note??'')});
   for(const l of b.lines){const plan=query(db,'SELECT *,COALESCE((SELECT SUM(quantity) FROM plan_receipts WHERE plan_id=? AND product_id=?),0) received FROM purchase_plan_lines WHERE plan_id=? AND product_id=?',[p.id,l.product_id,p.id,l.product_id])[0];if(!plan||l.quantity>plan.quantity-plan.received)throw Error('收货数量超过计划剩余数量');if(l.unit_price_cents!==plan.unit_price_cents)throw Error('收货单价与批准的采购计划不一致');}
   id=post(db,b);for(const l of b.lines)insert(db,'plan_receipts',{plan_id:p.id,document_id:id,product_id:l.product_id,quantity:l.quantity});const pending=query(db,'SELECT COALESCE(SUM(l.quantity-COALESCE((SELECT SUM(quantity) FROM plan_receipts WHERE plan_id=l.plan_id AND product_id=l.product_id),0)),0) n FROM purchase_plan_lines l WHERE l.plan_id=?',[p.id])[0].n;db.run('UPDATE purchase_plans SET status=? WHERE id=?',[pending?'partial':'received',p.id]);
  }
  else id=post(db,inputSchema.parse(input));
  db.run('COMMIT');const bytes=db.export();if(bytes.length>16*1024*1024)throw Error('账套超过16MB');
  if(!await repo.put('ledger/'+tenant,{sqlite:Buffer.from(bytes).toString('base64'),revision:revision+1,source:operation==='seed'?'synthetic':source==='empty'?'provided':source,updatedAt:new Date().toISOString()},saved?.version??null))throw Error('账套写入冲突，请刷新后重试');return {id,revision:revision+1};
 }finally{db.close();}
}
export async function ledgerView(repo:Repository,tenant:string,from='',to='9999-12-31'){
 if(from)date.parse(from);if(to!=='9999-12-31')date.parse(to);if(from&&from>to)throw Error('开始日期不能晚于结束日期');const {db,revision,source}=await open(repo,tenant);
 try{
  const args=[from,to],period="d.date>=? AND d.date<=?";
  const products=query(db,`SELECT p.*,COALESCE(SUM(CASE WHEN d.date<=? THEN m.quantity ELSE 0 END),0) stock,COALESCE(SUM(CASE WHEN d.date<=? THEN m.value_cents ELSE 0 END),0) stock_value_cents,COALESCE(SUM(CASE WHEN ${period} AND d.type='purchase' THEN m.quantity ELSE 0 END),0) bought,COALESCE(SUM(CASE WHEN ${period} AND d.type='sale' THEN -m.quantity ELSE 0 END),0) sold,COALESCE(SUM(CASE WHEN ${period} AND d.type='sale_return' THEN m.quantity ELSE 0 END),0) returned FROM ledger_products p LEFT JOIN movements m ON m.product_id=p.id LEFT JOIN documents d ON d.id=m.document_id GROUP BY p.id ORDER BY p.id`,[to,to,...args,...args,...args]);
  for(const p of products){const s=query(db,`SELECT COALESCE(SUM(CASE WHEN d.type='sale_return' THEN -l.amount_cents ELSE l.amount_cents END),0) revenue_cents,COALESCE(SUM(CASE WHEN d.type='sale_return' THEN -l.cost_cents ELSE l.cost_cents END),0) cost_cents FROM document_lines l JOIN documents d ON d.id=l.document_id WHERE l.product_id=? AND d.type IN ('sale','sale_return') AND ${period}`,[p.id,...args])[0];Object.assign(p,s,{profit_cents:s.revenue_cents-s.cost_cents,net_sold:p.sold-p.returned,average_cost_cents:p.stock?Math.round(p.stock_value_cents/p.stock):null});p.latest_purchase_cents=query(db,"SELECT l.unit_price_cents FROM document_lines l JOIN documents d ON d.id=l.document_id WHERE l.product_id=? AND d.type='purchase' AND d.date<=? ORDER BY d.date DESC,d.rowid DESC LIMIT 1",[p.id,to])[0]?.unit_price_cents??null;}
  const trial=query(db,'SELECT j.account,SUM(j.debit_cents) debit_cents,SUM(j.credit_cents) credit_cents,SUM(j.debit_cents-j.credit_cents) balance_cents FROM journal j JOIN documents d ON d.id=j.document_id WHERE d.date<=? GROUP BY j.account',[to]);
  const balances:Record<string,number>=Object.fromEntries(Object.keys(accountNames).map(a=>[a,Number(trial.find(r=>r.account===a)?.balance_cents??0)]));
  const pj=query(db,`SELECT j.account,SUM(j.debit_cents-j.credit_cents) balance FROM journal j JOIN documents d ON d.id=j.document_id WHERE ${period} GROUP BY j.account`,args),get=(a:string)=>Number(pj.find(r=>r.account===a)?.balance??0);
  const income={revenue_cents:0-get('revenue'),cost_cents:get('cogs'),expense_cents:get('expense')};const gross=income.revenue_cents-income.cost_cents,profit=gross-income.expense_cents;
  const retained=-balances.revenue-balances.cogs-balances.expense,assets=balances.cash+balances.receivable+balances.inventory+balances.fixed_assets+balances.depreciation,liabilities=-balances.payable,equity=-balances.capital+retained;
  const cashRows=query(db,`SELECT d.type,COALESCE(SUM(j.debit_cents-j.credit_cents),0) cents FROM journal j JOIN documents d ON d.id=j.document_id WHERE j.account='cash' AND ${period} GROUP BY d.type`,args),cash=(type:string)=>Number(cashRows.find(r=>r.type===type)?.cents??0);
  const openingCash=Number(query(db,"SELECT COALESCE(SUM(j.debit_cents-j.credit_cents),0) n FROM journal j JOIN documents d ON d.id=j.document_id WHERE j.account='cash' AND d.date<?",[from])[0].n),operating=cash('sale')+cash('sale_return')+cash('purchase')+cash('expense')+cash('customer_payment')+cash('supplier_payment'),financing=cash('capital');
  const documents=query(db,'SELECT * FROM documents WHERE date>=? AND date<=? ORDER BY date DESC,rowid DESC',args).map(d=>({...d,lines:query(db,'SELECT l.*,p.name,p.unit,p.specification FROM document_lines l JOIN ledger_products p ON p.id=l.product_id WHERE document_id=?',[d.id]),journal:query(db,'SELECT * FROM journal WHERE document_id=?',[d.id]),provenance:query(db,'SELECT * FROM document_sources WHERE document_id=?',[d.id])[0]??{kind:source==='synthetic'?'synthetic':'unverified',original_number:'',source_file:''}}));
  const outstanding=query(db,"SELECT d.id,d.date,d.type,d.partner,d.amount_cents-d.cash_cents-COALESCE((SELECT SUM(CASE WHEN x.type='sale_return' THEN x.amount_cents-x.cash_cents ELSE x.amount_cents END) FROM documents x WHERE x.reference=d.id AND x.date<=?),0) outstanding_cents FROM documents d WHERE d.type IN ('sale','purchase') AND d.date<=?",[to,to]).filter(d=>d.outstanding_cents>0);
  const monthly=query(db,"SELECT substr(d.date,1,7) month,-SUM(CASE WHEN j.account='revenue' THEN j.debit_cents-j.credit_cents ELSE 0 END) revenue_cents,SUM(CASE WHEN j.account='cogs' THEN j.debit_cents-j.credit_cents ELSE 0 END) cost_cents,SUM(CASE WHEN j.account='expense' THEN j.debit_cents-j.credit_cents ELSE 0 END) expense_cents FROM journal j JOIN documents d ON d.id=j.document_id WHERE d.date>=? AND d.date<=? GROUP BY 1 ORDER BY 1",args);
  const allMovements=query(db,'SELECT m.id,m.document_id,d.date,d.type,d.partner,m.product_id,p.name,p.unit,m.quantity,m.value_cents,l.unit_price_cents,l.amount_cents,l.cost_cents,d.cash_cents document_cash_cents FROM movements m JOIN documents d ON d.id=m.document_id JOIN ledger_products p ON p.id=m.product_id JOIN document_lines l ON l.document_id=m.document_id AND l.product_id=m.product_id WHERE d.date<=? ORDER BY d.date,d.rowid,m.rowid',[to]);const running:Record<string,{quantity:number,value:number}>={};const flow=allMovements.map(m=>{const r=running[m.product_id]??{quantity:0,value:0},quantity_before=r.quantity,value_before_cents=r.value;r.quantity+=m.quantity;r.value+=m.value_cents;running[m.product_id]=r;return {...m,quantity_before,value_before_cents,quantity_after:r.quantity,value_after_cents:r.value};}).filter(m=>m.date>=from);
  const plans=query(db,'SELECT * FROM purchase_plans ORDER BY rowid DESC').map(p=>({...p,lines:query(db,'SELECT l.*,p.name,p.unit,COALESCE((SELECT SUM(quantity) FROM plan_receipts WHERE plan_id=l.plan_id AND product_id=l.product_id),0) received FROM purchase_plan_lines l JOIN ledger_products p ON p.id=l.product_id WHERE plan_id=?',[p.id])}));
  const inventoryValue=products.reduce((n,p)=>n+p.stock_value_cents,0),stockEquation=products.every(p=>p.stock>=0&&p.stock_value_cents>=0);
  const unbalanced=query(db,'SELECT document_id FROM journal j JOIN documents d ON d.id=j.document_id WHERE d.date<=? GROUP BY document_id HAVING SUM(debit_cents)<>SUM(credit_cents)',[to]);
  const debit=trial.reduce((n,r)=>n+r.debit_cents,0),credit=trial.reduce((n,r)=>n+r.credit_cents,0),cashChange=cashRows.reduce((n,r)=>n+r.cents,0);
  const bridge={profit_cents:profit,inventory_change_cents:get('inventory'),receivable_change_cents:get('receivable'),payable_change_cents:-get('payable'),operating_cents:profit-get('inventory')-get('receivable')-get('payable')};
  const balanceSheet:Record<string,number>={...balances,assets_cents:assets,liabilities_cents:liabilities,equity_cents:equity,retained_cents:retained};
  const operations=query(db,'SELECT * FROM operational_records WHERE date>=? AND date<=? ORDER BY date,id',[from,to]);const suppliers=query(db,"SELECT partner name,COUNT(*) documents,SUM(amount_cents) purchase_cents FROM documents WHERE type='purchase' AND date>=? AND date<=? GROUP BY partner",[from,to]);
  return {tenant,source,operations,suppliers,currency:'CNY',cutoff:query(db,'SELECT MAX(date) date FROM documents')[0]?.date??'',flow,revision,from,to:to==='9999-12-31'?'':to,products,documents,outstanding,monthly,plans,trial:trial.map(r=>({...r,name:accountNames[r.account]})),income:{...income,gross_profit_cents:gross,net_profit_cents:profit},balance:balanceSheet,bridge,cashflow:{opening_cents:openingCash,operating_cents:operating,financing_cents:financing,investing_cents:0,change_cents:cashChange,closing_cents:balances.cash,rows:cashRows},checks:[{name:'每张凭证借贷平衡',difference:unbalanced.length,ok:!unbalanced.length},{name:'总账借贷平衡',difference:debit-credit,ok:debit===credit},{name:'资产 = 负债 + 权益',difference:assets-liabilities-equity,ok:assets===liabilities+equity},{name:'库存商品账面价值 = 库存流水',difference:balances.inventory-inventoryValue,ok:balances.inventory===inventoryValue},{name:'期初现金 + 净流量 = 期末现金',difference:openingCash+cashChange-balances.cash,ok:openingCash+cashChange===balances.cash},{name:'应收明细 = 总账',difference:outstanding.filter(d=>d.type==='sale').reduce((n,d)=>n+d.outstanding_cents,0)-balances.receivable,ok:outstanding.filter(d=>d.type==='sale').reduce((n,d)=>n+d.outstanding_cents,0)===balances.receivable},{name:'应付明细 = 总账',difference:outstanding.filter(d=>d.type==='purchase').reduce((n,d)=>n+d.outstanding_cents,0)+balances.payable,ok:outstanding.filter(d=>d.type==='purchase').reduce((n,d)=>n+d.outstanding_cents,0)===-balances.payable},{name:'库存数量与金额非负',difference:stockEquation?0:1,ok:stockEquation},{name:'净利润调整后 = 经营现金流',difference:bridge.operating_cents-operating,ok:bridge.operating_cents===operating}],policy:'人民币元；存储为整数分；商品按包装基础单位计量；移动加权平均计价；销售退货冲回原单成本；不含增值税的教学模拟账套，净利润为本账套已记录收支口径，尚未计提所得税。'};
 }finally{db.close();}
}
