import {ledgerView} from './ledger.ts';
import type {Repository} from './api.ts';
const money=(n:number)=>(n/100).toFixed(2)+'元';
export function isLedgerQuestion(q:string){return /商品|茶|水|咖啡|牛奶|酸奶|面包|大米|粮油|销量|销售|卖|买|进货|采购|库存|补货|备货|促销|利润|成本|毛利|财务|现金|应收|应付|经营|风险|费用|收入|价[格钱]|对账|[年月]|\d+天/.test(q);}
function dates(q:string,latest:string,old:any={}){
 let from=old.from??'',to=old.to??'';
 const full=[...q.matchAll(/(20\d{2})[-年/.](\d{1,2})[-月/.](\d{1,2})日?/g)];
 if(full.length){const ds=full.map(m=>`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`);from=ds[0];to=ds.at(-1)!;}
 else{const numeric=q.match(/(?:(20\d{2})年?[-/]?)?(\d{1,2})月/),cn=q.match(/(?:(20\d{2})年)?(十一|十二|十|[一二三四五六七八九])月/);let m=0,y='';if(numeric){m=Number(numeric[2]);y=numeric[1]??'';}else if(cn){m={'一':1,'二':2,'三':3,'四':4,'五':5,'六':6,'七':7,'八':8,'九':9,'十':10,'十一':11,'十二':12}[cn[2]]??0;y=cn[1]??'';}if(m){if(m<1||m>12)throw Error('月份应为1至12月');y=y||from.slice(0,4)||latest.slice(0,4);from=`${y}-${String(m).padStart(2,'0')}-01`;to=new Date(Date.UTC(Number(y),m,0)).toISOString().slice(0,10);}
  else if(/本月|这个月/.test(q)){from=latest.slice(0,7)+'-01';to=latest;}
  else if(/上个月|上月/.test(q)){const d=new Date(latest+'T00:00:00Z');d.setUTCDate(0);to=d.toISOString().slice(0,10);from=to.slice(0,7)+'-01';}
  else{const recent=q.match(/(?:最近|近)(\d+)天/);if(recent){const d=new Date(latest+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-Math.min(365,Number(recent[1]))+1);from=d.toISOString().slice(0,10);to=latest;}}
 }
 if(/全部日期|全部期间|所有月份|全年|全部历史/.test(q)){from='';to='';}return {from,to};
}
export async function ledgerAnswer(repo:Repository,tenant:string,question:string,previous:any={}){
 const all=await ledgerView(repo,tenant),latest=all.documents[0]?.date??new Date().toISOString().slice(0,10),raw=question.replace(/\s+/g,''),followup=/^(那|这|它|只|改成|换成|为什么|怎么|再)/.test(raw),q=followup&&previous.question?(previous.question+'；'+raw).replace(/\s+/g,'').slice(-4000):raw,range=dates(raw,latest,followup?previous:{}),v=await ledgerView(repo,tenant,range.from,range.to||'9999-12-31');
 const explicit=v.products.filter(p=>raw.includes(p.name)||new RegExp('(?:^|[^A-Za-z0-9])'+p.id+'(?:$|[^A-Za-z0-9])','i').test(raw));
 const aliases:Record<string,string[]>={T001:['无糖茶','茶饮'],W001:['瓶装水','矿泉水'],C001:['咖啡'],M001:['牛奶'],Y001:['酸奶'],B001:['面包'],N001:['方便面','泡面'],R001:['大米'],O001:['食用油','葵花籽油'],S001:['薯片'],P001:['纸巾','抽纸'],D001:['洗衣液']};
 const aliasMatches=explicit.length?explicit:v.products.filter(p=>(aliases[p.id]??[]).some(a=>raw.includes(a)));
 const clear=/全部商品|所有商品|整体|总体|全店|整店|各商品|哪些商品/.test(raw),ids=clear?[]:aliasMatches.length?aliasMatches.map(p=>p.id):followup?previous.productIds??[]:[];
 const categories=[...new Set(v.products.map(p=>p.category))].filter(c=>q.includes(c));
 let selected=v.products.filter(p=>(!ids.length||ids.includes(p.id))&&(!categories.length||categories.includes(p.category)));let intent='sales';
 const evidence:any[]=[];const add=(name:string,rows:any[],formula:string)=>{const ref='ledger-'+(evidence.length+1);evidence.push({reference:ref,sql:formula,tables:['documents','document_lines','movements','journal'],rowCount:rows.length,rows,databaseRevision:v.revision,source:v.source,queriedAt:new Date().toISOString(),label:name});return '['+ref+']';};
 const scope=selected.length===1?selected[0].name:categories.join('、')||'全店',period=range.from?`${range.from}至${range.to||latest}`:`全部记录（截至${range.to||latest}）`,source=v.source==='synthetic'?'【模拟门店账套】':'【企业经营账套】';
 let text='';const namedUnknown=/[“「"](.+?)[”」"]/.exec(question)?.[1];const unmatched=!aliasMatches.length&&!categories.length&&!followup&&!clear?raw.replace(/20\d{2}年|\d{1,2}月|这个月|本月|上月|请问|帮我查一下|帮我|查询|查一下|看看|的/g,'').match(/^(.{1,20}?)(?:卖了|买了|买入|卖出|库存|销量|价格)/)?.[1]:null;const unknown=namedUnknown??(unmatched&&!/全店|商品|销售|采购|门店|经营|哪些|现在|目前|今天|最近|茶水/.test(unmatched)?unmatched:null);if(unknown&&!v.products.some(p=>p.name.includes(unknown)||p.id===unknown))return {text:`账套里没有找到“${unknown}”。请用商品台账中的名称或编码查询。`,evidence,query:{...range,productIds:[],intent:'unknown'},scope};
 if(!v.documents.length){return {text:`${period}没有已过账业务单据，无法据此判断经营情况。你可以查看商品台账，或换一个日期范围。`,evidence,query:{...range,productIds:ids,intent:'empty'},scope};}
 if(/补货|备货|补多少|库存够|库存能否|促销/.test(q)){
  intent='replenish';const dm=[...q.matchAll(/(\d+)天/g)].at(-1),um=[...q.matchAll(/(?:增长|增幅|提升|增加)(\d+(?:\.\d+)?)%/g)].at(-1),days=dm?Number(dm[1]):null,uplift=um?Number(um[1]):null;
  if(!days||uplift===null){text=`要计算${scope}的促销备货量，还需要${!days?'活动持续几天':''}${!days&&uplift===null?'、':''}${uplift===null?'预计销量增长百分比':''}。例如：“无糖茶做7天促销，销量增长20%，补多少货？”`;}
  else if(days>60||uplift>300){text='当前测算支持1至60天、0%至300%的情景增长率，请缩小范围。';}
  else{const baselineStart=new Date(latest+'T00:00:00Z');baselineStart.setUTCDate(baselineStart.getUTCDate()-27);const recent=await ledgerView(repo,tenant,baselineStart.toISOString().slice(0,10),latest);const covered=28;
   const forecasts=selected.map(p=>{const latestP=all.products.find(x=>x.id===p.id)!,baseline=recent.products.find(x=>x.id===p.id)!,daily=baseline.net_sold/covered,forecast=Math.ceil(daily*days*(1+uplift/100)),gap=Math.max(0,forecast+latestP.safety_stock-latestP.stock),suggested=Math.ceil(gap/latestP.pack_size)*latestP.pack_size,leadCoverage=Math.ceil(daily*(1+uplift/100)*latestP.lead_days),cost=latestP.latest_purchase_cents??latestP.average_cost_cents;return {product_id:p.id,name:p.name,unit:p.unit,daily:Number(daily.toFixed(3)),days,uplift_percent:uplift,current_stock:latestP.stock,safety_stock:latestP.safety_stock,pack_size:latestP.pack_size,lead_days:latestP.lead_days,forecast,suggested,purchase_budget_cents:cost==null?null:suggested*cost,lead_time_risk:latestP.stock<leadCoverage};});const ref=add('商品级补货情景',forecasts,'最近28个完整自然日净销量÷28；ceil(日均×天数×(1+增长率))；补货=包装倍数×ceil(max(0,预测+安全库存-库存)/包装倍数)');
   text=`按${latest}库存和最近28个自然日销量，活动 ${days} 天、增长${uplift}%的情景测算：\n\n`+forecasts.map(p=>`- ${p.name}：库存${p.current_stock}${p.unit}，预计卖出${p.forecast}${p.unit}，建议补货${p.suggested}${p.unit}${p.purchase_budget_cents==null?'':`，预计采购金额${money(p.purchase_budget_cents)}`}。${p.lead_time_risk?'现有库存可能撑不到计划到货，需先核实加急供货。':''}`).join('\n')+`\n\n${ref} 增长率是你给定的假设；采用商品各自的安全库存、包装倍数和计划交期。未加入未确认的在途量，不保证供应商实际交期。账套需连续记录经营日，才能把无单据日作为零销量使用。`;
   const discount=q.match(/(\d+(?:\.\d+)?)折/);if(discount){const factor=Number(discount[1])/10;text+='\n\n折扣约束：'+selected.map(p=>{const cost=p.average_cost_cents??p.latest_purchase_cents;return cost==null?`${p.name}缺成本`:`${p.name}按当前标价打${discount[1]}折后，单件预计毛利${money(Math.round(p.price_cents*factor)-cost)}${Math.round(p.price_cents*factor)<=cost?'，不建议按此价格推广':''}`;}).join('；')+'。未扣活动费用与额外损耗。';}
  }
 }else if(/财务|现金|净利润|利润.*不同|对账|费用|应收|应付|经营风险|整体经营|经营情况/.test(q)){
  intent='finance';const ref=add('利润、现金与资产对账',[{period,...v.income,...v.cashflow,assets_cents:v.balance.assets_cents,liabilities_cents:v.balance.liabilities_cents,equity_cents:v.balance.equity_cents,receivable_cents:v.balance.receivable,payable_cents:-v.balance.payable}], '按所选期间汇总凭证；收入-成本-费用=经营净利润；期初现金+现金净流量=期末现金');add('利润到现金的差额桥',[v.bridge],'经营净利润-库存增加-应收增加+应付增加=经营现金流；余额减少显示负数');add('对账检查',v.checks,'逐单借贷、总账、库存、现金、应收与应付独立勾稽');
  text=`${period}，全店销售净额${money(v.income.revenue_cents)}，销售成本${money(v.income.cost_cents)}，毛利${money(v.income.gross_profit_cents)}；经营费用${money(v.income.expense_cents)}，经营净利润${money(v.income.net_profit_cents)}。${ref}\n\n同期经营现金净流量${money(v.cashflow.operating_cents)}，期末现金${money(v.cashflow.closing_cents)}，应收${money(v.balance.receivable)}，应付${money(-v.balance.payable)}。利润与现金的差额可核对为：经营净利润${money(v.bridge.profit_cents)} − 库存增加${money(v.bridge.inventory_change_cents)} − 应收增加${money(v.bridge.receivable_change_cents)} + 应付增加${money(v.bridge.payable_change_cents)} = 经营现金净流量${money(v.bridge.operating_cents)}。资金投入单独列为筹资现金流，不计入经营利润；减少额显示为负数。\n\n资产${money(v.balance.assets_cents)} = 负债${money(v.balance.liabilities_cents)} + 权益${money(v.balance.equity_cents)}；${v.checks.filter(c=>c.ok).length}/${v.checks.length}项对账通过。未计提所得税，这是本账套已记录业务口径。`;
  if(v.income.net_profit_cents<0){const expenses=v.documents.filter(d=>d.type==='expense').sort((a,b)=>b.amount_cents-a.amount_cents),largest=expenses[0];text+=`\n\n当前账套出现经营亏损：毛利不足以覆盖已记录费用。${largest?`期间最大费用是${largest.partner}，${money(largest.amount_cents)}。`:''}建议先核对费用周期和销量规模，再评估促销；不能只看销售增长。`;add('亏损诊断的费用单据',expenses.map(d=>({id:d.id,date:d.date,name:d.partner,amount_cents:d.amount_cents})),'费用单据按金额排序，不把采购支出当经营费用');}
  if(ids.length)text+='\n\n财务三表按整家门店统计；单品毛利可以单独查询，店级费用没有随意分摊给某个商品。';
 }else if(/库存|缺货|安全库存|积压/.test(q)){
  intent='inventory';if(/低于|缺货|不足|风险|哪些/.test(q))selected=selected.filter(p=>p.stock<p.safety_stock);
  const ref=add('库存余额',selected.map(p=>({product_id:p.id,name:p.name,unit:p.unit,stock:p.stock,safety_stock:p.safety_stock,stock_value_cents:p.stock_value_cents,as_of:range.to||latest})), '库存=累计采购入库-累计销售出库+累计销售退回；库存价值=累计成本流水');text=selected.length?selected.map(p=>`${p.name}：库存${p.stock}${p.unit}，安全库存${p.safety_stock}${p.unit}，库存价值${money(p.stock_value_cents)}${p.stock<p.safety_stock?'，低于安全库存':''}。`).join('\n')+`\n\n截至${range.to||latest}，${ref}`:`截至${range.to||latest}，所选商品没有低于安全库存的记录。${ref} 这不等于未来促销一定不会缺货。`;
 }else if(/待到货|没到货|未到货|采购单/.test(q)){
  intent='purchase';const docs=v.documents.filter(d=>d.type==='purchase'&&(!ids.length||d.lines.some((l:any)=>ids.includes(l.product_id))));const ref=add('已收货采购单',docs.map(d=>({id:d.id,date:d.date,partner:d.partner,amount_cents:d.lines.filter((l:any)=>!ids.length||ids.includes(l.product_id)).reduce((n:number,l:any)=>n+l.amount_cents,0),scope:ids.length?'所选商品采购行金额':'整张采购单金额'})), '本账套采购单采用收货即入库口径；未收货采购计划尚未入账');const pending=all.plans.filter(p=>['approved','partial'].includes(p.status)&&(!ids.length||p.lines.some((l:any)=>ids.includes(l.product_id))));text=`所选期间记录了${docs.length}张已收货采购入库单，${ids.length?'所选商品行金额':'金额'}${money(docs.reduce((n,d)=>n+d.lines.filter((l:any)=>!ids.length||ids.includes(l.product_id)).reduce((a:number,l:any)=>a+l.amount_cents,0),0))}。${ref}\n\n`+(pending.length?pending.map(p=>`采购计划${p.id.slice(0,8)}：${p.partner}，计划到货${p.due_date}；`+p.lines.filter((l:any)=>!ids.length||ids.includes(l.product_id)).map((l:any)=>`${l.name}待收${l.quantity-l.received}${l.unit}`).join('、')).join('\n')+'。未收货数量未计入现货。':'当前账套没有未收货采购计划和供应商确认记录，不能据此声称“全部采购都已到货”。');if(pending.length)add('待收货采购计划',pending,'批准计划数量-累计实际收货=待收数量');
 }else{
  if(/排名|排行|最好|最多|前\d+/.test(q)){intent='ranking';const limit=Math.min(50,Number(q.match(/前(\d+)/)?.[1]??10)),byQuantity=/销量|数量|卖.*多/.test(q);selected=[...selected].sort((a,b)=>(byQuantity?b.net_sold-a.net_sold:b.revenue_cents-a.revenue_cents)).slice(0,limit);if(byQuantity&&new Set(selected.map(p=>p.unit)).size>1){text='商品包含不同计量单位，不能直接把瓶、袋、桶的销量放在一个数量榜比较。可以查询“销售额排名”，或指定同一计量单位的商品。';}}
  const ref=add('商品进销存与毛利',selected.map(p=>({product_id:p.id,name:p.name,unit:p.unit,bought:p.bought,sold:p.sold,returned:p.returned,stock:p.stock,price_cents:p.price_cents,latest_purchase_cents:p.latest_purchase_cents,revenue_cents:p.revenue_cents,cost_cents:p.cost_cents,gross_profit_cents:p.profit_cents})), '商品明细按日期聚合；净销售量=卖出-退回；销售毛利=销售净额-销售成本');
  if(!text)text=`${period}：\n\n`+selected.map(p=>`- ${p.name}（${p.specification}）：买入${p.bought}${p.unit}，卖出${p.sold}${p.unit}，退回${p.returned}${p.unit}，净卖出${p.net_sold}${p.unit}；期末库存${p.stock}${p.unit}。销售净额${money(p.revenue_cents)}，销售毛利${money(p.profit_cents)}。${/价格|价钱|售价|单价/.test(q)?`当前标价${money(p.price_cents)}，最近采购价${p.latest_purchase_cents==null?'未提供':money(p.latest_purchase_cents)}。`:''}`).join('\n')+`\n\n${ref} 买入指已收货数量；毛利尚未扣门店经营费用。`;
 }
 return {text:source+'\n'+text,evidence,query:{...range,productIds:ids,intent},scope};
}
