import {createCipheriv,createDecipheriv,createHash,randomBytes} from 'node:crypto';
import {z} from 'zod';
import type {Repository} from './api.ts';
const schema=z.object({provider:z.enum(['OpenAI','Groq','Zhipu','Ark']).default('OpenAI'),guestEnabled:z.boolean().default(false),guestDailyLimit:z.number().int().min(1).max(100).default(20),model:z.string().trim().max(100).regex(/^[a-zA-Z0-9._:\/-]*$/),apiKey:z.string().trim().max(512).optional(),enabled:z.boolean(),revision:z.number().int().min(0),dailyLimit:z.number().int().min(1).max(500),tokenBudget:z.number().int().min(1000).max(100000000).default(500000),priorTokenReserve:z.number().int().min(0).max(100000000).default(0)});
function encryptionKey(secret:string){if(secret.length<32)throw Error('服务器加密密钥未配置');return createHash('sha256').update('zhilian-model-key:'+secret).digest()}
function encrypt(value:string,secret:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',encryptionKey(secret),iv);const text=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return [iv.toString('base64'),cipher.getAuthTag().toString('base64'),text.toString('base64')].join('.')}
function decrypt(value:string,secret:string){const [iv,tag,text]=value.split('.').map(v=>Buffer.from(v,'base64')),cipher=createDecipheriv('aes-256-gcm',encryptionKey(secret),iv);cipher.setAuthTag(tag);return Buffer.concat([cipher.update(text),cipher.final()]).toString('utf8')}
export async function modelSettings(repo:Repository){const v=(await repo.get('settings/model'))?.value,usage=(await repo.get('usage/site-tokens'))?.value;return {provider:v?(v.provider??'OpenAI'):'Ark',guestEnabled:v?.guestEnabled??false,guestDailyLimit:v?.guestDailyLimit??20,model:v?.model??'doubao-seed-2-1-lite-260915',enabled:v?.activationVersion===2&&(v?.enabled??false),hasKey:!!v?.encryptedKey,revision:v?.revision??0,dailyLimit:v?.dailyLimit??30,tokenBudget:v?.tokenBudget??500000,priorTokenReserve:v?.priorTokenReserve??0,usedTokens:usage?.used??0,reservedTokens:usage?.reserved??0}}
export async function saveModel(repo:Repository,secret:string,input:unknown){const b=schema.parse(input);if(b.priorTokenReserve>=b.tokenBudget)throw Error('既往试运行预留应小于本站token预算');if(b.apiKey&&(/\.{3}|…/.test(b.apiKey)))throw Error('密钥包含省略号，请粘贴完整 API Key，不要使用控制台遮盖后的文本');const old=await repo.get('settings/model');if((old?.value.revision??0)!==b.revision)throw Error('设置已更新，请刷新后重新保存');const changed=(old?.value.provider??'OpenAI')!==b.provider;const encryptedKey=b.apiKey?encrypt(b.apiKey,secret):changed?null:old?.value.encryptedKey;if(b.enabled&&(!encryptedKey||!b.model))throw Error('启用前请填写模型名称和 API Key');const next={activationVersion:2,provider:b.provider,guestEnabled:b.guestEnabled,guestDailyLimit:b.guestDailyLimit,model:b.model,enabled:b.enabled,encryptedKey,revision:b.revision+1,dailyLimit:b.dailyLimit,tokenBudget:b.tokenBudget,priorTokenReserve:b.priorTokenReserve};if(!await repo.put('settings/model',next,old?.version??null))throw Error('设置发生冲突，请刷新后重试');return modelSettings(repo)}
export async function removeModelKey(repo:Repository){const old=await repo.get('settings/model');if(old&&!await repo.put('settings/model',{...old.value,encryptedKey:null,enabled:false,revision:old.value.revision+1},old.version))throw Error('设置已更新，请刷新后重试');return modelSettings(repo)}
// Reserve a conservative upper bound before dispatch. Failed or interrupted calls
// retain their reservation because the provider may have processed the request.
async function tokenReservation(repo:Repository,config:any,instructions:string,input:string){
 const amount=Buffer.byteLength(instructions,'utf8')+Buffer.byteLength(input,'utf8')+2400+4096,limit=config.tokenBudget??500000,prior=config.priorTokenReserve??0;
 for(let i=0;i<10;i++){const old=await repo.get('usage/site-tokens'),v=old?.value??{used:0,reserved:0};if(v.used+v.reserved+prior+amount>limit)throw Error('本站模型体验预算不足；可在后台查看已用及预留用量');if(await repo.put('usage/site-tokens',{used:v.used,reserved:v.reserved+amount},old?.version??null))return amount}
 throw Error('用量记录繁忙，请稍后重试');
}
async function settleTokens(repo:Repository,amount:number,usage:any){const reported=usage?.total_tokens;if(!Number.isSafeInteger(reported)||reported<0)return;for(let i=0;i<10;i++){const old=await repo.get('usage/site-tokens');if(!old)return;const v=old.value;if(await repo.put('usage/site-tokens',{used:v.used+reported,reserved:Math.max(0,v.reserved-amount)},old.version))return}}
export async function callModel(repo:Repository,secret:string,instructions:string,input:string,fetcher:typeof fetch=fetch,guest=false){const row=await repo.get('settings/model'),config=row?.value;if(config?.activationVersion!==2||!config?.enabled||!config?.encryptedKey)throw Error('模型未启用');if(guest){if(!config.guestEnabled)throw Error('游客模型未开放');const guestKey='usage/guest/'+new Date().toISOString().slice(0,10);let ok=false;for(let i=0;i<5;i++){const old=await repo.get(guestKey),n=(old?.value.calls??0)+1;if(n>(config.guestDailyLimit??20))throw Error('今日游客体验额度已用完');if(await repo.put(guestKey,{calls:n},old?.version??null)){ok=true;break}}if(!ok)throw Error('游客模型繁忙')}const key='usage/model/'+new Date().toISOString().slice(0,10);let reserved=false;for(let i=0;i<5;i++){const old=await repo.get(key),n=(old?.value.calls??0)+1;if(n>config.dailyLimit)throw Error('今日模型调用次数已达上限');if(await repo.put(key,{calls:n},old?.version??null)){reserved=true;break}}if(!reserved)throw Error('模型繁忙，请稍后再试');const groq=config.provider==='Groq',zhipu=config.provider==='Zhipu',ark=config.provider==='Ark',chatAPI=groq||zhipu;const boundedFetch:typeof fetch=async(url,options)=>{for(let attempt=0;;attempt++){const r=await fetcher(url,options);if(!zhipu||r.status!==429||attempt>=2)return r;await r.text();await new Promise(resolve=>setTimeout(resolve,1500*(attempt+1)));}};const tokenReserved=await tokenReservation(repo,config,instructions,input);const response=await boundedFetch(ark?'https://ark.cn-beijing.volces.com/api/v3/responses':zhipu?'https://open.bigmodel.cn/api/paas/v4/chat/completions':groq?'https://api.groq.com/openai/v1/chat/completions':'https://api.openai.com/v1/responses',{method:'POST',redirect:'error',signal:AbortSignal.timeout(45000),headers:{Authorization:'Bearer '+decrypt(config.encryptedKey,secret),'Content-Type':'application/json'},body:JSON.stringify(chatAPI?{model:config.model,messages:[{role:'system',content:instructions},{role:'user',content:input}],...(zhipu||ark?{max_tokens:2400,thinking:{type:'disabled'}}:{max_completion_tokens:2400}),stream:false}:{model:config.model,instructions,input,max_output_tokens:2400,store:false,...(ark?{thinking:{type:'disabled'}}:{})})});if(!response.ok){const failure:any=await response.json().catch(()=>({}));const code=String(failure.error?.code??'');const suffix=/^\d{3,8}$/.test(code)?'（服务代码 '+code+'）':'';throw Error((code==='1305'?'智谱当前繁忙，已等待重试，请稍后再试':response.status===401?'API Key 无效或无权限':response.status===429?'模型额度不足或请求过多':'模型服务请求失败（'+response.status+'）')+suffix);}const data:any=await response.json();await settleTokens(repo,tokenReserved,data.usage);const output=chatAPI?data.choices?.[0]?.message?.content:(data.output??[]).flatMap((o:any)=>o.content??[]).filter((c:any)=>c.type==='output_text').map((c:any)=>c.text).join('\n');if(!output||data.status==='incomplete'||(chatAPI&&data.choices?.[0]?.finish_reason!=='stop'))throw Error('模型未生成完整答复，请缩小问题范围后重试');return {text:output,model:config.model,usage:data.usage??null}}
