import {prepareChineseCase} from './case-localization.ts';
export const rowCost=(c:any,r:any[])=>c.costByRow?.[String(r[0])]??Math.round(r[4]*(c.products.find((p:any)=>p.id===r[2])?.cost_scaled??0));
export function retailCase(original:any,supplement:any,from='2026-09-01',to='2026-09-30'){
 ({original,supplement}=prepareChineseCase(original,supplement));
 const end=to||'9999-12-31',start=from||'',qs=supplement.quantity_scale??1,q=(n:number)=>Math.round(n*qs)/qs,value=(p:any,n:number)=>Math.round(q(n)*qs*p.cost_scaled/qs);
 const byId=new Map<string,any>(supplement.products.map((p:any)=>[p.id,{...p,stock:0,bought:0,sold:0,returned:0,lost:0,revenue_scaled:0,cost_total_scaled:0}])),flow:any[]=[];
 const events:any[]=[...supplement.purchases.map((d:any)=>({kind:'purchase',at:d.timestamp??d.date+'T00:00:00',d})),...original.rows.map((r:any[])=>({kind:'sale',at:r[5],r})),...(supplement.stock_losses??[]).map((d:any)=>({kind:'loss',at:d.timestamp??d.date+'T23:59:59',d}))].sort((a,b)=>a.at.localeCompare(b.at));
 const selected=original.rows.filter((r:any[])=>r[5].slice(0,10)>=start&&r[5].slice(0,10)<=end);
 for(const e of events){const dt=e.at.slice(0,10);if(dt>end)continue;const included=dt>=start;
  if(e.kind==='purchase'){for(const l of e.d.lines){const p=byId.get(l.product_id),before=p.stock;p.stock=q(p.stock+l.quantity);if(included){p.bought=q(p.bought+l.quantity);flow.push({date:dt,timestamp:e.at,document_id:e.d.id,name:p.name,product_id:p.id,type:'采购入库（拟）',quantity_before:before,quantity_change:l.quantity,quantity_after:p.stock,value_before_scaled:value(p,before),value_change_scaled:l.amount_scaled,value_after_scaled:value(p,p.stock),source_row:'规则生成（拟）',amount_scaled:l.amount_scaled,source:'（拟）'})}}}
  else if(e.kind==='sale'){const r=e.r,p=byId.get(r[2]),before=p.stock,change=p.stocked?-r[4]:0;p.stock=q(p.stock+change);if(included){const cost=supplement.cost_by_row?.[String(r[0])]??Math.round(r[4]*p.cost_scaled);p.sold=q(p.sold+Math.max(0,r[4]));p.returned=q(p.returned+Math.max(0,-r[4]));p.revenue_scaled+=r[7];p.cost_total_scaled+=cost;flow.push({date:dt,timestamp:e.at,document_id:r[1],product_id:p.id,name:r[3]||p.name,type:p.stocked?(r[4]<0?'退货回补（拟）':'销售出库（拟）'):'非实物调整',quantity_before:before,quantity_change:change,quantity_after:p.stock,value_before_scaled:value(p,before),value_change_scaled:-cost,value_after_scaled:value(p,p.stock),source_row:r[0],amount_scaled:r[7],source:'销售数量及单价为公开原值；库存变动（拟）'})}}
  else{const d=e.d,p=byId.get(d.product_id),before=p.stock;p.stock=q(p.stock-d.quantity);if(included){p.lost=q(p.lost+d.quantity);flow.push({date:dt,timestamp:e.at,document_id:d.id,product_id:p.id,name:p.name,type:'损耗出库（拟）',quantity_before:before,quantity_change:-d.quantity,quantity_after:p.stock,value_before_scaled:value(p,before),value_change_scaled:-d.amount_scaled,value_after_scaled:value(p,p.stock),source_row:'附件4参考损耗率，拟定数量',amount_scaled:d.amount_scaled,source:d.source})}}
 }
 const products=[...byId.values()].map(p=>({...p,stock_value_scaled:value(p,p.stock),gross_profit_scaled:p.revenue_scaled-p.cost_total_scaled})),inRange=(r:any)=>r.date>=start&&r.date<=end,documents=supplement.documents.filter(inRange),journal=supplement.journal.filter((r:any)=>r.date<=end),trial:Record<string,number>={};for(const j of journal)trial[j.account]=(trial[j.account]??0)+j.debit_scaled-j.credit_scaled;
 const revenue=selected.reduce((n:number,r:any[])=>n+r[7],0),cost=products.reduce((n,p)=>n+p.cost_total_scaled,0),expenses=documents.filter((d:any)=>['expense','stock_loss'].includes(d.type)).reduce((n:number,d:any)=>n+d.amount_scaled,0),loss=documents.filter((d:any)=>d.type==='stock_loss').reduce((n:number,d:any)=>n+d.amount_scaled,0),profit=revenue-cost-expenses;
 const cash=trial.cash??0,receivable=trial.receivable??0,inventory=products.reduce((n,p)=>n+p.stock_value_scaled,0),payable=-(trial.payable??0),capital=-(trial.capital??0),retained=-(trial.revenue??0)-(trial.cogs??0)-(trial.expense??0),opening=supplement.documents.filter((d:any)=>d.date<start&&d.date<=end).reduce((n:number,d:any)=>n+d.cash_scaled,0),cashchange=documents.reduce((n:number,d:any)=>n+d.cash_scaled,0),dbalance=new Map<string,number>();for(const j of journal)dbalance.set(j.document_id,(dbalance.get(j.document_id)??0)+j.debit_scaled-j.credit_scaled);
 return {from:start,to:end,source:original.source,products,flow,sales:selected,salesMeta:original.sales_meta??{},costByRow:supplement.cost_by_row??{},wholesale:original.wholesale??null,lossReference:original.loss_reference??null,suppliers:supplement.suppliers,purchases:supplement.purchases.filter(inRange),marketing:supplement.marketing.filter((r:any)=>r.date<=end&&r.end>=start),fulfillment:supplement.fulfillment.filter(inRange),aftersales:supplement.aftersales.filter(inRange),documents,journal:supplement.journal.filter(inRange),income:{revenue_scaled:revenue,cost_scaled:cost,gross_profit_scaled:revenue-cost,expense_scaled:expenses,loss_scaled:loss,net_profit_scaled:profit},balance:{cash,receivable,inventory,assets:cash+receivable+inventory,payable,capital,retained,equity:capital+retained},cashflow:{opening,change:cashchange,closing:cash},checks:[{name:'每张凭证借贷平衡（拟）',difference:[...dbalance.values()].filter(n=>n!==0).length},{name:'资产 = 负债 + 权益（拟）',difference:cash+receivable+inventory-payable-capital-retained},{name:'库存明细 = 库存总账（拟）',difference:inventory-(trial.inventory??0)},{name:'期初现金 + 收支 = 期末现金（拟）',difference:opening+cashchange-cash},{name:'商品销售净额 = 原始销量售价演算',difference:products.reduce((n,p)=>n+p.revenue_scaled,0)-revenue},{name:'原单汇总 = 销售明细',difference:documents.filter((d:any)=>d.type==='sale').reduce((n:number,d:any)=>n+d.amount_scaled,0)-revenue}],policy:supplement.policy};
}
