import {ReleasePanel} from './releases';
"use client";
import {useEffect,useState} from 'react';import {Bot,Save,Code2,Database,Check,ArrowLeft,RefreshCw} from 'lucide-react';import {defaults,type AgentConfig} from '../lib/agents';
export default function AgentEditor({initialId,onBack,onSaved}:{initialId:string,onBack:()=>void,onSaved:()=>void}){const [agents,setAgents]=useState(defaults),[id,setId]=useState(initialId),[draft,setDraft]=useState<AgentConfig>(defaults.find(a=>a.id===initialId)??defaults[0]),[user,setUser]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
async function load(){try{const r=await fetch('/api/agents'),d:any=await r.json();if(!r.ok)throw Error(d.error);setAgents(d.agents);setUser(d.user);setDraft(d.agents.find((a:AgentConfig)=>a.id===id)??d.agents[0]);setDirty(false);}catch(e){setMessage((e as Error).message);}}
useEffect(()=>{load();},[]);useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[dirty]);
function edit(p:Partial<AgentConfig>){setDraft(d=>({...d,...p}));setDirty(true);}
function choose(a:AgentConfig){if(dirty&&!confirm('当前修改尚未保存，确定切换 Agent 吗？'))return;setId(a.id);setDraft(a);setDirty(false);setMessage('');}
async function save(){setBusy(true);try{const r=await fetch('/api/agents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)}),d:any=await r.json();if(!r.ok)throw Error(d.error);const saved={...draft,revision:d.revision};setDraft(saved);setAgents(a=>a.map(x=>x.id===id?saved:x));setDirty(false);setMessage('已保存第 '+d.revision+' 版。草稿已保存，请试运行后发布，客户端才会使用。');onSaved();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
return <section className="editor-page"><div className="page-heading"><div><small>AGENT BUILDER</small><h2>智能体编辑台</h2><p>编辑自己的智能体角色、任务和数据能力。</p></div><button onClick={()=>{if(!dirty||confirm('修改尚未保存，确定离开吗？'))onBack();}}><ArrowLeft size={16}/>返回工作流</button></div>
<ReleasePanel key={agents.map(a=>a.revision).join('|')}/><div className="editor-shell"><aside className="agent-list">{agents.map(a=><button key={a.id} className={id===a.id?'selected':''} onClick={()=>choose(a)}><Bot size={19}/><span>{a.name}<small>{a.revision?'已保存 v'+a.revision:'预置模板'}</small></span></button>)}</aside><div className="editor-main">
<div className="editor-top"><div><Bot size={20}/><strong>{draft.name}</strong><span className="outline-tag">{dirty?'有未保存修改':'v'+draft.revision}</span></div><div>{!user?<a className="login-link" target="_top" href="/admin">登录后保存</a>:<button className="primary" disabled={busy||!dirty} onClick={save}><Save size={16}/>保存草稿</button>}</div></div>
{message&&<div className="editor-message" role="status">{message}</div>}<div className="editor-columns"><div><h3>智能体信息</h3><label>智能体名称<input maxLength={50} value={draft.name} onChange={e=>edit({name:e.target.value})}/></label><label>智能体简介<textarea rows={3} maxLength={300} value={draft.description} onChange={e=>edit({description:e.target.value})}/></label><h3>调度设置</h3>{!['orchestrator','review'].includes(id)&&<label className="check-row"><input type="checkbox" checked={draft.enabled!==false} onChange={e=>edit({enabled:e.target.checked})}/>允许总控调用此 Agent</label>}{id==='orchestrator'&&<div className="cap-card"><p>允许总控调度的业务节点（按需选择，并非全部执行）</p>{agents.filter(a=>!['orchestrator','review'].includes(a.id)).map(a=><label className="check-row" key={a.id}><input type="checkbox" checked={!draft.delegates||draft.delegates.includes(a.id)} onChange={e=>{const all=draft.delegates??agents.filter(x=>!['orchestrator','review'].includes(x.id)).map(x=>x.id);edit({delegates:e.target.checked?[...all,a.id]:all.filter(x=>x!==a.id)})}}/>{a.name}</label>)}</div>}<h3>基础配置</h3><label>角色与任务设定<textarea className="prompt-editor" rows={13} maxLength={12000} value={draft.prompt} onChange={e=>edit({prompt:e.target.value})}/></label><div className="editor-hint">{draft.prompt.length} / 12000 字符 · 直接编辑，无需写代码</div></div><div className="capabilities"><h3>扩展能力</h3><div className="cap-card"><h4><Code2 size={17}/>运行模型</h4><p>规则引擎 / 后台统一配置模型</p><div className="editor-hint">在「模型接入」中启用后，企业咨询会使用此提示词。未启用时使用只读查询与规则分析。</div></div><div className="cap-card"><h4><Database size={17}/>数据 API</h4><p>业务节点只查询已勾选且属于其职责范围的数据表。</p>{['products','orders','inventory','campaigns','suppliers','purchase_orders','sales_orders','deliveries','returns'].map(t=><label className="check-row" key={t}><input type="checkbox" checked={draft.tools.includes(t)} onChange={e=>edit({tools:e.target.checked?[...draft.tools,t]:draft.tools.filter(x=>x!==t)})}/><code>{t}</code><span>{({products:'商品',orders:'销售',inventory:'库存',campaigns:'活动',suppliers:'供应商',purchase_orders:'采购单',sales_orders:'销售明细',deliveries:'履约',returns:'售后'} as Record<string,string>)[t]}</span></label>)}{id!=='orchestrator'&&<small>取消所需数据权限后，节点会报告数据缺口；总控与回顾使用下游证据。</small>}</div>{id==='replenish'&&<div className="cap-card"><h4>补货计算参数</h4><label>每组包装数量<input type="number" min={1} max={10000} value={draft.packSize} onChange={e=>edit({packSize:Number(e.target.value)})}/></label><label>缺口额外缓冲（%）<input type="number" min={0} max={100} value={draft.bufferPercent} onChange={e=>edit({bufferPercent:Number(e.target.value)})}/></label><p>建议量 = 按包装数量向上取整（缺口 × (1 + 缓冲)）。保存后用于经营报表的促销备货测试。</p></div>}<div className="cap-card"><h4>配置归属</h4><p>{user?user.name+' · 全站业务配置':'访客可试写，登录后才能持久保存。'}</p><small>发布后的配置用于客户新咨询；已有报告保留当时的参数版本。</small></div></div></div></div></div></section>;
}




