import {useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowUpRight,Bot,Check,CheckCheck,Copy,Download,LoaderCircle,MessageSquarePlus,PackageSearch,ReceiptText,Square,TrendingUp,Wallet} from 'lucide-react';
import './case-agent.css';
const intentNames:Record<string,string>={product:'商品销量与库存',finance:'财务核查',procurement:'供货采购',marketing:'营销活动',fulfillment:'履约查询',aftersales:'售后查询',forecast:'备货测算',ranking:'销售排名',source:'数据来源',profit:'利润预测 Skill'};
const money=(n:number)=>'¥'+(n/10000).toLocaleString('zh-CN',{maximumFractionDigits:4});
async function api(path:string,body?:any,key=''){const r=await fetch('/api/v2/case/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','x-case-key':key},...(body?{body:JSON.stringify(body)}:{})}),d=await r.json();if(!r.ok)throw Error(d.error??'服务暂不可用');return d}
function exportForecast(run:any){const heads=['报告编号','账套','样本开始（拟）','样本结束（拟）','商品编码','商品名称','日历样本天数','正向销量','负向销量','库存（拟）','日均正向销量','预测方法','预测开始（拟）','预测结束（拟）','预测天数','需求增幅（拟）%','预计销量','安全库存（拟）','缺口','包装（拟）','缓冲（拟）%','建议备货（拟）','采购单价（拟）元','采购预算（拟）元','原表行数','原表行号示例'];const rows=(run.allocation?.rows??run.forecasts).map((f:any)=>[run.id,run.scope.caseId,f.from,f.to,f.productId,f.name,f.sampleDays,f.sold,f.returned,f.stock,f.average,f.method,f.horizonFrom,f.horizonTo,f.days,f.uplift,f.forecast,f.safety,f.gap,f.packSize,f.bufferPercent,f.suggested,f.cost_scaled/10000,f.budget_scaled/10000,f.sourceRowCount,f.sourceRows.join('、')]);const csv='\ufeff'+[heads,...rows].map(r=>r.map((v:any)=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='备货测算-'+run.id+'.csv';a.click();URL.revokeObjectURL(url)}
export function ForecastCards({rows}:{rows:any[]}){const [expanded,setExpanded]=useState(false);return <div>{(expanded?rows:rows.slice(0,3)).map(f=><article key={f.productId} className="case-forecast"><header><div><small>备货方案（拟） · {f.productId}</small><h3>{f.name}</h3></div><a href={'/real-data?tab=products&q='+encodeURIComponent(f.productId)+'&from='+f.from+'&to='+f.to}>回查商品与流水 ↗</a></header><div className="case-numbers">{[['账面库存（拟）',f.stock],['次日可售（拟）',f.availableStock],['预计销量（千克）',f.forecast],['安全库存（拟）',f.safety],['库存缺口',f.gap],['建议备货（拟）',f.suggested],['采购预算（拟）',money(f.budget_scaled)]].map(([n,v])=><div key={n}><small>{n}</small><b>{v}</b></div>)}</div><p>库存截至 {f.asOf} · 样本 {f.sampleDays} 个日历日 · 预测 {f.horizonFrom} 至 {f.horizonTo} · 增幅 {f.uplift}%（拟）</p><details><summary>计算、误差与原单依据</summary><p>日均正向销量 {f.average.toFixed(4)}；方法：{f.method}。负向数量 {f.returned} 已参与库存回补（拟）。</p><p>缺口 = max（0，预测销量 ÷（1 − 参考损耗率）+ 安全余量 − 预测窗口可售库存），数量保留3位小数。建议备货按每天需求与包装 {f.packSize} 千克、缓冲 {f.bufferPercent}% 向上取整（拟），受总预算限制时按包装减少。</p>{f.mae&&<p>末 {f.mae.days} 天留出检验：日均法平均绝对误差 {f.mae.average.toFixed(4)}，星期分组法 {f.mae.weekday.toFixed(4)}，选误差较小的方法。</p>}<p>{f.availabilityRule}</p>{f.wholesaleReference_scaled!=null&&<p>本月公开批发价中位数 {money(f.wholesaleReference_scaled)}/千克；保留一位小数作为采购成本（拟）。批发价原表行号：{f.wholesaleSourceRows.map((r:any)=>r.row).join('、')}；近期损耗率原表行号：{f.lossSourceRow}。可在Excel对应原表中核验。</p>}<p>参考近期损耗率 {f.lossPercent}%；{f.budgetLimited?`预算限制减少采购，尚有未满足需求 ${f.unfulfilled} 千克（拟）`:"本商品未受预算压缩"}。</p><p>{f.warning}</p>{f.dailyPlan?.length>0&&<div className="ledger-table"><table><thead><tr><th>到货日期（拟）</th><th>预计销售 千克</th><th>采购 千克（拟）</th><th>预算（拟）</th></tr></thead><tbody>{f.dailyPlan.map((d:any)=><tr key={d.date}><td>{d.date}</td><td>{d.demand}</td><td>{d.suggested}</td><td>{money(d.budget_scaled)}</td></tr>)}</tbody></table></div>}<p>原始销售明细 {f.sourceRowCount} 行；示例原表行号：{f.sourceRows.join('、')}。原单：{f.invoiceRefs.join('、')}。</p>{f.assumptions.map((s:string)=><p key={s}>{s}</p>)}</details></article>)}{rows.length>3&&<button className="forecast-more" onClick={()=>setExpanded(!expanded)}>{expanded?'收起更多商品':`展开其余 ${rows.length-3} 种商品`}</button>}</div>}
function AnswerText({text}:{text:string}){return <div className="case-answer">{text.split(/\n\s*\n/).map((part,i)=><p key={i}>{part}</p>)}</div>}
function ProfitAnswer({run}:{run:any}){return <>{run.evidence.filter((e:any)=>e.tool==='利润预测与目标测算').map((e:any)=>{const r=e.data.result;return <section className="answer-finance" key={e.ref}><div className="answer-card-heading"><b>利润预测 Skill · 情景测算（拟）</b><span>{e.ref}</span></div><p>{r.horizon.from} 至 {r.horizon.to} · {r.horizon.days}天（拟）</p><div className="answer-finance-grid">{[['预测销售净额（拟）',r.revenue_scaled],['销售成本（拟）',r.cost_scaled],['损耗费用（拟）',r.loss_scaled],['其他费用（拟）',r.fixed_scaled],['预测净利润（拟）',r.profit_scaled],['目标差距（拟）',r.gap_scaled]].map(([label,value])=><div key={label as string}><small>{label}</small><strong>{money(value as number)}</strong></div>)}</div><details className="answer-bridge" open><summary>各条件对利润的贡献（拟）</summary>{r.bridge.map((v:any)=><div key={v.name}><span>{v.name}</span><b>{money(v.amount_scaled)}</b></div>)}</details><p>销量变化 {r.parameters.quantityChange}%，售价变化 {r.parameters.priceChange}%，单位成本变化 {r.parameters.costChange}%，损耗费用改善 {r.parameters.lossReduction}%，其他费用变化 {r.parameters.fixedChange}%（拟）。目标 {money(r.target_scaled)}（拟）；{r.targetMet?'按当前假设条件满足。':'尚未达到。'}成本费用为拟定口径，结果不代表真实或已实现的利润。</p><a className="context-link" href="/growth">打开工作台调整条件 ↗</a></section>})}</>}
function EvidenceCards({run}:{run:any}){return <>{run.evidence.filter((e:any)=>e.tool==='财务报表与对账'||e.tool==='经营商品排名').map((e:any)=>e.tool==='财务报表与对账'?<section className="answer-finance" key={e.ref}><div className="answer-card-heading"><b>利润与现金，分别看清楚</b><span>{e.ref}</span></div><div className="answer-finance-grid">{[['销售净额',e.data.income.revenue_scaled],['销售成本（拟）',e.data.income.cost_scaled],['销售毛利（拟）',e.data.income.gross_profit_scaled],['经营费用（拟）',e.data.income.expense_scaled],['净利润（拟）',e.data.income.net_profit_scaled],['期末现金（拟）',e.data.balance.cash]].map(([label,value])=><div key={label as string}><small>{label}</small><strong>{money(value as number)}</strong></div>)}</div><details className="answer-bridge" open><summary>从利润到现金的调节（拟）</summary>{[['期初现金',e.data.bridge.openingCash],['＋ 本期净利润',e.data.bridge.profit],['＋ 本期资本投入',e.data.bridge.capital],['＋ 应付增加',e.data.bridge.payable],['－ 应收增加',e.data.bridge.receivable],['－ 库存增加',e.data.bridge.inventory],['＝ 期末现金',e.data.bridge.closingCash]].map(([label,value])=><div key={label as string}><span>{label}</span><b>{money(value as number)}</b></div>)}</details><p>资本投入、应付和库存变动会影响现金；现金余额并不等于本期净利润。金额保留原账套精度，单位人民币。</p></section>:<section className="answer-ranking" key={e.ref}><div className="answer-card-heading"><b>{({quantity:'正向销量',revenue:'销售净额',gross:'毛利（拟）',margin:'毛利率（拟）'} as any)[e.data.metric]}排名</b><span>{e.data.ascending?'从低到高':'从高到低'} · {e.ref}</span></div>{e.data.rows.map((p:any,i:number)=><a href={'/real-data?tab=products&q='+encodeURIComponent(p.id)+'&from='+run.scope.from+'&to='+run.scope.to} key={p.id}><span className="ranking-number">{String(i+1).padStart(2,'0')}</span><div><b>{p.name}</b><small>销售额 {money(p.revenue_scaled)} · 毛利 {money(p.gross_profit_scaled)}（拟）</small></div><strong>{e.data.metric==='quantity'?p.sold:e.data.metric==='gross'?money(p.gross_profit_scaled):e.data.metric==='margin'?(p.margin*100).toFixed(2)+'%':money(p.revenue_scaled)}<small>{e.data.metric==='quantity'?p.unit:''}</small></strong></a>)}</section>)}</>}
export function RunDetail({run,conversation=false}:{run:any,conversation?:boolean}){
 const [copied,setCopied]=useState(false),[copyError,setCopyError]=useState('');
 async function copy(){try{await navigator.clipboard.writeText(run.answer??'');setCopied(true);setCopyError('');setTimeout(()=>setCopied(false),2000)}catch{setCopyError('复制未完成，请选中回答复制。')}}
 const phases=['理解目标','查询与计算','生成与核查'],phaseIndex=({plan:0,tools:1,review:2} as any)[run.phase]??0;
 return <div className={'case-run '+(conversation?'conversation-result':'')}>
  <div className="case-run-meta"><span>{({running:'分析中',failed:'执行失败',cancelled:'已停止',completed:'分析完成'} as any)[run.status]}</span><span>{run.modelEnabled?'模型 + 账套工具':'账套规则查询'}</span><span>{run.scope.from.slice(5)} — {run.scope.to.slice(5)}（拟）</span></div>
  {!conversation&&<p className="case-question">{run.question}</p>}
  {run.status==='running'&&<div className="conversation-progress" role="status"><div>{phases.map((label,i)=><span key={label} className={i<phaseIndex?'done':i===phaseIndex?'current':''}>{i<phaseIndex?<Check size={14}/>:i===phaseIndex?<LoaderCircle size={14} className="agent-spin"/>:<i/>}{label}</span>)}</div><p>{({plan:'正在理解你的经营目标，选择需要查询的数据。',tools:'正在查询经营账套，计算销量、库存或财务指标。',review:'正在整理建议，核查数字与引用。'} as any)[run.phase]}</p></div>}
  {run.forecasts?.length>0&&<>{run.allocation&&<p className="case-warning">全方案 {run.allocation.totalProducts} 种商品 · 本次分配 {money(run.allocation.totalAllocated_scaled)}（拟）{run.allocation.budget_scaled!==null?` · 总预算 ${money(run.allocation.budget_scaled)}（拟）`:''}。{run.allocation.rule}</p>}<ForecastCards rows={run.forecasts}/><button className="result-export" onClick={()=>exportForecast(run)}><Download size={15}/>导出全部测算明细</button></>}
  {conversation&&<><ProfitAnswer run={run}/><EvidenceCards run={run}/></>}
  {run.answer&&(run.forecasts?.length>0||conversation&&run.evidence.some((e:any)=>e.tool==='财务报表与对账'||e.tool==='经营商品排名')?<details className="full-answer"><summary>查看完整回答与经营建议</summary><AnswerText text={run.answer}/></details>:<AnswerText text={run.answer}/>)}
  {run.error&&<p className="case-warning">{run.error}</p>}
  {run.status==='cancelled'&&!run.answer&&<p>本次分析已停止，已完成的步骤保留在下方。</p>}
  {run.modelWarnings?.length>0&&<p className="case-warning">模型状态：{run.modelWarnings.join('；')}。数字仍取自账套。</p>}
  <details className="case-trace"><summary>查看执行轨迹与数据依据 · {run.trace.length} 步</summary><p><a href="https://www.mcm.edu.cn/html_cn/node/c74d72127066f510a5723a94b5323a26.html" target="_blank" rel="noreferrer">官方原表来源 ↗</a> · 原始销售2022年9月；演示账期2026年9月（拟）。采购、库存、费用与利润为（拟），保留原表行号供核验。</p><p>报告 {run.id} · {run.scope.caseId} · 配置 {run.configVersion}</p>{run.trace.map((t:any,i:number)=><section key={i}><b>{i+1}．{t.name}</b><small> · {t.mode} · {(t.durationMs/1000).toFixed(2)}秒</small><p>{t.output}</p>{t.details&&<p>工具：{t.details.intents.map((id:string)=>intentNames[id]??id).join('、')} · 商品：{t.details.productIds.join('、')||'全店范围'}</p>}</section>)}{run.evidence.map((e:any)=><section key={e.ref}><b>{e.ref} · {e.node} · {e.tool}</b><p>{e.text}</p></section>)}{run.checks?.map((c:any)=><p key={c.name}>{c.difference===0?'✓':'异常'} {c.name} · 差额 {c.difference}</p>)}{run.usage&&<p>模型用量：{run.usage.reduce((n:number,u:any)=>n+(u?.total_tokens??0),0)} tokens</p>}</details>
  {run.approval==='pending'&&<p className="case-warning">采购方案待后台审核；实际采购、入库与付款需要另行登记。</p>}{run.reviewNote&&<p>审核：{run.approval==='approved'?'通过':'退回'} · {run.reviewNote}</p>}
  {run.answer&&conversation&&<div className="answer-actions"><button onClick={copy}>{copied?<CheckCheck size={14}/>:<Copy size={14}/>} {copied?'已复制':'复制回答'}</button><a href={'/real-data?from='+run.scope.from+'&to='+run.scope.to}>回查经营台账 <ArrowUpRight size={14}/></a>{copyError&&<small role="status">{copyError}</small>}</div>}
 </div>
}
export default function CaseAssistant({from,to,products=[],planning=false,workspace=false,newConversation=0,promptRequest,onBusyChange}:{from:string,to:string,products?:any[],planning?:boolean,workspace?:boolean,newConversation?:number,promptRequest?:{text:string,id:number},onBusyChange?:(busy:boolean)=>void}){
 const preview=new URLSearchParams(location.search).get('preview')==='draft',storageKey='zhilian-domestic-case-session'+(preview?'-draft':'');
 const [question,setQuestion]=useState(''),[runs,setRuns]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState<any>(null),[recovering,setRecovering]=useState(true),[product,setProduct]=useState(products.find(p=>p.name==='小米椒(份)')?.id??products[0]?.id??''),[days,setDays]=useState(7),[uplift,setUplift]=useState(0);const credential=useRef<any>(null),stopped=useRef(false),live=useRef(true),submitting=useRef(false),inputRef=useRef<HTMLTextAreaElement>(null),scrollRef=useRef<HTMLDivElement>(null),nearBottom=useRef(true);
 const invalidScope=!from||!to||from>to||from<'2026-09-01'||to>'2026-09-30';
 function resetConversation(){if(submitting.current)return;credential.current=null;sessionStorage.removeItem(storageKey);setRuns([]);setQuestion('');setError('');inputRef.current?.focus()}
 useEffect(()=>{if(newConversation)resetConversation()},[newConversation]);
 useEffect(()=>{if(promptRequest){setQuestion(promptRequest.text);inputRef.current?.focus()}},[promptRequest]);
 useEffect(()=>{onBusyChange?.(busy)},[busy]);
 useEffect(()=>{const el=scrollRef.current;if(el&&nearBottom.current)el.scrollTop=el.scrollHeight},[runs]);
 useEffect(()=>{const el=inputRef.current;if(el){el.style.height='auto';el.style.height=Math.min(el.scrollHeight,150)+'px'}},[question]);
 useEffect(()=>{live.current=true;api('status').then(d=>{if(live.current)setStatus(d)}).catch(e=>{if(live.current)setError(e.message)});
 async function recover(){try{const saved=JSON.parse(sessionStorage.getItem(storageKey)??'null');if(saved){credential.current=saved;const d=await api('read?id='+saved.id,undefined,saved.accessKey);if(live.current)setRuns(d.session.runs)}}catch{credential.current=null;sessionStorage.removeItem(storageKey)}finally{if(live.current)setRecovering(false)}}recover();return()=>{live.current=false}},[]);
 const chosen=products.find(p=>p.id===product||p.name===product);
 async function execute(resume=false,override?:string){if(submitting.current||recovering||invalidScope)return;const q=override??(planning?`${chosen?.id??product}备货${days}天，需求增长${uplift}%：请根据销售和库存测算缺口、预算并给出行动建议。`:question);if(!resume&&!q.trim())return;submitting.current=true;nearBottom.current=true;setBusy(true);setError('');stopped.current=false;try{if(!credential.current){credential.current=await api('session',{preview});sessionStorage.setItem(storageKey,JSON.stringify(credential.current))}const {id,accessKey}=credential.current;let d=resume?await api('read?id='+id,undefined,accessKey):await api('run',{id,question:q,from,to},accessKey);if(!resume)setQuestion('');if(live.current)setRuns(d.session.runs);while(d.session.runs.at(-1)?.status==='running'&&!stopped.current&&live.current){d=await api('step',{id},accessKey);if(live.current)setRuns(d.session.runs);if(d.busy)await new Promise(r=>setTimeout(r,1000))}if(d.session.runs.at(-1)?.status==='failed')setError(d.session.runs.at(-1).error)}catch(e){setError((e as Error).message)}finally{submitting.current=false;if(live.current)setBusy(false)}}
 async function cancel(){stopped.current=true;try{if(credential.current){const d=await api('cancel',{id:credential.current.id},credential.current.accessKey);setRuns(d.session.runs)}}catch(e){setError((e as Error).message)}}
 if(workspace)return <section className="agent-conversation" aria-label="经营智能体对话">
 <div className="conversation-toolbar"><div className="conversation-model"><span className={status?.modelReady?'status-dot configured':'status-dot'}/>{status?status.modelReady?(status.provider==='Ark'?'豆包模型已配置':'模型已配置'):'账套规则模式':'正在检查模型'}<span className="model-divider"/>供销协同</div><button disabled={busy||recovering} onClick={resetConversation} title="开始新的会话"><MessageSquarePlus size={16}/><span>新会话</span></button></div>
 <div className="conversation-scroll" ref={scrollRef} onScroll={e=>{const el=e.currentTarget;nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<120}}>
 <div className="conversation-content">
 {recovering?<div className="conversation-restoring" role="status"><LoaderCircle size={18} className="agent-spin"/>正在恢复会话…</div>:!runs.length?<div className="conversation-welcome"><span className="welcome-agent-icon"><Bot size={32}/><i/></span><span className="welcome-eyebrow">智链销 · 经营智能体</span><h1>今天，想解决<br className="mobile-break"/>哪件经营事？</h1><p>从销售、库存到利润，一起把下一步算清楚。</p><div className="conversation-suggestions">{[
 {name:'明天怎么备货',desc:'结合销量、库存与预算测算',question:'小米椒明天备货，预算500元，需求增长三成',Icon:PackageSearch},
 {name:'哪些商品卖得好',desc:'查看畅销商品的销量与毛利',question:'销量最高的5种商品分别是什么？列出销售数量、销售额和毛利。',Icon:TrendingUp},
 {name:'利润和现金对账',desc:'解释利润、库存与现金的关系',question:'净利润和现金为什么不同？请逐项对账。',Icon:Wallet},
 {name:'采购与售后回查',desc:'查看单据、供应商与退款记录',question:'有多少采购单、供应商、履约和售后记录？请给出核查依据。',Icon:ReceiptText}
 ].map(({name,desc,question:q,Icon})=><button key={name} onClick={()=>{setQuestion(q);inputRef.current?.focus()}}><span><Icon size={20}/><ArrowUpRight size={14}/></span><b>{name}</b><small>{desc}</small></button>)}</div><p className="welcome-footnote">建议先说清商品、时间和预算，结果可以追溯到经营台账。</p></div>:runs.map(run=><div className="conversation-turn" key={run.id}><div className="conversation-user"><span>你</span><div>{run.question}</div></div><div className="conversation-agent"><span className="agent-avatar"><Bot size={18}/></span><div className="agent-response"><div className="agent-response-name">智链销 <small>经营分析</small></div><RunDetail run={run} conversation/></div></div></div>)}
 </div></div>
 <div className="conversation-compose"><div className="compose-inner">
 {preview&&<p className="compose-notice">当前为已保存草稿试运行。</p>}
 {invalidScope&&<p className="compose-error" role="alert">请选择2026年9月内的有效账期，开始日期不能晚于结束日期。</p>}
 {error&&<p className="compose-error" role="alert">{error}</p>}
 {!busy&&runs.at(-1)?.status==='failed'&&<button className="resume-task" onClick={()=>execute(false,runs.at(-1).question)}>重新分析这个问题</button>}
 {!busy&&runs.at(-1)?.status==='running'&&<button className="resume-task" onClick={()=>execute(true)}>继续上次未完成的分析</button>}
 <form className={'agent-composer '+(busy?'is-working':'')} onSubmit={e=>{e.preventDefault();execute()}}><label className="sr-only" htmlFor="agent-question">输入经营问题</label><textarea id="agent-question" ref={inputRef} value={question} maxLength={2000} rows={2} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&e.nativeEvent.keyCode!==229){e.preventDefault();execute()}}} placeholder="问销量、查利润、算备货…直接说说你的问题"/><div className="agent-composer-bottom"><span><ReceiptText size={14}/>已关联经营账套 <small>· 人民币</small></span>{busy?<button type="button" className="agent-send" aria-label="停止本次分析" onClick={cancel}><Square size={16}/></button>:<button className="agent-send" disabled={recovering||invalidScope||!question.trim()} aria-label="发送经营问题"><ArrowUp size={20}/></button>}</div></form>
 <div className="compose-caption"><span>演示账期2026年9月（拟） · 拟定业务标（拟）</span><span className="keyboard-hint">回车发送 · 换行按 Shift + 回车</span></div>
 </div></div></section>;
 return <section className="ledger-card case-assistant"><div className="case-assistant-heading"><div><span className="case-eyebrow">经营智能体</span><h2>{planning?'用当前账套测算备货':'说出经营问题，查看分析与行动方案。'}</h2><p>先理解目标与预算，再查数据、计算和审核建议；关键数字可回查官方原表行号，拟定业务标“（拟）”。</p></div><div className={'case-model-status '+(status?.modelReady?'ready':'')}><i/>{status?status.modelReady?(status.provider==='Ark'?'豆包已接入':'模型已接入'):'离线规则模式':'检查连接…'}<small>同一账套 · 人民币 · 配置 v{status?.version??'—'}</small></div></div>{preview&&<p className="case-warning">已保存草稿试运行；通过后可在编辑台发布。</p>}
 {planning?<div className="case-planning"><label>商品名称或编码<input list="case-products" aria-label="备货商品" value={product} onChange={e=>setProduct(e.target.value)}/><datalist id="case-products">{products.filter(p=>p.stocked).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</datalist></label><label>预测天数<input type="number" min={1} max={60} value={days} onChange={e=>setDays(Number(e.target.value))}/></label><label>需求增幅（拟）%<input type="number" min={-100} max={300} value={uplift} onChange={e=>setUplift(Number(e.target.value))}/></label><p>{chosen?`${chosen.name} · ${from}至${to}正向销量${chosen.sold} · 截至${to}库存${chosen.stock}（拟）`:'请选择账套中的实物商品。'}<br/>销量和库存直接读取账套；安全库存、包装及增幅为测算假设（拟）。</p><button className="ledger-primary" disabled={busy||!chosen?.stocked||!Number.isInteger(days)||days<1||days>60||!Number.isFinite(uplift)||uplift<-100||uplift>300} onClick={()=>execute()}>生成并保存备货方案</button></div>:<><div className="case-prompts">{['小米椒明天备货，预算500元，需求增长三成','畅销商品有哪些？销量和毛利都看看。','净利润和现金为什么不同？','采购有哪些供应商？','有多少履约和售后记录？'].map(q=><button key={q} disabled={busy} onClick={()=>setQuestion(q)}>{q}</button>)}</div><form onSubmit={e=>{e.preventDefault();execute()}}><textarea aria-label="输入完整账套经营问题" value={question} maxLength={2000} rows={3} onChange={e=>setQuestion(e.target.value)} placeholder="例如：小米椒明天备货，预算500元，销量下降20%"/><div className="case-compose-actions"><small>当前查询账期 {from} 至 {to}（拟）</small><button className="ledger-primary" disabled={busy||!question.trim()}>分析并生成方案</button></div></form></>}
 {error&&<div className="ledger-alert" role="alert">{error}</div>}{busy&&<button onClick={cancel}>停止本次分析</button>}{!busy&&runs.at(-1)?.status==='failed'&&<button onClick={()=>execute(false,runs.at(-1).question)}>重试本次任务</button>}{!busy&&runs.at(-1)?.status==='running'&&<button onClick={()=>execute(true)}>继续未完成任务</button>}{runs.length>0&&<div className="case-history"><div className="case-history-heading"><h3>分析记录 · {runs.length} 次</h3><button disabled={busy} onClick={()=>{credential.current=null;sessionStorage.removeItem(storageKey);setRuns([])}}>新建会话</button></div>{[...runs].reverse().map(run=><RunDetail key={run.id} run={run}/>)}</div>}
 </section>
}
export function CaseRuns({kind='all'}:{kind?:string}){const [runs,setRuns]=useState<any[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false);async function load(){try{const d=await api('runs');setRuns(d.runs)}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[]);const rows=runs.filter(r=>kind==='all'||kind==='forecast'&&r.forecasts?.length||kind==='approval'&&r.approval!=='unneeded'),current=rows.find(r=>r.id===selected)??rows[0];async function review(status:string){setBusy(true);try{await api('review',{id:current.sessionId,runId:current.id,revision:current.revision,status,note});setNote('');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <section className="admin-section"><div className="section-title"><div><h1>{kind==='forecast'?'备货测算记录':kind==='approval'?'采购方案审核':'智能体咨询与执行'}</h1><p>当前完整账套的实际执行记录，保存账期、版本、工具依据和备货方案。</p></div><button onClick={load}>刷新</button></div>{error&&<p role="alert">{error}</p>}<div className="case-admin-grid"><div>{rows.length?rows.map(r=><button className={'case-record '+(current?.id===r.id?'selected':'')} key={r.id} onClick={()=>setSelected(r.id)}><b>{r.question}</b><small>{new Date(r.createdAt).toLocaleString('zh-CN')} · {({completed:'已完成',running:'运行中',failed:'失败',cancelled:'已停止'} as any)[r.status]} {r.preview?' · 草稿':''}</small><small>{r.scope.from}至{r.scope.to}</small></button>):<p>当前账套暂无此类执行记录。<a href="/scenario">打开备货测算</a></p>}</div><div>{current&&<><RunDetail run={current}/>{current.approval==='pending'&&<div className="case-review"><label>审核意见<textarea rows={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="核查库存、预算与交期后填写意见"/></label><button disabled={busy||!note.trim()} onClick={()=>review('approved')}>审核通过</button><button disabled={busy||!note.trim()} onClick={()=>review('rejected')}>退回修改</button><p>审核保存方案意见。实际采购、入库与付款应按业务单据另行登记。</p></div>}</>}</div></div></section>}

