import {useEffect,useState} from 'react';
const money=(n:number|null)=>n===null?'缺数据':(n/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
async function get(path:string){const r=await fetch('/api/v2/'+path),d=await r.json();if(!r.ok)throw Error(d.error);return d}
export default function FinancialReports(){
 const [companies,setCompanies]=useState<any[]>([]),[tenant,setTenant]=useState(''),[data,setData]=useState<any>(null),[from,setFrom]=useState(''),[to,setTo]=useState(''),[error,setError]=useState('');
 useEffect(()=>{get('companies').then(d=>{setCompanies(d.companies);const saved=sessionStorage.getItem('zhilian-admin-company');setTenant((d.companies.find((c:any)=>c.id===saved)??[...d.companies].sort((a:any,b:any)=>b.createdAt.localeCompare(a.createdAt))[0])?.id??'')}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{let active=true;setData(null);setError('');if(tenant)get('history-finance?'+new URLSearchParams({tenant,from,to})).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[tenant,from,to]);
 const s=data?.summary;
 return <section className="reports-page"><div className="page-heading"><div><small>ENTERPRISE DATA / 企业经营数据</small><h2>销售与财务概览</h2><p>由本企业销售数据库计算；原始来源未经核验，缺少的账目不估填。</p></div></div>
 <div className="report-filters"><label>企业<select value={tenant} onChange={e=>{setTenant(e.target.value);sessionStorage.setItem('zhilian-admin-company',e.target.value)}}>{!companies.length&&<option value="">尚未建立企业</option>}{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>从<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>至<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={()=>{setFrom('');setTo('')}}>全部日期</button></div>
 {error&&<div className="notice" role="alert">{error}</div>}
 {!tenant&&!error&&<div className="empty-box">请先在企业数据库导入你的商品和销售记录。</div>}
 {tenant&&!data&&!error&&<p role="status">正在读取企业数据库…</p>}
 {data&&<><div className="notice">用户导入数据 · 数据版本 {data.revision} · {s.first_date??'无记录'} 至 {s.last_date??'无记录'} · {s.days} 个有记录日期。金额沿用原表单位，币种未声明；没有记录的日期不当作零销售。</div>
 <div className="metric-grid">{[['销售净额',money(s.net_cents),'正数销售与负数冲销合计，不等同于实收'],['正向销售额',money(s.positive_cents),'非负数量记录金额合计'],['冲销 / 退货候选',money(s.reversal_cents),`${s.reversal_records??0} 条负数销售，退款状态未核验`],['销售毛利',money(s.gross_profit_cents),s.missing_costs?`${s.missing_costs} 条记录缺少成本`:'销售额减销售成本，未扣其他费用']].map(([label,value,note])=><div className="metric" key={label}><small>{label}</small><strong>{value}</strong><p>{note}</p></div>)}</div>
 <div className="report-grid"><div className="report-card"><h3>按月销售</h3><div className="finance-month-bars">{data.monthly.map((r:any)=><div className="finance-month-bar" key={r.month}><b>{money(r.net_cents)}</b><i style={{height:Math.max(3,r.net_cents/Math.max(1,...data.monthly.map((m:any)=>m.net_cents))*110)}}/><span>{r.month}</span></div>)}</div><div className="table-scroll"><table><thead><tr><th>月份</th><th>销售记录</th><th>销售净额</th></tr></thead><tbody>{data.monthly.map((r:any)=><tr key={r.month}><td>{r.month}</td><td>{r.records}</td><td>{money(r.net_cents)}</td></tr>)}</tbody></table></div></div><div className="report-card"><h3>财务数据完整度</h3>{[['销售记录',s.records+' 条'],['销售成本',s.cost_cents===null?'未提供完整成本':money(s.cost_cents)],['实际收款 / 现金流','未接入收付款流水'],['净利润 / 纳税金额','未接入费用与税务数据'],['资产负债 / 应收应付','未接入会计余额与往来账'],['具备上架基础数据的商品',data.eligible+' 个（仍需确认上架）']].map(([label,value])=><div className="review-stat" key={label}><span>{label}</span><b>{value}</b></div>)}</div></div>
 <div className="report-card"><h3>品类销售</h3>{data.categories?.map((r:any)=><div className="review-stat" key={r.category}><span>{r.category} · {r.records} 条</span><b>{money(r.net_cents)}</b></div>)}</div><div className="report-card"><h3>销售数量（按单位分别统计）</h3>{data.units.map((u:any)=><div className="review-stat" key={u.unit}><span>{u.unit}</span><b>{Number(u.quantity).toLocaleString('zh-CN',{maximumFractionDigits:4})}</b></div>)}</div>
 <div className="report-card"><h3>商品销售排名</h3><p>显示销售净额前 100 个商品及单位组合；名称缺失时沿用原始商品编码。</p><div className="table-scroll"><table><thead><tr><th>商品 / 编码</th><th>单位</th><th>记录数</th><th>净销售数量</th><th>销售净额</th></tr></thead><tbody>{data.products.map((p:any)=><tr key={p.id}><td>{p.name}<small className="cell-sub">{p.source_code??p.id}</small></td><td>{p.unit??'未声明'}</td><td>{p.records}</td><td>{Number(p.quantity).toLocaleString('zh-CN',{maximumFractionDigits:4})}</td><td>{money(p.net_cents)}</td></tr>)}</tbody></table></div></div>
 <div className="notice"><b>当前口径与缺口</b><ul>{data.limitations.map((t:string)=><li key={t}>{t}</li>)}</ul>这是销售分析与财务数据概览，尚不是完整会计报表。企业库存 {data.counts.inventory} 条，供应商 {data.counts.suppliers} 条，采购单 {data.counts.purchase_orders} 条。</div></>}
 </section>
}
