import {useState} from 'react';
import {ArrowDownToLine,Check,ChevronRight,FileText,PackageCheck,Target} from 'lucide-react';
import type {ProfitBaseline} from '../lib/profit-forecast';
import type {GoalReport,GoalConditions} from '../lib/goal-planner';
import {downloadChineseReport,downloadDecisionExcel} from './decision-download';
import './goal-plan-view.css';
const money=(n:number)=>'¥'+(n/10000).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:4});
const kg=(n:number)=>(n/1000).toLocaleString('zh-CN',{maximumFractionDigits:3});
export default function GoalPlanView({baseline,report,onAdopt}:{baseline:ProfitBaseline;report:GoalReport;onAdopt?:(c:GoalConditions)=>void}){
 const [selection,setSelection]=useState(''),[exporting,setExporting]=useState(false),[error,setError]=useState(''),[showAll,setShowAll]=useState(false),[product,setProduct]=useState('');
 const chosen=report.plans.find(p=>p.id===selection)??report.plans.find(p=>p.id===report.recommendedId)!;
 const line=chosen.lines.find(l=>l.id===product)??chosen.lines[0];
 async function excel(){setExporting(true);setError('');try{await downloadDecisionExcel(baseline,report,chosen.id)}catch(e){setError((e as Error).message)}finally{setExporting(false)}}
 return <section className="goal-view" aria-label="目标经营智能体方案">
  <div className="goal-conclusion"><span><Target size={15}/>智能体建议（拟）</span><h3>{report.plans.find(p=>p.id===report.recommendedId)!.name}</h3><p>未来{chosen.horizon.days}天 · {chosen.horizon.from}至{chosen.horizon.to}（拟）<br/>目标净利润 {money(report.conditions.inputs.target_scaled)}（拟）</p><p>{report.summary}</p></div>
  <div className="goal-plan-cards">{report.plans.map(p=><button key={p.id} className={chosen.id===p.id?'selected':''} aria-pressed={chosen.id===p.id} onClick={()=>setSelection(p.id)}><span>{p.name}{p.id===report.recommendedId&&<small>建议评估</small>}</span><strong>{money(p.profit_scaled)}</strong><small>净利润（拟） · {p.targetMet?'按条件达到目标':'目标尚差'+money(p.gap_scaled)}</small><p>销量变化 {p.conditions.inputs.quantityChange}%<br/>降损改善 {p.conditions.inputs.lossReduction}%<br/>需求覆盖 {(p.coverage*100).toFixed(1)}%</p><i>{chosen.id===p.id?<><Check size={12}/>正在查看</>:<>查看方案<ChevronRight size={12}/></>}</i></button>)}</div>
  <div className="goal-selected-heading"><b><PackageCheck size={16}/>{chosen.name} · 供销利润联动（拟）</b>{onAdopt&&<button onClick={()=>onAdopt(chosen.conditions)}>带入条件</button>}</div>
  <p className="goal-explanation">所选条件（拟）：销量变化{chosen.conditions.inputs.quantityChange}%，售价变化{chosen.conditions.inputs.priceChange}%，单位成本变化{chosen.conditions.inputs.costChange}%，降损改善{chosen.conditions.inputs.lossReduction}%，其他费用变化{chosen.conditions.inputs.fixedChange}%。</p>
  <div className="goal-metrics">{[['累计采购支出',chosen.purchase_scaled],['可支持销售净额',chosen.revenue_scaled],['联动净利润',chosen.profit_scaled],['目标缺口',chosen.gap_scaled]].map(([k,v])=><div key={k as string}><small>{k}（拟）</small><b>{money(v as number)}</b></div>)}</div>
  <p className={chosen.budgetLimited?'goal-constraint limited':'goal-constraint'}>预算{report.conditions.budget_scaled===null?'未设累计上限':money(report.conditions.budget_scaled)}（拟），采购不超过上限。预计需求 {kg(chosen.demandGrams)} 千克，可支持正向销售 {kg(chosen.soldGrams)} 千克，未满足 {kg(chosen.shortageGrams)} 千克（拟）。<br/>预算压缩会改变商品分配和报损余量，采购更多不一定利润更高。</p>
  <div className="goal-financial-lines">{[['销售净额',chosen.revenue_scaled],['− 净售商品成本',chosen.cost_scaled],['− 清理及损耗成本',chosen.loss_scaled],['− 其他费用',chosen.fixed_scaled],['＝ 净利润',chosen.profit_scaled]].map(([k,v])=><div key={k as string}><span>{k}（拟）</span><b>{money(v as number)}</b></div>)}</div><p className="goal-explanation">采购支出已分解到销售和报损成本，利润不再重复扣除采购。未来可售库存按0计，分日到货，未售生鲜按当天清理（拟）。</p>
  <details className="goal-details"><summary>查看商品备货与分日明细 · {chosen.lines.length}种</summary><p>商品、价格、账面库存与原表行号来自同一账套。销量变化与降损均为待验证条件（拟）。</p><div className="goal-table"><table><thead><tr><th>商品</th><th>账面/未来可售 千克（拟）</th><th>采购 千克（拟）</th><th>可支持售出 千克（拟）</th><th>未满足 千克（拟）</th><th>采购预算（拟）</th></tr></thead><tbody>{(showAll?chosen.lines:chosen.lines.slice(0,8)).map(l=><tr key={l.id}><td><a href={'/real-data?tab=products&q='+encodeURIComponent(l.id)}>{l.name}</a><small>{l.id}</small></td><td>{l.stock} / {l.availableStock}</td><td>{kg(l.purchaseGrams)}</td><td>{kg(l.soldGrams)}</td><td>{kg(l.shortageGrams)}</td><td>{money(l.purchase_scaled)}</td></tr>)}</tbody></table></div>{chosen.lines.length>8&&<button className="goal-text-button" onClick={()=>setShowAll(!showAll)}>{showAll?'收起商品':'显示全部'+chosen.lines.length+'种商品'}</button>}
  <label className="goal-product-select">查看分日到货<select value={line?.id??''} onChange={e=>setProduct(e.target.value)}>{chosen.lines.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>{line&&<><p>方法：{line.method}。包装 {line.packSize} 千克（拟），参考损耗率经改善后 {line.lossPercent.toFixed(2)}%（拟）。原表 {line.sourceRowCount} 行，示例 {line.sourceRows.join('、')}。</p><div className="goal-table"><table><thead><tr><th>到货日期（拟）</th><th>采购 千克</th><th>可支持售出 千克</th><th>报损 千克</th><th>销售净额</th><th>采购支出</th></tr></thead><tbody>{line.daily.map(d=><tr key={d.date}><td>{d.date}</td><td>{kg(d.purchaseGrams)}</td><td>{kg(d.soldGrams)}</td><td>{kg(d.discardGrams)}</td><td>{money(d.revenue_scaled)}</td><td>{money(d.purchase_scaled)}</td></tr>)}</tbody></table></div></>}
  </details>
  <details className="goal-details"><summary>为什么选这个方案 · 规划步骤与对账</summary><ol className="goal-steps">{report.steps.map(s=><li key={s.name}><b>{s.name}</b><p>{s.detail}</p></li>)}</ol><p>搜索范围：销量在当前条件上额外增加最多 {report.search.maxAdditionalQuantityPercent} 个百分点，降损改善至少 {report.search.lossImprovementPercent}%（拟）；比较了 {report.search.tested} 次方案。优先选择达到目标且需要较少销量增长的方案；都未达到时列出利润较高方案及缺口。未证明全局最优。</p>{chosen.checks.map(c=><p key={c.name}>{c.name}：差额 {c.difference}</p>)}</details>
  <div className="goal-next"><b>下一步需要验证</b><ul>{report.actions.map(a=><li key={a}>{a}</li>)}</ul></div>
  <div className="goal-export-actions"><button onClick={()=>downloadChineseReport(baseline,report,chosen.id)}><FileText size={15}/>下载中文报告</button><button disabled={exporting} onClick={excel}><ArrowDownToLine size={15}/>{exporting?'正在生成Excel…':'导出方案与流水 Excel'}</button></div>{error&&<p className="goal-export-error" role="alert">{error}</p>}
  <details className="goal-details"><summary>原费用情景与预测边界</summary><p>历史净利润 {money(report.comparison.historicalProfit_scaled)}（拟）。按历史月度费用整体变化、未检查供货的情景值为 {money(report.comparison.unconstrainedProfit_scaled)}（拟），口径与上方逐商品分日计划不同。联动结果以实际测算采购能支持的数量为限。</p>{report.assumptions.map(a=><p key={a}>{a}</p>)}</details>
 </section>;
}
