import {useEffect,useMemo,useState} from 'react';
import {ArrowDownToLine,ArrowRight,ArrowUpRight,BarChart3,Check,ChevronRight,Layers,MessageSquare,RotateCcw,Save,ShieldCheck,Sparkles,Target,TrendingUp} from 'lucide-react';
import {predictProfit,profitScenarios,profitDefaults,type ProfitBaseline,type ProfitInputs} from '../lib/profit-forecast';
import './growth-workbench.css';
const money=(n:number)=>'¥'+(n/10000).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const preciseMoney=(n:number)=>'¥'+(n/10000).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:4});
const rate=(n:number|null)=>n===null?'无可比基数':(n>0?'+':'')+n.toFixed(1)+'%';
const storageKey='zhilian-profit-plans-v1';
type Saved={id:string;at:string;caseId:string;baselineRevenue:number;parameters:ProfitInputs;profit:number};
function readSaved():Saved[]{try{const v=JSON.parse(localStorage.getItem(storageKey)??'[]');return Array.isArray(v)?v.filter(x=>x?.caseId&&x?.parameters&&Number.isFinite(x.profit)).slice(0,8):[]}catch{return []}}
function ask(text:string){return '/?prompt='+encodeURIComponent(text)}
function Trend({data}:{data:ProfitBaseline['daily']}){
 const width=720,height=210,pad=40,max=Math.max(1,...data.map(d=>d.revenue_scaled));
 const x=(i:number)=>pad+i*(width-pad*2)/Math.max(1,data.length-1),y=(v:number)=>height-pad-v/max*(height-pad*2);
 const path=data.map((d,i)=>(i?'L':'M')+x(i)+','+y(d.revenue_scaled)).join(' ');
 return <div className="growth-trend"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="原始九月每日销售净额趋势，具体金额可展开图表下方明细"><defs><linearGradient id="growth-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#59a885" stopOpacity=".22"/><stop offset="100%" stopColor="#59a885" stopOpacity="0"/></linearGradient></defs>{[0,.5,1].map(t=><g key={t}><line x1={pad} x2={width-pad} y1={y(max*t)} y2={y(max*t)} stroke="#e6ece7" strokeDasharray="4 4"/><text x={pad-8} y={y(max*t)+4} textAnchor="end" fill="#809287" fontSize="10">{Math.round(max*t/10000)}</text></g>)}<path d={path+` L ${x(data.length-1)},${height-pad} L ${pad},${height-pad} Z`} fill="url(#growth-area)"/><path d={path} fill="none" stroke="#2d8662" strokeWidth="2.5" strokeLinejoin="round"/>{data.map((d,i)=><circle key={d.date} cx={x(i)} cy={y(d.revenue_scaled)} r="3" fill="#2d8662"><title>{d.originalDate}：{money(d.revenue_scaled)}</title></circle>)}{[0,Math.floor((data.length-1)/2),data.length-1].map(i=><text key={i} x={x(i)} y={height-12} textAnchor="middle" fill="#809287" fontSize="10">{data[i].originalDate.slice(5).replace('-','/')}</text>)}<text x="8" y="16" fill="#809287" fontSize="10">元</text></svg></div>
}
export default function GrowthWorkbench(){
 const [baseline,setBaseline]=useState<ProfitBaseline|null>(null),[error,setError]=useState(''),[inputs,setInputs]=useState<ProfitInputs>({...profitDefaults}),[saved,setSaved]=useState(readSaved),[notice,setNotice]=useState(''),[ranking,setRanking]=useState<'contribution'|'decline'>('contribution');
 useEffect(()=>{fetch('/data/profit-baseline.json').then(r=>{if(!r.ok)throw Error('利润分析基线暂未加载，请重新构建或刷新页面。');return r.json()}).then(setBaseline).catch(e=>setError(e.message))},[]);
 const forecast=useMemo(()=>baseline?predictProfit(baseline,inputs):null,[baseline,inputs]),scenarios=useMemo(()=>baseline?profitScenarios(baseline,inputs):[],[baseline,inputs]);
 const products=useMemo(()=>!baseline?[]:ranking==='contribution'?[...baseline.products].sort((a,b)=>b.revenue_scaled-a.revenue_scaled).slice(0,5):baseline.products.filter(p=>p.previous_scaled>0&&p.delta_scaled<0).sort((a,b)=>a.delta_scaled-b.delta_scaled).slice(0,5),[baseline,ranking]);
 function update(key:keyof ProfitInputs,value:number){setInputs(p=>({...p,[key]:value}));setNotice('')}
 function save(){if(!baseline||!forecast)return;const row={id:crypto.randomUUID(),at:new Date().toISOString(),caseId:baseline.caseId,baselineRevenue:baseline.revenue_scaled,parameters:{...inputs},profit:forecast.profit_scaled};const next=[row,...saved].slice(0,8);try{localStorage.setItem(storageKey,JSON.stringify(next));setSaved(next);setNotice('演示方案已保存在此设备，未写入经营流水。')}catch{setNotice('此浏览器无法保存，请下载测算报告。')}}
 function exportReport(){if(!baseline||!forecast)return;const url=URL.createObjectURL(new Blob([JSON.stringify({title:'智链销利润情景测算（拟）',baseline,forecast,scenarios},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='利润预测与目标测算（拟）.json';a.click();URL.revokeObjectURL(url)}
 return <div className="growth-app"><header className="growth-header"><a className="growth-brand" href="/"><span><Layers size={21}/></span><b>智链销</b><small>经营增长工作台</small></a><nav aria-label="增长工作台导航"><a href="/"><MessageSquare size={16}/>经营对话</a><a href="/real-data">查看台账<ArrowUpRight size={15}/></a></nav></header><main>
 <section className="growth-hero"><div><span className="growth-kicker"><Sparkles size={14}/>利润预测 Skill · 演示版</span><h1>找到增长点，<br className="growth-mobile-break"/>算清下一步。</h1><p>从可追溯的历史销售出发，比较经营趋势，测算利润目标。</p><a className="growth-start" href="#profit-plan"><Target size={15}/>开始利润测算<ArrowRight size={15}/></a></div><div className="growth-hero-note"><ShieldCheck size={21}/><div><b>历史有出处 · 目标可复算</b><span>原始销售 2022年9月<br/>演示账期 2026年9月（拟）</span></div></div></section>
 {!baseline?<div className="growth-card growth-loading" role="status">{error||'正在读取同源销售与利润基线…'}</div>:<>
 <div className="growth-source-strip"><ShieldCheck size={15}/><span>销售数量、单价来自公开原表；净额由销量×单价演算。成本、费用与未来结果（拟）。</span><a href={baseline.source.url} target="_blank" rel="noreferrer">核验来源<ArrowUpRight size={13}/></a></div>
 <section className="growth-kpis" aria-label="历史经营基线">{[['销售净额',money(baseline.revenue_scaled),'原始数量 × 售价'],['正向销量',(baseline.soldGrams/1000).toLocaleString('zh-CN'),'原表数量单位：千克'],['销售明细',baseline.rowCount.toLocaleString('zh-CN')+' 笔',baseline.productCount+' 种商品 · '+baseline.days+' 天'],['基线净利润（拟）',money(baseline.profit_scaled),'销售净额 − 成本 − 全部费用']].map(([label,value,foot])=><article key={label}><small>{label}</small><strong>{value}</strong><span>{foot}</span></article>)}</section>
 <div className="growth-history-grid"><section className="growth-card"><div className="growth-card-heading"><div><span className="growth-section-number">01 / 看清历史</span><h2>销售变化，直接看原始数据</h2></div><span className="growth-pill">原始日期</span></div><Trend data={baseline.daily}/>{baseline.comparison&&<div className="growth-comparison"><div><small>末7天相比前7天 · 等长比较</small><b className={baseline.comparison.delta_scaled>=0?'positive':'negative'}>{rate(baseline.comparison.growth)}</b></div><p>9月24—30日 {money(baseline.comparison.recent_scaled)}<br/>9月17—23日 {money(baseline.comparison.previous_scaled)}</p></div>}<details className="growth-details"><summary>查看每日金额与原始日期</summary><div className="growth-table-scroll"><table><thead><tr><th>原始日期</th><th>演示日期（拟）</th><th>销售净额</th><th>明细数</th></tr></thead><tbody>{baseline.daily.map(d=><tr key={d.date}><td>{d.originalDate}</td><td>{d.date}</td><td>{money(d.revenue_scaled)}</td><td>{d.rows}</td></tr>)}</tbody></table></div></details></section>
 <section className="growth-card growth-opportunities"><div className="growth-card-heading"><div><span className="growth-section-number">02 / 找到切入点</span><h2>优先分析哪些商品</h2></div><TrendingUp size={21}/></div><div className="growth-tabs" aria-label="商品分析方向"><button aria-pressed={ranking==='contribution'} className={ranking==='contribution'?'active':''} onClick={()=>setRanking('contribution')}>销售贡献</button><button aria-pressed={ranking==='decline'} className={ranking==='decline'?'active':''} onClick={()=>setRanking('decline')}>销售回落</button></div><p className="growth-card-caption">{ranking==='contribution'?'按全月销售净额排序，检查重点商品的供应与盈利结构。':'按末7天较前7天减少的销售额排序，先查价格、供货和需求。'}</p><div className="growth-product-list">{products.map((p,i)=><a key={p.id} href={ask(`${p.name}（编码${p.id}）9月销售和毛利情况如何？请展示依据。`)}><span className="growth-product-rank">{String(i+1).padStart(2,'0')}</span><div><b>{p.name}</b><small>{p.category} · 周变化 {rate(p.growth)}</small></div><strong>{money(ranking==='contribution'?p.revenue_scaled:p.delta_scaled)}<ChevronRight size={14}/></strong></a>)}</div><p className="growth-card-caption">变化揭示分析线索；数据不能单独证明缺货原因、促销效果或未来必然增长。</p></section></div>
 <section id="profit-plan" className="growth-planner"><div className="growth-planner-title"><div><span className="growth-section-number">03 / 测算目标</span><h2>利润怎样变，差距在哪里？</h2><p>先设置经营条件，再比较未来周期的结果。所有预测与目标（拟）。</p></div><span className="growth-skill-badge"><BarChart3 size={15}/>共享计算引擎</span></div><div className="growth-plan-grid"><section className="growth-controls"><div className="growth-controls-title"><b><Target size={17}/>我的经营目标（拟）</b><button onClick={()=>{setInputs({...profitDefaults});setNotice('')}}><RotateCcw size={13}/>重置</button></div><div className="growth-goal-fields"><label>测算周期<select value={inputs.days} onChange={e=>update('days',Number(e.target.value))}><option value={7}>未来7天</option><option value={14}>未来14天</option><option value={30}>未来30天</option></select></label><label>目标净利润 · 元<input type="number" min="0" max="10000000" step="100" value={inputs.target_scaled/10000} onChange={e=>{const value=Number(e.target.value);if(Number.isFinite(value)&&value>=0&&value<=10000000)update('target_scaled',Math.round(value*10000))}}/></label></div>{([{key:'quantityChange',name:'销量变化',min:-50,max:100,caption:'销量增加会同步增加销售成本和损耗费用。'},{key:'priceChange',name:'售价变化',min:-20,max:20,caption:'保持商品结构不变；价格对需求的影响未估计。'},{key:'lossReduction',name:'损耗费用降低',min:0,max:100,caption:'费用相对降低，不是损耗率降低同等百分点。'}] as const).map(v=><label className="growth-slider" key={v.key}><span><b>{v.name}（拟）</b><strong>{v.key==='lossReduction'?inputs[v.key]+'%':rate(inputs[v.key])}</strong></span><input aria-label={v.name+'（拟）'} type="range" min={v.min} max={v.max} step="1" value={inputs[v.key]} onChange={e=>update(v.key,Number(e.target.value))}/><small>{v.caption}</small></label>)}<details className="growth-details"><summary>更多条件：成本与其他费用</summary>{([{key:'costChange',name:'单位成本变化',min:-20,max:50},{key:'fixedChange',name:'其他费用变化',min:-50,max:100}] as const).map(v=><label className="growth-slider" key={v.key}><span><b>{v.name}（拟）</b><strong>{rate(inputs[v.key])}</strong></span><input aria-label={v.name+'（拟）'} type="range" min={v.min} max={v.max} step="1" value={inputs[v.key]} onChange={e=>update(v.key,Number(e.target.value))}/></label>)}</details><button className="growth-save" onClick={save}><Save size={16}/>保存演示方案</button><small className="growth-local-note">仅保存在此设备，不作为已发生的经营流水。</small>{notice&&<p className="growth-save-notice" role="status"><Check size={14}/>{notice}</p>}</section>
 {forecast&&<section className="growth-result" aria-live="polite"><div className="growth-result-top"><span>未来{inputs.days}天净利润（拟）</span><b>{money(forecast.profit_scaled)}</b><p>{forecast.horizon.from} — {forecast.horizon.to}（拟）</p><div className="growth-result-change">较同天数基准情景 <strong>{forecast.delta_scaled>=0?'+':''}{money(forecast.delta_scaled)}</strong></div></div><div className="growth-target-status"><span><Target size={16}/>{forecast.targetMet?'按当前假设达到目标（拟）':'距目标还差（拟）'}</span><b>{forecast.targetMet?'条件满足':money(forecast.gap_scaled)}</b></div><div className="growth-result-lines">{[['预测销售净额',forecast.revenue_scaled],['− 销售成本（拟）',forecast.cost_scaled],['− 损耗费用（拟）',forecast.loss_scaled],['− 其他费用（拟）',forecast.fixed_scaled],['＝ 净利润（拟）',forecast.profit_scaled]].map(([label,value])=><div key={label as string}><span>{label}</span><b>{preciseMoney(value as number)}</b></div>)}</div><details className="growth-details" open><summary>利润改善由哪些条件贡献（拟）</summary><div className="growth-bridge">{forecast.bridge.map(v=><div key={v.name}><span>{v.name}</span><b className={v.amount_scaled<0?'negative':'positive'}>{v.amount_scaled>0?'+':''}{preciseMoney(v.amount_scaled)}</b></div>)}</div></details><p className="growth-target-equation">{forecast.requiredQuantityChange===null?'当前单位贡献不为正，仅增加销量不能实现正向利润目标。':`保持其他条件不变，达到目标所需销量变化约 ${forecast.requiredQuantityChange.toFixed(1)}%（拟）。${forecast.requiredQuantityChange>100||forecast.requiredQuantityChange< -50?'超出本演示的销量变化范围，应重新评估目标或成本结构。':'这是代数条件，不代表需求能够实现。'}`}</p></section>}
 </div><section className="growth-scenarios"><div className="growth-scenario-heading"><h3>换一组条件，结果会怎样？</h3><span>敏感性情景（拟） · 不表示发生概率</span></div><div>{scenarios.map((s,i)=><article key={s.name} className={i===1?'current':''}><small>{s.name}</small><strong>{money(s.profit_scaled)}</strong><p>销量 {rate(s.parameters.quantityChange)} · 售价 {rate(s.parameters.priceChange)}<br/>单位成本 {rate(s.parameters.costChange)} · 损耗改善 {s.parameters.lossReduction}%</p></article>)}</div></section></section>
 <section className="growth-bottom-grid"><section className="growth-card"><div className="growth-card-heading"><h2>把测算交给经营智能体</h2><MessageSquare size={21}/></div><p>在对话里调用利润预测 Skill，查看计算依据，再继续分析商品与备货。</p><a className="growth-ask" href={ask(`预测未来${inputs.days}天全店净利润，销量变化${inputs.quantityChange}%，售价变化${inputs.priceChange}%，单位成本变化${inputs.costChange}%，损耗费用降低${inputs.lossReduction}%，其他费用变化${inputs.fixedChange}%，目标净利润${inputs.target_scaled/10000}元。请解释差距与依据。`)}>带着当前条件提问<ArrowRight size={17}/></a><button className="growth-export" onClick={exportReport}><ArrowDownToLine size={15}/>下载完整测算 JSON</button></section><section className="growth-card"><div className="growth-card-heading"><h2>此设备保存的演示方案</h2><span className="growth-pill">{saved.length} 份（拟）</span></div>{saved.length?saved.map(v=><div key={v.id} className="growth-saved-row"><div><b>未来{v.parameters.days}天 · {money(v.profit)}</b><small>{new Date(v.at).toLocaleString('zh-CN',{hour12:false})}</small></div><button disabled={v.caseId!==baseline.caseId||v.baselineRevenue!==baseline.revenue_scaled} onClick={()=>{try{predictProfit(baseline,v.parameters);setInputs(v.parameters);setNotice('已载入演示方案；当前账套未改变。')}catch{setNotice('旧方案参数无效，请重新测算。')}}}>载入</button></div>):<p>调整目标和条件后保存，便于演示不同方案的差异。</p>}</section></section>
 <details className="growth-method"><summary><ShieldCheck size={17}/>数据来源、计算公式与预测边界</summary><p>原始期间 {baseline.originalFrom} 至 {baseline.originalTo}；演示期间 {baseline.from} 至 {baseline.to}（拟）。来源：{baseline.source.name} / {baseline.source.file}。全月销售净额与台账一致，{baseline.checks.filter(v=>v.difference===0).length}/{baseline.checks.length} 项对账通过。</p><p>净利润 = 预测销售净额 − 销售成本 − 损耗费用 − 其他费用。周期基准按历史日均折算；未来销售净额同时应用销量和售价变化，销售成本同时应用销量与单位成本变化，损耗费用再应用改善比例。</p>{forecast?.assumptions.map(a=><p key={a}>{a}</p>)}<a href="/real-data?tab=finance">回查财务报表与流水<ArrowUpRight size={14}/></a></details>
 </>}
 <footer className="growth-footer"><span>智链销 · 从数据到可解释的经营决策</span><span>参赛演示 · 人民币</span></footer></main></div>
}
