"use client";
import {useEffect,useMemo,useState} from 'react';import {BarChart3,Download,Upload,Play,ArrowRight,Database,Check,CalendarDays} from 'lucide-react';import {summarize,type RetailRow} from '../lib/retail';
const money=(n:number)=>'¥'+(n/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const columns=['date','sku','name','opening','received','sold','closing','safety','price_cents','cost_cents','promo'];
function csv(rows:RetailRow[]){return '\uFEFF'+[columns.join(','),...rows.map(r=>columns.map(c=>'"'+String((r as any)[c]).replace(/^([=+@-])/,"'$1").replaceAll('"','""')+'"').join(','))].join('\r\n');}
function parseCsv(text:string){const lines:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(!quoted&&(c===','||c==='\n')){row.push(field.replace(/\r$/,''));field='';if(c==='\n'){if(row.some(Boolean))lines.push(row);row=[];}}else field+=c;}if(quoted)throw Error('CSV 引号不完整');row.push(field.replace(/\r$/,''));if(row.some(Boolean))lines.push(row);const header=lines.shift()?.map(x=>x.replace(/^\uFEFF/,'').trim());if(!header||columns.some(c=>!header.includes(c)))throw Error('CSV 缺少字段，请先下载模板');return lines.map(line=>Object.fromEntries(columns.map(c=>{const v=line[header.indexOf(c)];if(v===undefined||v==='')throw Error('CSV 存在空字段');if(c==='promo'&&!['true','false','0','1'].includes(v.toLowerCase()))throw Error('promo 只能为 true/false 或 1/0');return [c,['date','sku','name'].includes(c)?v:c==='promo'?['true','1'].includes(v.toLowerCase()):Number(v)];})));}
export default function RetailReports(){const [rows,setRows]=useState<RetailRow[]>([]),[source,setSource]=useState('demo'),[user,setUser]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState(''),[sku,setSku]=useState(''),[days,setDays]=useState(7),[uplift,setUplift]=useState(40),[result,setResult]=useState<any>(null),[view,setView]=useState('sales');
async function load(s=source){setBusy(true);setMessage('');setRows([]);setResult(null);try{const r=await fetch('/api/retail?source='+s),d:any=await r.json();if(!r.ok)throw Error(d.error);setRows(d.rows);setUser(d.user);setSku(d.rows[0]?.sku??'');setFrom('');setTo('');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}useEffect(()=>{load();},[]);
const filtered=useMemo(()=>rows.filter(r=>(!from||r.date>=from)&&(!to||r.date<=to)),[rows,from,to]),summary=useMemo(()=>summarize(filtered),[filtered]),max=Math.max(1,...summary.daily.map(d=>d.revenue));
function download(template=false){const blob=new Blob([csv(template?rows.slice(0,2):filtered)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=template?'校园门店数据模板.csv':'校园门店经营明细.csv';a.click();URL.revokeObjectURL(url);}
async function upload(file:File){setBusy(true);try{if(file.size>1000000)throw Error('文件应小于 1MB，每次最多 500 行');const data=parseCsv(await file.text());const r=await fetch('/api/retail',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows:data})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setSource('mine');await load('mine');setMessage('已导入 '+d.count+' 行；相同日期和商品的记录会更新。');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
async function analyze(){setBusy(true);setMessage('');try{const r=await fetch('/api/retail/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source,sku,days,uplift})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setResult(d);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
return <section className="reports-page"><div className="page-heading"><div><small>CAMPUS RETAIL / 校园零售</small><h2>校园便利店 · 经营报表</h2><p>运动会促销备货案例：从每日进销存到活动复盘。</p></div><div className="report-actions"><button onClick={()=>download()} disabled={!filtered.length}><Download size={16}/>导出明细</button><button onClick={()=>download(true)} disabled={!rows.length}>下载模板</button><label className="upload-button"><Upload size={16}/>导入 CSV<input type="file" accept=".csv" disabled={busy||!user} onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);e.target.value='';}}/></label></div></div>
<div className="report-source"><div><span className="outline-tag">{source==='demo'?'模拟案例':'个人导入'}</span><span>{source==='demo'?'6 个商品 · 42 天进销存 · 数据按账实平衡生成，非真实企业记录':'仅管理员可见 · 数据由用户提供，未核验真实性'}</span></div><div><select value={source} onChange={e=>{setSource(e.target.value);load(e.target.value);}}><option value="demo">校园便利店示例</option><option value="mine" disabled={!user}>后台导入数据</option></select>{!user&&<a className="login-link" target="_top" href="/admin">登录后导入</a>}</div></div>
{message&&<div className="editor-message" role="status">{message}</div>}
<div className="report-filters"><CalendarDays size={17}/><label>开始日期<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><span>至</span><label>结束日期<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={()=>{setFrom('');setTo('');}}>全部日期</button><small>金额：人民币 · 单价及成本在明细中以分保存</small></div>
<div className="metric-grid">{[['销售额',money(summary.revenue),'按每日成交价计算'],['销售毛利',money(summary.profit),'未扣房租、人工和营销费用'],['销售件数',summary.units.toLocaleString(),'当前筛选期间合计'],['库存预警',summary.items.filter(i=>i.closing<i.safety).length+' 个商品','筛选期间各商品最后一日']].map(([label,value,note])=><div className="metric" key={label}><small>{label}</small><strong>{value}</strong><p>{note}</p></div>)}</div>
<div className="report-grid"><div className="report-card"><div className="report-card-heading"><h3>每日销售额</h3><span><i/>非活动日 <i className="promo"/>活动日</span></div><div className="bar-chart">{summary.daily.map(d=><div className="bar-slot" key={d.date} title={d.date+'：'+money(d.revenue)}><span className={d.promo?'promo':''} style={{height:Math.max(2,d.revenue/max*135)}}/><small>{d.date.slice(5)}</small></div>)}</div></div><div className="report-card"><h3>促销复盘</h3><div className="review-stat"><span>非活动日均销售额</span><b>{summary.baselineDaily===null?'暂无数据':money(summary.baselineDaily)}</b></div><div className="review-stat"><span>活动日均销售额</span><b>{summary.promoDaily===null?'暂无数据':money(summary.promoDaily)}</b></div><p className="editor-hint">这是描述性对比，未剔除客流、天气等影响，不能直接认定为促销带来的增量。缺少营销费用时不计算 ROI。</p></div></div>
<div className="report-card"><div className="report-card-heading"><h3>经营明细</h3><div className="report-tabs">{[['sales','商品销售'],['stock','库存与补货'],['ledger','每日进销存']].map(([id,n])=><button className={view===id?'active':''} key={id} onClick={()=>setView(id)}>{n}</button>)}</div></div><div className="table-scroll">{view==='ledger'?<table><thead><tr>{['日期','商品','期初','入库','销售','期末','成交价','单位成本','活动'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.date+r.sku}><td>{r.date}</td><td>{r.name}</td><td>{r.opening}</td><td>{r.received}</td><td>{r.sold}</td><td>{r.closing}</td><td>{money(r.price_cents)}</td><td>{money(r.cost_cents)}</td><td>{r.promo?'促销':'—'}</td></tr>)}</tbody></table>:<table><thead><tr>{(view==='sales'?['商品','销售件数','销售额','销售成本','毛利','毛利率']:['商品','库存日期','期末库存','安全库存','安全库存缺口','状态']).map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{summary.items.map(i=><tr key={i.sku}><td>{i.name}<small className="cell-sub">{i.sku}</small></td>{view==='sales'?<><td>{i.units}</td><td>{money(i.revenue)}</td><td>{money(i.cost)}</td><td>{money(i.revenue-i.cost)}</td><td>{i.revenue?((i.revenue-i.cost)/i.revenue*100).toFixed(1)+'%':'—'}</td></>:<><td>{i.date}</td><td>{i.closing}</td><td>{i.safety}</td><td>{Math.max(0,i.safety-i.closing)}</td><td>{i.closing<i.safety?'需关注':'正常'}</td></>}</tr>)}</tbody></table>}</div>{!filtered.length&&<div className="empty-box">当前期间没有记录。</div>}<div className="table-foot">每条记录校验：期初 + 入库 − 销售 = 期末。此简化报表暂不包含退货、盘损与税费。</div></div>
<div className="report-card analysis-box"><div><small>SCENARIO TEST</small><h3>下周运动会，备货够不够？</h3><p>基于此数据集最后库存及最近最多 28 个非促销日销量，按保存的 Agent 参数运行。</p></div><div className="analysis-controls"><label>商品<select value={sku} onChange={e=>setSku(e.target.value)}>{Array.from(new Map(rows.map(r=>[r.sku,r.name]))).map(([s,n])=><option key={s} value={s}>{n}</option>)}</select></label><label>活动天数<input type="number" min={1} max={60} value={days} onChange={e=>setDays(Number(e.target.value))}/></label><label>需求增幅 %<input type="number" min={0} max={300} value={uplift} onChange={e=>setUplift(Number(e.target.value))}/></label><button className="primary" disabled={busy||!sku} onClick={analyze}><Play size={15}/>运行 Agent</button></div>{result&&<div className="scenario-result"><strong>{result.name}：预计销量 {result.forecast}，预计结余 {result.remaining}，建议补货 {result.suggested}。</strong><small>库存截止 {result.asOf} · 增幅是情景假设 · 本次结果未另存运行历史</small>{result.trace.map((t:any)=><div className="scenario-step" key={t.name}><Check size={15}/><b>{t.name}</b><span>{t.output}</span><small>配置 v{t.revision}</small></div>)}</div>}</div>
<div className="case-reference">案例借鉴：<a href="https://www.microsoft.com/en/customers/story/754571-pepsico-consumer-goods-azure-machine-learning" target="_blank" rel="noreferrer">百事门店需求与备货案例</a>。本页面为校园便利店的独立模拟，非百事经营数据。</div>
</section>;
}



