import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,CheckCircle2,AlertCircle,Package,FileText,Wallet,Plus,Download,RefreshCw} from 'lucide-react';
import './workspace.css';
import {useLedgerPeriod} from './ledger-scope';
const money=(n:number|null|undefined)=>n==null?'未提供':(n/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const labels:Record<string,string>={purchase:'采购并入库',sale:'销售并出库',sale_return:'销售退货',expense:'支付经营费用',customer_payment:'收回客户欠款',supplier_payment:'支付供应商欠款',capital:'投入资金',purchase_plan:'拟定采购计划（待审批）'};
function parseMoney(value:string){if(!/^\d+(\.\d{1,2})?$/.test(value))throw Error('金额应为非负数，最多两位小数');const [a,b='']=value.split('.');return Number(a)*100+Number(b.padEnd(2,'0'));}
async function api(path:string,body?:any){const r=await fetch('/api/v2/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
export default function Workspace({admin=false}:{admin?:boolean}){
 const [companies,setCompanies]=useState<any[]>([]),[tenant,setTenant]=useState('demo'),[data,setData]=useState<any>(null),[tab,setTab]=useState('products'),[search,setSearch]=useState(''),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState(false),[productForm,setProductForm]=useState(false),[selected,setSelected]=useState<any>(null);
 const {from,to,setFrom,setTo}=useLedgerPeriod();
 const [type,setType]=useState('sale'),[date,setDate]=useState('2026-09-30'),[partner,setPartner]=useState(''),[note,setNote]=useState(''),[cash,setCash]=useState('0'),[amount,setAmount]=useState('0'),[reference,setReference]=useState(''),[lines,setLines]=useState<any[]>([]),[requestKey,setRequestKey]=useState(''),[receivingPlan,setReceivingPlan]=useState<any>(null);
 const [originalNumber,setOriginalNumber]=useState(''),[sourceFile,setSourceFile]=useState('');
 const [product,setProduct]=useState({id:'',name:'',unit:'瓶',specification:'',category:'',price:'0',safety_stock:10,pack_size:1,lead_days:3});
 useEffect(()=>{if(admin)api('companies').then(d=>{setCompanies(d.companies);const saved=sessionStorage.getItem('zhilian-admin-company');if(d.companies.some((c:any)=>c.id===saved))setTenant(saved!);}).catch(e=>setError(e.message));else api('company-session').then(c=>setTenant(c.tenant)).catch(e=>setError(e.message));},[]);
 async function load(rangeFrom=from,rangeTo=to){setError('');const d=await api('ledger?'+new URLSearchParams({tenant,from:rangeFrom,to:rangeTo}));setData(d);return d;}
 useEffect(()=>{let active=true;setData(null);setSelected(null);setForm(false);setError('');api('ledger?'+new URLSearchParams({tenant,from,to})).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[tenant,from,to]);
 const writable=tenant!=='demo',shown=data?.products.filter((p:any)=>(p.name+p.id+p.category+p.specification).toLowerCase().includes(search.toLowerCase()))??[];
 function newDocument(){setOriginalNumber('');setSourceFile('');setReceivingPlan(null);setType('sale');setPartner('');setNote('');setCash('0');setAmount('0');setReference('');setLines([]);setDate(data?.documents[0]?.date??new Date().toISOString().slice(0,10));setRequestKey(crypto.randomUUID());setForm(true);setError('');}
 function selectType(v:string){setReceivingPlan(null);setType(v);setLines([]);setReference('');setCash('0');setAmount('0');setRequestKey(crypto.randomUUID());}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api(type==='purchase_plan'?'ledger/plan':receivingPlan?'ledger/receive':'ledger',{tenant,revision:data.revision,key:requestKey,date,due_date:date,type,partner,note,plan_id:receivingPlan?.id,cash_cents:parseMoney(cash),amount_cents:parseMoney(amount),reference:reference||undefined,provenance:{kind:'manual',original_number:originalNumber,source_file:sourceFile},lines:lines.map(l=>({product_id:l.product_id,quantity:Number(l.quantity),unit_price_cents:parseMoney(l.price)}))});setForm(false);setStatus(type==='purchase_plan'?'采购计划已保存，审批和实际收货前不会增加库存或财务金额。':'单据已过账：库存流水和财务凭证已同时更新。');setFrom('');setTo('');await load('','');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const total=lines.reduce((n,l)=>{try{return n+Number(l.quantity)*parseMoney(l.price);}catch{return n;}},0);
 function addLine(id:string){const p=data.products.find((p:any)=>p.id===id);if(!p||lines.some(l=>l.product_id===id))return;const original=data.documents.find((d:any)=>d.id===reference)?.lines.find((l:any)=>l.product_id===id);const price=type==='sale_return'?original?.unit_price_cents:['purchase','purchase_plan'].includes(type)?p.latest_purchase_cents??p.price_cents:p.price_cents;setLines([...lines,{product_id:id,quantity:1,price:((price??0)/100).toFixed(2)}]);}
 function exportCSV(){const rows=[['商品编码','商品名称','规格','单位','售价','最近采购价','期间买入','期间卖出','期间退回','期末库存','库存价值','销售净额','销售毛利'],...shown.map((p:any)=>[p.id,p.name,p.specification,p.unit,money(p.price_cents),money(p.latest_purchase_cents),p.bought,p.sold,p.returned,p.stock,money(p.stock_value_cents),money(p.revenue_cents),money(p.profit_cents)])];const csv='\ufeff'+rows.map(r=>r.map((v:any)=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='智链销-商品经营台账.csv';a.click();URL.revokeObjectURL(u);}
 return <div className={'ledger-app '+(admin?'embedded':'')}><header className="ledger-header"><a href="/">智链销<span>经营工作台</span></a><div><a href="/real-data">真实销售案例 ↗</a><a href="/">进入经营咨询 <ArrowRight size={15}/></a>{!admin&&<a href="/admin?tab=ledger">管理账套</a>}</div></header><main>
 <div className="ledger-heading"><div><span className="ledger-kicker">CONNECTED OPERATIONS</span><h1>每一笔经营，都有来处。</h1><p>采购、销售、库存和财务使用同一套单据。数字可追溯，账目可核对。</p></div><div className="ledger-source"><span className="source-dot"/>{data?.source==='synthetic'?'模拟门店 · 教学演示':data?.source==='provided'?'独立企业账套':'空账套'}<small>数据版本 {data?.revision??'—'} · 人民币元</small></div></div>
 <div className="ledger-toolbar">{admin&&<label>账套<select value={tenant} onChange={e=>{setTenant(e.target.value);sessionStorage.setItem('zhilian-admin-company',e.target.value);}}><option value="demo">公共演示门店（只读）</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<label>从<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>至<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={()=>{setFrom('');setTo('');}}>全部日期</button><button onClick={()=>load().catch(e=>setError(e.message))}><RefreshCw size={15}/>刷新</button>{writable&&<button className="ledger-primary" onClick={newDocument} disabled={!data}><Plus size={15}/>记录业务</button>}</div>
 {error&&<div className="ledger-alert" role="alert">{error}</div>}{status&&<div className="ledger-status" role="status">{status}</div>}
 {data&&<><div className="ledger-metrics">{[['销售净额',data.income.revenue_cents,'已扣除销售退货'],['销售毛利',data.income.gross_profit_cents,'销售净额 − 销售成本'],['经营净利润',data.income.net_profit_cents,'毛利 − 已记录经营费用'],['期末库存价值',data.balance.inventory,'移动加权平均成本']].map(([name,value,note]:any)=><div key={name}><small>{name}</small><strong>{money(value)}</strong><span>{note}</span></div>)}</div>
 <div className="ledger-tabs">{[['products','商品台账',Package],['plans','采购计划',Package],['flow','全流程流水',FileText],['documents','业务单据',FileText],['finance','财务报表',Wallet]].map(([id,name,Icon]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={17}/>{name}</button>)}</div>
 {tab==='products'&&<section className="ledger-card"><div className="ledger-card-title"><div><h2>商品经营台账</h2><p>买入、卖出、退回按所选期间统计；库存截至结束日期。售价为当前商品标价。</p></div><div><button onClick={exportCSV}><Download size={15}/>导出台账</button>{writable&&<button onClick={()=>setProductForm(true)}>新增商品</button>}</div></div><input className="ledger-search" aria-label="搜索商品" placeholder="搜索商品名称、编码、规格或品类" value={search} onChange={e=>setSearch(e.target.value)}/><div className="ledger-table"><table><thead><tr>{['商品 / 规格','单位','当前售价','最近采购价','期间买入','期间卖出','退回','期末库存','库存价值','销售净额','销售毛利'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{shown.map((p:any)=><tr key={p.id}><td><button className="text-button" onClick={()=>{setSearch(p.name);setTab('documents');}}>{p.name}</button><small>{p.id} · {p.specification}</small></td><td>{p.unit}</td><td>{money(p.price_cents)}</td><td>{money(p.latest_purchase_cents)}</td><td>{p.bought}</td><td>{p.sold}</td><td>{p.returned}</td><td><span className={p.stock<p.safety_stock?'stock-low':''}>{p.stock}</span></td><td>{money(p.stock_value_cents)}</td><td>{money(p.revenue_cents)}</td><td>{money(p.profit_cents)}</td></tr>)}</tbody></table></div>{!shown.length&&<div className="ledger-empty">{data.products.length?'没有匹配的商品。':'尚无商品记录。'}{admin&&writable&&!data.products.length&&<button disabled={busy} onClick={async()=>{setBusy(true);try{await api('ledger/seed',{tenant,revision:data.revision});setStatus('已在空企业中创建独立模拟账套。');setFrom('');setTo('');await load('','');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>创建完整模拟门店账套</button>}</div>}</section>}
 {tab==='plans'&&<section className="ledger-card"><div className="ledger-card-title"><div><h2>采购计划与分批收货</h2><p>拟定 → 人工审批 → 实际收货 → 库存与财务更新。未收货数量不计入现货。</p></div>{writable&&<button onClick={()=>{newDocument();setType('purchase_plan');}}>拟定采购计划</button>}</div>{!data.plans.length&&<div className="ledger-empty">尚无采购计划。可以先向经营助手咨询备货，再按建议拟定计划。</div>}{data.plans.map((p:any)=><article className="plan-card" key={p.id}><div className="ledger-card-title"><div><h3>{p.partner} · {{draft:'待审批',approved:'已批准',rejected:'已驳回',partial:'部分收货',received:'全部收货'}[p.status as 'draft']}</h3><p>计划到货 {p.due_date} · {p.note}</p></div><div>{admin&&p.status==='draft'&&['approved','rejected'].map(state=><button key={state} disabled={busy} onClick={async()=>{setBusy(true);try{await api('ledger/approve',{tenant,revision:data.revision,id:p.id,status:state});await load();setStatus(state==='approved'?'计划已批准，等待实际收货。':'计划已驳回。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{state==='approved'?'批准':'驳回'}</button>)}{writable&&['approved','partial'].includes(p.status)&&<button onClick={()=>{newDocument();setReceivingPlan(p);setType('purchase');setPartner(p.partner);setLines(p.lines.filter((l:any)=>l.quantity>l.received).map((l:any)=>({product_id:l.product_id,quantity:l.quantity-l.received,price:(l.unit_price_cents/100).toFixed(2)})));}}>记录实际收货</button>}</div></div><div className="ledger-table"><table><thead><tr><th>商品</th><th>计划采购</th><th>已收货</th><th>待收货</th><th>批准单价</th></tr></thead><tbody>{p.lines.map((l:any)=><tr key={l.product_id}><td>{l.name}</td><td>{l.quantity}{l.unit}</td><td>{l.received}{l.unit}</td><td>{l.quantity-l.received}{l.unit}</td><td>{money(l.unit_price_cents)}</td></tr>)}</tbody></table></div></article>)}</section>}
{tab==='flow'&&<section className="ledger-card"><h2>逐笔商品流水</h2><p>期初库存 + 本笔变动 = 本笔结存；按业务日期顺序计算。金额以人民币元展示。</p><input placeholder="筛选商品名称或编码" value={search} onChange={e=>setSearch(e.target.value)}/><div className="ledger-table"><table><thead><tr>{['日期','业务','商品','期初数量','变动数量','结存数量','期初价值','价值变动','结存价值','业务金额','销售成本','原单'].map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{data.flow.filter((r:any)=>(r.name+r.product_id).includes(search)).map((r:any)=><tr key={r.id}><td>{r.date}</td><td>{labels[r.type]}</td><td>{r.name}</td><td>{r.quantity_before}</td><td>{r.quantity}</td><td>{r.quantity_after}</td><td>{money(r.value_before_cents)}</td><td>{money(r.value_cents)}</td><td>{money(r.value_after_cents)}</td><td>{money(r.amount_cents)}</td><td>{money(r.cost_cents)}</td><td><button onClick={()=>setSelected(data.documents.find((d:any)=>d.id===r.document_id))}>查看单据与凭证</button></td></tr>)}</tbody></table></div></section>}
{tab==='documents'&&<section className="ledger-card"><div className="ledger-card-title"><div><h2>业务单据与财务凭证</h2><p>点开单据查看商品明细、成本和借贷分录。</p></div><button onClick={()=>setSearch('')}>显示全部</button></div><input className="ledger-search" aria-label="筛选单据" placeholder="按商品、业务类型或往来单位筛选" value={search} onChange={e=>setSearch(e.target.value)}/><div className="ledger-table"><table><thead><tr>{['日期','业务类型','往来单位','单据金额','现金收付','说明','依据'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{data.documents.filter((d:any)=>(JSON.stringify(d.lines)+d.partner+d.note+labels[d.type]).includes(search)).map((d:any)=><tr key={d.id}><td>{d.date}</td><td>{labels[d.type]}</td><td>{d.partner||'—'}</td><td>{money(d.amount_cents)}</td><td>{money(d.cash_cents)}</td><td>{d.note||'—'}</td><td><button className="text-button" onClick={()=>setSelected(d)}>查看单据</button></td></tr>)}</tbody></table></div></section>}
 {tab==='finance'&&<><section className="ledger-checks"><h2>对账检查 <span>{data.checks.filter((c:any)=>c.ok).length}/{data.checks.length} 通过</span></h2><div>{data.checks.map((c:any)=><article key={c.name} className={c.ok?'check-pass':'check-fail'}>{c.ok?<CheckCircle2 size={18}/>:<AlertCircle size={18}/>}<span>{c.name}</span><b>{c.ok?'平衡':`差额 ${money(c.difference)}`}</b></article>)}</div></section><div className="ledger-report-grid">
 <section className="ledger-card"><h2>利润表</h2><p>所选期间 · 不含所得税</p>{[['销售净额',data.income.revenue_cents],['销售成本',data.income.cost_cents],['销售毛利',data.income.gross_profit_cents],['经营费用',data.income.expense_cents],['经营净利润',data.income.net_profit_cents]].map(([n,v]:any)=><div className="statement-row" key={n}><span>{n}</span><b>{money(v)}</b></div>)}</section>
 <section className="ledger-card"><h2>资产负债表</h2><p>截至 {to||'最后过账日期'}</p>{[['货币资金',data.balance.cash],['应收账款',data.balance.receivable],['库存商品',data.balance.inventory],['资产合计',data.balance.assets_cents],['应付账款',-data.balance.payable],['投入资本',-data.balance.capital],['累计未分配利润',data.balance.retained_cents],['负债与权益合计',data.balance.liabilities_cents+data.balance.equity_cents]].map(([n,v]:any)=><div className="statement-row" key={n}><span>{n}</span><b>{money(v)}</b></div>)}</section>
 <section className="ledger-card"><h2>现金流量表</h2><p>收付实现口径</p>{[['期初货币资金',data.cashflow.opening_cents],['经营活动净流量',data.cashflow.operating_cents],['投资活动净流量',data.cashflow.investing_cents],['筹资活动净流量',data.cashflow.financing_cents],['现金净增加额',data.cashflow.change_cents],['期末货币资金',data.cashflow.closing_cents]].map(([n,v]:any)=><div className="statement-row" key={n}><span>{n}</span><b>{money(v)}</b></div>)}</section></div>
 <section className="ledger-card"><h2>利润如何变成经营现金流</h2><p>所选期间的差额可以逐项核对。库存、应收和应付减少时显示负数。</p><div className="statement-row"><span>经营净利润 − 库存增加 − 应收增加 + 应付增加 = 经营现金流</span></div><div className="statement-row"><b>{money(data.bridge.profit_cents)} − ({money(data.bridge.inventory_change_cents)}) − ({money(data.bridge.receivable_change_cents)}) + ({money(data.bridge.payable_change_cents)}) = {money(data.bridge.operating_cents)}</b></div></section><section className="ledger-card"><h2>往来款明细</h2><div className="ledger-table"><table><thead><tr><th>日期</th><th>类型</th><th>往来单位</th><th>未结金额</th></tr></thead><tbody>{data.outstanding.map((d:any)=><tr key={d.id}><td>{d.date}</td><td>{d.type==='sale'?'应收':'应付'}</td><td>{d.partner}</td><td>{money(d.outstanding_cents)}</td></tr>)}</tbody></table></div></section>
 <section className="ledger-card"><h2>月度经营趋势</h2><div className="ledger-table"><table><thead><tr><th>月份</th><th>销售净额</th><th>销售成本</th><th>经营费用</th><th>经营净利润</th></tr></thead><tbody>{data.monthly.map((m:any)=><tr key={m.month}><td>{m.month}</td><td>{money(m.revenue_cents)}</td><td>{money(m.cost_cents)}</td><td>{money(m.expense_cents)}</td><td>{money(m.revenue_cents-m.cost_cents-m.expense_cents)}</td></tr>)}</tbody></table></div></section><details className="ledger-card"><summary>查看科目试算平衡表</summary><div className="ledger-table"><table><thead><tr><th>科目</th><th>借方发生额</th><th>贷方发生额</th><th>借方余额（负数为贷方）</th></tr></thead><tbody>{data.trial.map((t:any)=><tr key={t.account}><td>{t.name}</td><td>{money(t.debit_cents)}</td><td>{money(t.credit_cents)}</td><td>{money(t.balance_cents)}</td></tr>)}</tbody></table></div></details></>}
 <footer className="ledger-policy">{data.policy}{tenant==='demo'&&<p>公共账套只读。到管理后台创建企业，即可在独立账套录入采购、销售、退货、费用和收付款。</p>}</footer></>}
 {!data&&!error&&<p role="status" className="ledger-empty">正在核对经营账套…</p>}
 </main>
 {selected&&<div className="ledger-modal"><section><button className="ledger-close" onClick={()=>setSelected(null)}>关闭</button><span className="ledger-kicker">SOURCE DOCUMENT</span><h2>{labels[selected.type]} · {selected.date}</h2><p>{selected.partner} / {selected.note}</p><small>单据编号 {selected.id}</small><p>来源：{selected.provenance?.kind==='synthetic'?'模拟记录':selected.provenance?.kind==='manual'?'人工录入，凭证真实性待核验':'来源待核验'} · 原始单号 {selected.provenance?.original_number||'未提供'} · 文件 {selected.provenance?.source_file||'未提供'} · 原表行号 {selected.provenance?.source_row??'未提供'}</p><div className="ledger-table"><table><thead><tr><th>商品</th><th>数量</th><th>单价</th><th>金额</th><th>成本</th></tr></thead><tbody>{selected.lines.map((l:any)=><tr key={l.id}><td>{l.name}</td><td>{l.quantity}{l.unit}</td><td>{money(l.unit_price_cents)}</td><td>{money(l.amount_cents)}</td><td>{money(l.cost_cents)}</td></tr>)}</tbody></table></div><h3>同步财务凭证</h3><div className="ledger-table"><table><thead><tr><th>科目</th><th>借方</th><th>贷方</th></tr></thead><tbody>{selected.journal.map((j:any)=><tr key={j.id}><td>{{cash:'货币资金',receivable:'应收账款',inventory:'库存商品',payable:'应付账款',capital:'投入资本',revenue:'销售收入',cogs:'销售成本',expense:'经营费用'}[j.account as 'cash']??j.account}</td><td>{money(j.debit_cents)}</td><td>{money(j.credit_cents)}</td></tr>)}</tbody></table></div>{selected.reference&&<small>关联原单 {selected.reference}</small>}</section></div>}
 {form&&<div className="ledger-modal"><form onSubmit={submit}><button type="button" className="ledger-close" onClick={()=>setForm(false)}>关闭</button><h2>记录经营业务</h2><p>{type==='purchase_plan'?'计划经管理员审核后才能收货；拟定计划不会改变库存或财务。':receivingPlan?'按实际数量收货，可分批入库；未收部分保留在采购计划。':'提交后同时生成库存流水与财务凭证。单据按日期顺序过账。'}</p><div className="ledger-form-grid"><label>业务类型<select disabled={!!receivingPlan} value={type} onChange={e=>selectType(e.target.value)}>{Object.entries(labels).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label>{type==='purchase_plan'?'计划到货日期':'业务日期'}<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>往来单位 / 费用名称<input required value={partner} onChange={e=>setPartner(e.target.value)} maxLength={100}/></label><label>原始单号<input value={originalNumber} onChange={e=>setOriginalNumber(e.target.value)} maxLength={100}/></label><label>凭证文件 / 依据<input value={sourceFile} onChange={e=>setSourceFile(e.target.value)} maxLength={200}/></label><label>备注<input value={note} onChange={e=>setNote(e.target.value)} maxLength={500}/></label></div>
 {['sale_return','customer_payment','supplier_payment'].includes(type)&&<label>关联原始单据<select required value={reference} onChange={e=>{setReference(e.target.value);setLines([]);}}><option value="">请选择原单（可切换全部日期查找）</option>{(type==='sale_return'?data.documents.filter((d:any)=>d.type==='sale'):data.outstanding.filter((d:any)=>d.type===(type==='customer_payment'?'sale':'purchase'))).map((d:any)=><option key={d.id} value={d.id}>{d.date} · {d.partner} · {money(d.outstanding_cents??d.amount_cents)} · {d.id.slice(0,8)}</option>)}</select></label>}
 {['sale','purchase','sale_return','purchase_plan'].includes(type)?<><label>添加商品<select value="" onChange={e=>addLine(e.target.value)}><option value="">选择商品</option>{data.products.filter((p:any)=>(!receivingPlan||receivingPlan.lines.some((l:any)=>l.product_id===p.id&&l.quantity>l.received))&&(type!=='sale_return'||data.documents.find((d:any)=>d.id===reference)?.lines.some((l:any)=>l.product_id===p.id))).map((p:any)=><option key={p.id} value={p.id}>{p.name} · 可售 {p.stock}{p.unit}</option>)}</select></label>{lines.map((l,i)=><div className="ledger-line" key={l.product_id}><b>{data.products.find((p:any)=>p.id===l.product_id)?.name}</b><label>数量<input required type="number" min={1} step={1} value={l.quantity} onChange={e=>setLines(lines.map((x,n)=>n===i?{...x,quantity:e.target.value}:x))}/></label><label>单价（元）<input required value={l.price} readOnly={type==='sale_return'||!!receivingPlan} onChange={e=>setLines(lines.map((x,n)=>n===i?{...x,price:e.target.value}:x))}/></label><button type="button" onClick={()=>setLines(lines.filter((_,n)=>n!==i))}>移除</button></div>)}<div className="statement-row"><span>单据金额</span><b>{money(total)}</b></div>{type!=='purchase_plan'&&<><label>{type==='sale'?'本次实际收款（剩余记应收）':type==='purchase'?'本次实际付款（剩余记应付）':'本次退款（剩余冲减应收）'}<input required value={cash} onChange={e=>setCash(e.target.value)}/></label><button type="button" onClick={()=>setCash((total/100).toFixed(2))}>全额现金收付</button></>}</>:<label>实际收付金额（元）<input required value={amount} onChange={e=>{setAmount(e.target.value);setCash(e.target.value);}}/></label>}
 {error&&<div className="ledger-alert" role="alert">{error}</div>}<button className="ledger-primary" disabled={busy}>{busy?'正在保存…':type==='purchase_plan'?'提交采购计划':'确认记录并过账'}</button></form></div>}
 {productForm&&<div className="ledger-modal"><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const {price,...fields}=product;await api('ledger/product',{tenant,revision:data.revision,product:{...fields,price_cents:parseMoney(price)}});await load();setProductForm(false);setStatus('商品已建立，库存从零开始，由入库单增加。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><button type="button" className="ledger-close" onClick={()=>setProductForm(false)}>关闭</button><h2>新增商品</h2>{[['id','商品编码'],['name','商品名称'],['unit','基础单位'],['specification','规格'],['category','品类'],['price','当前售价（元）']].map(([id,n])=><label key={id}>{n}<input required={['id','name','unit','price'].includes(id)} value={(product as any)[id]} onChange={e=>setProduct({...product,[id]:e.target.value})}/></label>)}<div className="ledger-form-grid">{[['safety_stock','安全库存'],['pack_size','采购包装倍数'],['lead_days','采购交期（天）']].map(([id,n])=><label key={id}>{n}<input type="number" min={id==='pack_size'?1:0} required value={(product as any)[id]} onChange={e=>setProduct({...product,[id]:Number(e.target.value)})}/></label>)}</div>{error&&<div className="ledger-alert">{error}</div>}<button disabled={busy} className="ledger-primary">建立商品</button></form></div>}
 </div>;
}
